<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>zswl-mithras</artifactId>
        <groupId>cn.zswltech</groupId>
        <version>${revision}</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>zswl-mithras-dashboard</artifactId>

    <properties>
        <maven.compiler.source>8</maven.compiler.source>
        <maven.compiler.target>8</maven.compiler.target>
    </properties>

    <dependencies>
        <dependency>
            <groupId>cn.zswltech</groupId>
            <artifactId>zswl-mithras-api</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>cn.zswltech</groupId>
            <artifactId>zswl-mithras-foundation</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>cn.zswltech</groupId>
            <artifactId>zswl-mithras-basedata</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>cn.zswltech</groupId>
            <artifactId>gruul-spring-boot-starter</artifactId>
            <version>3.5.2-mithras.RELEASE</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>cn.zswltech</groupId>
            <artifactId>zswl-mithras-customer</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>cn.zswltech</groupId>
            <artifactId>zswl-mithras-riskcontrol</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>cn.zswltech</groupId>
            <artifactId>zswl-mithras-assetclassify</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>cn.zswltech</groupId>
            <artifactId>zswl-mithras-afterlease</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>cn.zswltech</groupId>
            <artifactId>zswl-mithras-contract</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>cn.zswltech</groupId>
            <artifactId>zswl-mithras-system</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>cn.zswltech</groupId>
            <artifactId>zswl-mithras-payment</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>cn.zswltech</groupId>
            <artifactId>zswl-mithras-fund</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>cn.zswltech</groupId>
            <artifactId>zswl-mithras-kpi</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>cn.zswltech</groupId>
            <artifactId>zswl-mithras-projectprocess</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>cn.zswltech</groupId>
            <artifactId>zswl-mithras-workflow</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>org.flowable</groupId>
            <artifactId>flowable-engine</artifactId>
            <version>6.7.2</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>cn.zswltech.flow</groupId>
            <artifactId>core</artifactId>
            <version>1.5.11-mithras-RELEASE</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>cn.zswltech</groupId>
            <artifactId>sleipnir-toolkit</artifactId>
            <version>1.1.7-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
        </dependency>
        <dependency>
            <groupId>cn.hutool</groupId>
            <artifactId>hutool-all</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.poi</groupId>
            <artifactId>poi</artifactId>
            <version>4.1.2</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-boot-starter</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>io.swagger</groupId>
            <artifactId>swagger-annotations</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>javax.validation</groupId>
            <artifactId>validation-api</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-annotations</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
            <scope>provided</scope>
        </dependency>
    </dependencies>
</project>
