CREATE TABLE `contract_settle_plan_lib` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键id',
  `contract_id` bigint(20) unsigned NOT NULL COMMENT '合同id',
  `settle_type` varchar(20) NOT NULL COMMENT '结清类型',
  `outstanding_rent` bigint(20) unsigned NOT NULL COMMENT '到期未付租金',
  `before_maturity_principal` bigint(20) unsigned NOT NULL COMMENT '未到期本金',
  `loss` bigint(20) unsigned DEFAULT NULL COMMENT '损失金',
  `liquidated_damages` bigint(20) unsigned DEFAULT NULL COMMENT '违约金',
  `earnest_balance` bigint(20) unsigned DEFAULT NULL COMMENT '保证金余额',
  `is_earnest_deduction` tinyint(4) NOT NULL COMMENT '保证金是否内扣',
  `nominal_price` bigint(20) unsigned DEFAULT NULL COMMENT '名义货价',
  `apply_derate_amount` bigint(20) unsigned DEFAULT NULL COMMENT '申请减免金额',
  `original_deadline` date NOT NULL COMMENT '原到期日',
  `total_amount` bigint(20) unsigned DEFAULT NULL COMMENT '合计金额',
  `apply_settle_date` date DEFAULT NULL COMMENT '申请结清日期',
  `create_by` bigint(20) DEFAULT NULL COMMENT '创建人、发起人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` bigint(20) DEFAULT NULL COMMENT '最后更新人id',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `version` varchar(40) NOT NULL COMMENT '版本号',
  `origin_id` bigint(20) NOT NULL COMMENT '临时数据表id 需要用来比对数据 或者 流程拒绝时全量回写',
  `data_create_time` datetime DEFAULT NULL,
  `data_create_by` bigint(20) DEFAULT NULL,
  `data_update_time` datetime DEFAULT NULL,
  `data_update_by` bigint(20) DEFAULT NULL,
  `version_type` tinyint(4) DEFAULT '1' COMMENT '版本标志，0无效，1有效...业务自扩展',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='合同明细-结清方案版本表';