<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>cn.zswltech</groupId>
        <artifactId>zswl-root-pom</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>
    <packaging>pom</packaging>
    <artifactId>zswl-mithras</artifactId>
    <version>${revision}</version>
    <modules>
        <module>zswl-mithras-api</module>
        <module>zswl-mithras-service-core</module>
        <module>zswl-mithras-domain-creditreport</module>
        <module>zswl-mithras-domain-xinsight</module>
        <module>zswl-mithras-domain-ep</module>
        <module>zswl-mithras-domain-guanbao</module>
        <module>zswl-mithras-domain-log</module>
        <module>zswl-mithras-domain-async</module>
        <module>zswl-mithras-domain-associationreport</module>
        <module>zswl-mithras-domain-kpi</module>
        <module>zswl-mithras-domain-factory</module>
        <module>zswl-mithras-blackgray</module>
        <module>zswl-mithras-capital</module>
        <module>zswl-mithras-domain-finance</module>
        <module>zswl-mithras-finance</module>
        <module>zswl-mithras-domain-fund-direct</module>
        <module>zswl-mithras-domain-fund</module>
        <module>zswl-mithras-fund</module>
        <module>zswl-mithras-domain-leaseholdproperty</module>
        <module>zswl-mithras-leaseholdproperty</module>
        <module>zswl-mithras-domain-datashare</module>
        <module>zswl-mithras-domain-basedata</module>
        <module>zswl-mithras-domain-margin</module>
        <module>zswl-mithras-domain-projlifecycle</module>
        <module>zswl-mithras-policy</module>
        <module>zswl-mithras-credit</module>
        <module>zswl-mithras-domain-monthly</module>
        <module>zswl-mithras-domain-assetclassify</module>
        <module>zswl-mithras-assetclassify</module>
        <module>zswl-mithras-domain-liquiditymanage</module>
        <module>zswl-mithras-liquidity</module>
        <module>zswl-mithras-filingmaterials</module>
        <module>zswl-mithras-archives</module>
        <module>zswl-mithras-domain-financeprojectdistribution</module>
        <module>zswl-mithras-ftp</module>
        <module>zswl-mithras-domain-projectprocess</module>
        <module>zswl-mithras-project</module>
        <module>zswl-mithras-domain-payment</module>
        <module>zswl-mithras-payment</module>
        <module>zswl-mithras-domain-afterlease</module>
        <module>zswl-mithras-afterlease</module>
        <module>zswl-mithras-domain-budget</module>
        <module>zswl-mithras-budget</module>
        <module>zswl-mithras-customer</module>
        <module>zswl-mithras-identity</module>
        <module>zswl-mithras-contract</module>
        <module>zswl-mithras-domain-collection</module>
        <module>zswl-mithras-riskcontrol</module>
        <module>zswl-mithras-domain-workbench</module>
        <module>zswl-mithras-workbench</module>
        <module>zswl-mithras-third</module>
        <module>zswl-mithras-domain-message</module>
        <module>zswl-mithras-domain-dashboard</module>
        <module>zswl-mithras-dashboard</module>
        <module>zswl-mithras-workflow</module>
        <module>zswl-mithras-document</module>
        <module>zswl-mithras-kpi</module>
        <module>zswl-mithras-domain-creditlimit</module>
        <module>zswl-mithras-domain-metric</module>
        <module>zswl-mithras-domain-system</module>
        <module>zswl-mithras-service</module>
        <module>zswl-mithras-report</module>
        <module>zswl-mithras-web</module>
    </modules>
    <properties>
        <revision>0.0.9-SNAPSHOT</revision>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.source>8</maven.compiler.source>
        <maven.compiler.target>8</maven.compiler.target>
        <httpcomponents.version>4.5.12</httpcomponents.version>
        <hibernate.validator.version>6.0.17.Final</hibernate.validator.version>
        <org.mapstruct.version>1.5.2.Final</org.mapstruct.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>cn.zswltech.lib</groupId>
                <artifactId>crypto-open-starter</artifactId>
                <version>1.0.2</version>
            </dependency>
            <dependency>
                <groupId>com.alibaba</groupId>
                <artifactId>QLExpress</artifactId>
                <version>3.3.1</version>
            </dependency>
            <dependency>
                <groupId>org.hibernate.validator</groupId>
                <artifactId>hibernate-validator</artifactId>
                <version>${hibernate.validator.version}</version>
            </dependency>
            <dependency>
                <groupId>com.github.pagehelper</groupId>
                <artifactId>pagehelper</artifactId>
                <version>5.0.4</version>
            </dependency>
            <dependency>
                <groupId>io.minio</groupId>
                <artifactId>minio</artifactId>
                <version>8.3.4</version>
            </dependency>
            <dependency>
                <groupId>com.squareup.okhttp3</groupId>
                <artifactId>okhttp</artifactId>
                <version>4.9.3</version>
            </dependency>
            <dependency>
                <groupId>com.zswltec</groupId>
                <artifactId>providence-api</artifactId>
                <version>1.0.15-SNAPSHOT</version>
            </dependency>
        </dependencies>

    </dependencyManagement>

    <dependencies>

        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
        </dependency>

    </dependencies>
    <distributionManagement>
        <repository>
            <id>publicRepo</id>
            <name>nexus-releases</name>
            <url>http://10.158.32.191:8081/repository/maven-releases/</url>
        </repository>
        <snapshotRepository>
            <id>publicRepo</id>
            <name>maven-snapshots</name>
            <url>http://10.158.32.191:8081/repository/maven-snapshots/</url>
        </snapshotRepository>
    </distributionManagement>

</project>
