package cn.zswltech.mithras.fund.direct.application.directfinancing;

import cn.zswltech.mithras.api.fund.directfinancing.FundDirectFinancingSubscriptionDetailApi;

public interface FundDirectFinancingSubscriptionDetailApplicationService extends FundDirectFinancingSubscriptionDetailApi {
}
