alter table `after_lease_check_project_report_base` add column `biz_dept_id` bigint(20) default null comment '业务部门id';
alter table `after_lease_check_project_report_base` add column `biz_dept_name` varchar(50) default null comment '业务部门名称';
alter table `after_lease_check_project_report_base` add column `project_sponsor_id` bigint(20) default null comment '项目主办id';
alter table `after_lease_check_project_report_base` add column `project_sponsor_name` varchar(20) default null comment '项目主办名称';
alter table `after_lease_check_project_report_base` add column `risk_manager_id` bigint(20) default null comment '协查风控经理id';
alter table `after_lease_check_project_report_base` add column `risk_manager_name` varchar(20) default null comment '协查风控经理名称';
alter table `after_lease_check_project_report_base` add column `check_way` varchar(20) default null comment '检查形式';
alter table `after_lease_check_project_report_base` add column `client_id` bigint(20) default null comment '客户id';
alter table `after_lease_check_project_report_base` add column `project_name` varchar(100) default null comment '项目名称';
alter table `after_lease_check_project_report_base` add column `project_cosponsor_list` json default null comment '协办信息';

CREATE TABLE `after_lease_check_project_report_meta` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `check_plan_project_id` bigint(20) NOT NULL COMMENT '检查计划项目表主键id',
  `report_type` varchar(20) DEFAULT NULL COMMENT '检查报告类型',
  `create_by` bigint(20) DEFAULT NULL COMMENT '创建人、发起人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` bigint(20) DEFAULT NULL COMMENT '最后更新人id',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_plan_project_id` (`check_plan_project_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='租后检查报告元数据表';

CREATE TABLE `after_lease_check_project_report_meta_lib` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `check_plan_project_id` bigint(20) NOT NULL COMMENT '检查计划项目表主键id',
  `report_type` varchar(20) DEFAULT NULL COMMENT '检查报告类型',
  `create_by` bigint(20) DEFAULT NULL COMMENT '创建人、发起人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` bigint(20) DEFAULT NULL COMMENT '最后更新人id',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `version` varchar(40) NOT NULL COMMENT '版本号',
  `origin_id` bigint(20) NOT NULL COMMENT '临时数据表id 需要用来比对数据 或者 流程拒绝时全量回写',
  `data_create_time` datetime DEFAULT NULL,
  `data_create_by` bigint(20) DEFAULT NULL,
  `data_update_time` datetime DEFAULT NULL,
  `data_update_by` bigint(20) DEFAULT NULL,
  `version_type` tinyint(4) DEFAULT '1' COMMENT '版本标志，0无效，1有效...业务自扩展',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_plan_project_id` (`check_plan_project_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='租后检查报告元数据版本表';

CREATE TABLE `after_lease_check_project_report_base_lib` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `check_plan_project_id` bigint(20) NOT NULL COMMENT '检查计划项目表主键id',
  `check_period_start` date DEFAULT NULL COMMENT '检查时段（开始）',
  `check_period_end` date DEFAULT NULL COMMENT '检查时段（结束）',
  `check_date` date NOT NULL COMMENT '检查日期',
  `main_person` varchar(50) DEFAULT '' COMMENT '主要受访人员',
  `job` varchar(50) DEFAULT '' COMMENT '职务',
  `contact_way` varchar(50) DEFAULT '' COMMENT '联系方式',
  `contract_amount` bigint(20) NOT NULL COMMENT '合同金额',
  `risk_exposure` bigint(20) NOT NULL COMMENT '风险敞口',
  `deadline` date NOT NULL COMMENT '到期日',
  `client_name` varchar(200) DEFAULT NULL COMMENT '客户名称',
  `industry` varchar(50) DEFAULT NULL COMMENT '行业',
  `next_repay_date` date DEFAULT NULL COMMENT '下次还款日期',
  `next_repay_amount` bigint(20) DEFAULT NULL COMMENT '下次还款金额',
  `biz_dept_id` bigint(20) DEFAULT NULL COMMENT '业务部门id',
  `biz_dept_name` varchar(50) DEFAULT NULL COMMENT '业务部门名称',
  `project_sponsor_id` bigint(20) DEFAULT NULL COMMENT '项目主办id',
  `project_sponsor_name` varchar(20) DEFAULT NULL COMMENT '项目主办名称',
  `risk_manager_id` bigint(20) DEFAULT NULL COMMENT '协查风控经理id',
  `risk_manager_name` varchar(20) DEFAULT NULL COMMENT '协查风控经理名称',
  `check_way` varchar(20) DEFAULT NULL COMMENT '检查形式',
  `client_id` bigint(20) DEFAULT NULL COMMENT '客户id',
  `project_name` varchar(100) DEFAULT NULL COMMENT '项目名称',
  `project_cosponsor_list` json default null comment '协办信息',
  `create_by` bigint(20) DEFAULT NULL COMMENT '创建人、发起人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` bigint(20) DEFAULT NULL COMMENT '最后更新人id',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `version` varchar(40) NOT NULL COMMENT '版本号',
  `origin_id` bigint(20) NOT NULL COMMENT '临时数据表id 需要用来比对数据 或者 流程拒绝时全量回写',
  `data_create_time` datetime DEFAULT NULL,
  `data_create_by` bigint(20) DEFAULT NULL,
  `data_update_time` datetime DEFAULT NULL,
  `data_update_by` bigint(20) DEFAULT NULL,
  `version_type` TINYINT(4) DEFAULT 1 COMMENT '版本标志，0无效，1有效...业务自扩展',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='租后检查报告基本信息版本表';

CREATE TABLE `after_lease_check_project_report_content_lib` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `check_plan_project_id` bigint(20) NOT NULL COMMENT '检查计划项目表主键id',
  `template_id` bigint(20) NOT NULL COMMENT '检查内容模板id',
  `template_group_name` varchar(50) DEFAULT NULL COMMENT '检查内容模板分组名称',
  `template_code` varchar(50) DEFAULT NULL COMMENT '检查内容模板条目code',
  `template_title` varchar(100) NOT NULL COMMENT '检查内容模板条目',
  `template_content_input_type` varchar(20) NOT NULL COMMENT '检查内容模板输入框类型',
  `template_content_input_option` varchar(100) DEFAULT NULL COMMENT '检查内容模板输入框枚举类型（如果是下拉框等才会有值）',
  `template_order_num` int(11) NOT NULL DEFAULT '0' COMMENT '检查模板条目排序',
  `content` varchar(2000) DEFAULT NULL COMMENT '填写的检查内容',
  `create_by` bigint(20) DEFAULT NULL COMMENT '创建人、发起人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` bigint(20) DEFAULT NULL COMMENT '最后更新人id',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `version` varchar(40) NOT NULL COMMENT '版本号',
  `origin_id` bigint(20) NOT NULL COMMENT '临时数据表id 需要用来比对数据 或者 流程拒绝时全量回写',
  `data_create_time` datetime DEFAULT NULL,
  `data_create_by` bigint(20) DEFAULT NULL,
  `data_update_time` datetime DEFAULT NULL,
  `data_update_by` bigint(20) DEFAULT NULL,
  `version_type` tinyint(4) DEFAULT '1' COMMENT '版本标志，0无效，1有效...业务自扩展',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='租后检查报告检查内容版本表';

CREATE TABLE `after_lease_check_project_report_summary_lib` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `check_plan_project_id` bigint(20) NOT NULL COMMENT '检查计划项目表主键id',
  `template_id` bigint(20) NOT NULL COMMENT '检查总结模板id',
  `template_group_name` varchar(50) DEFAULT NULL COMMENT '检查总结条目分组',
  `template_code` varchar(50) DEFAULT NULL COMMENT '检查总结模板条目code',
  `template_title` varchar(100) NOT NULL DEFAULT '' COMMENT '检查总结模板条目',
  `template_content_input_type` varchar(20) NOT NULL DEFAULT '' COMMENT '检查总结模板输入框类型',
  `template_content_input_option` varchar(100) DEFAULT NULL COMMENT '检查总结模板输入框枚举类型（如果是下拉框等才会有值）',
  `template_order_num` int(11) NOT NULL DEFAULT '0' COMMENT '检查总结模板条目排序',
  `content` varchar(2000) DEFAULT NULL COMMENT '填写的检查内容',
  `create_by` bigint(20) DEFAULT NULL COMMENT '创建人、发起人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` bigint(20) DEFAULT NULL COMMENT '最后更新人id',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,`version` varchar(40) NOT NULL COMMENT '版本号',
  `origin_id` bigint(20) NOT NULL COMMENT '临时数据表id 需要用来比对数据 或者 流程拒绝时全量回写',
  `data_create_time` datetime DEFAULT NULL,
  `data_create_by` bigint(20) DEFAULT NULL,
  `data_update_time` datetime DEFAULT NULL,
  `data_update_by` bigint(20) DEFAULT NULL,
  `version_type` tinyint(4) DEFAULT '1' COMMENT '版本标志，0无效，1有效...业务自扩展',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='租后检查报告检查总结版本表';

CREATE TABLE `after_lease_check_project_report_extra_lib` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `check_plan_project_id` bigint(20) NOT NULL COMMENT '检查计划项目表主键id',
  `template_id` bigint(20) NOT NULL COMMENT '检查报告模板id',
  `template_code` varchar(50) DEFAULT NULL COMMENT '检查报告模板条目code',
  `template_title` varchar(100) NOT NULL DEFAULT '' COMMENT '检查报告模板条目',
  `template_order_num` int(11) NOT NULL DEFAULT '0' COMMENT '检查报告模板条目排序',
  `check_result` tinyint(4) DEFAULT NULL COMMENT '检查结果',
  `remark` varchar(2000) DEFAULT NULL COMMENT '备注',
  `create_by` bigint(20) DEFAULT NULL COMMENT '创建人、发起人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` bigint(20) DEFAULT NULL COMMENT '最后更新人id',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `version` varchar(40) NOT NULL COMMENT '版本号',
  `origin_id` bigint(20) NOT NULL COMMENT '临时数据表id 需要用来比对数据 或者 流程拒绝时全量回写',
  `data_create_time` datetime DEFAULT NULL,
  `data_create_by` bigint(20) DEFAULT NULL,
  `data_update_time` datetime DEFAULT NULL,
  `data_update_by` bigint(20) DEFAULT NULL,
  `version_type` tinyint(4) DEFAULT '1' COMMENT '版本标志，0无效，1有效...业务自扩展',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='租后检查报告补充说明（非公用事业）版本表';

CREATE TABLE `after_lease_check_project_report_finance_lib` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `check_plan_project_id` bigint(20) NOT NULL COMMENT '检查计划项目表主键id',
  `client_id` bigint(20) NOT NULL COMMENT '客户id',
  `client_project_identity` varchar(20) DEFAULT NULL COMMENT '客户在项目中的身份',
  `subject_type` varchar(50) NOT NULL DEFAULT '' COMMENT '报表类型',
  `query_json` text COMMENT '查询条件json',
  `data_json` text COMMENT '查询结果json',
  `create_by` bigint(20) DEFAULT NULL COMMENT '创建人、发起人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` bigint(20) DEFAULT NULL COMMENT '最后更新人id',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,`version` varchar(40) NOT NULL COMMENT '版本号',
  `origin_id` bigint(20) NOT NULL COMMENT '临时数据表id 需要用来比对数据 或者 流程拒绝时全量回写',
  `data_create_time` datetime DEFAULT NULL,
  `data_create_by` bigint(20) DEFAULT NULL,
  `data_update_time` datetime DEFAULT NULL,
  `data_update_by` bigint(20) DEFAULT NULL,
  `version_type` tinyint(4) DEFAULT '1' COMMENT '版本标志，0无效，1有效...业务自扩展',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='租后检查报告财务报表快照数据版本表';

CREATE TABLE `after_lease_check_external_query_lib` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键id',
  `inspection_month` datetime DEFAULT NULL COMMENT '所属检查月',
  `proj_review_id` bigint(20) DEFAULT NULL COMMENT '项目id',
  `proj_name` varchar(255) DEFAULT NULL COMMENT '项目名称',
  `client_id` bigint(20) DEFAULT NULL COMMENT '客户id',
  `proj_sponsor_user_id` bigint(20) DEFAULT NULL COMMENT '项目主办用户id',
  `deadline` date DEFAULT NULL COMMENT '合同最终到期日',
  `inspection_date` date DEFAULT NULL COMMENT '检查日期',
  `approval_pass_time` datetime DEFAULT NULL COMMENT '审批通过时间',
  `approval_status` varchar(20) DEFAULT NULL COMMENT '状态',
  `dept_id` bigint(20) DEFAULT NULL COMMENT '租后检查部门',
  `industry_type` varchar(50) DEFAULT NULL COMMENT '行业',
  `risk_exposure` bigint(20) DEFAULT NULL COMMENT '风险敞口余额',
  `contract_total_amount` bigint(20) DEFAULT NULL COMMENT '合同金额',
  `next_repay_date` date DEFAULT NULL COMMENT '下次还款日',
  `next_repay_amount` bigint(20) DEFAULT NULL COMMENT '下次还款金额',
  `preventive_measures` varchar(500) DEFAULT NULL COMMENT '风险信号及重大事项、风险防范措施',
  `query_conclusion` varchar(500) DEFAULT NULL COMMENT '查询分析与查询结论',
  `create_by` bigint(20) DEFAULT NULL COMMENT '创建人、发起人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` bigint(20) DEFAULT NULL COMMENT '最后更新人id',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `biz_dept_leader` bigint(20) DEFAULT NULL,
  `biz_division_leader` bigint(20) DEFAULT NULL,
  `process_instance_id` varchar(50) DEFAULT NULL COMMENT '运行中的流程id',
  `version` varchar(40) NOT NULL COMMENT '版本号',
  `origin_id` bigint(20) NOT NULL COMMENT '临时数据表id 需要用来比对数据 或者 流程拒绝时全量回写',
  `data_create_time` datetime DEFAULT NULL,
  `data_create_by` bigint(20) DEFAULT NULL,
  `data_update_time` datetime DEFAULT NULL,
  `data_update_by` bigint(20) DEFAULT NULL,
  `version_type` tinyint(4) DEFAULT '1' COMMENT '版本标志，0无效，1有效...业务自扩展',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='租后检查外部查询任务版本表';

CREATE TABLE `after_lease_check_external_query_client_info_lib` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `query_id` bigint(20) DEFAULT NULL COMMENT '所属外部信息查询任务id',
  `client_role` varchar(20) DEFAULT NULL COMMENT '客户角色-主承租人（Main lessee）承租人（）担保人（）',
  `client_id` bigint(20) DEFAULT NULL COMMENT '承租人/担保人id',
  `client_type` varchar(30) DEFAULT NULL COMMENT '客户类型',
  `query_time_from` date DEFAULT NULL COMMENT '查询时间',
  `query_time_to` date DEFAULT NULL COMMENT '查询时间',
  `credit_info` varchar(500) DEFAULT NULL COMMENT '全国企业信用信息公示系统查询',
  `court_info` varchar(500) DEFAULT NULL COMMENT '全国法院被执行人或被纳入失信人查询',
  `referee_network_info` varchar(500) DEFAULT NULL COMMENT '裁判文书网',
  `zhongdeng_info` varchar(500) DEFAULT NULL COMMENT '中登网登记及抵押登记',
  `credit_report` varchar(500) DEFAULT NULL COMMENT '信用报告',
  `other` varchar(500) DEFAULT NULL COMMENT '其他',
  `create_by` bigint(20) DEFAULT NULL COMMENT '创建人、发起人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` bigint(20) DEFAULT NULL COMMENT '最后更新人id',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `version` varchar(40) NOT NULL COMMENT '版本号',
  `origin_id` bigint(20) NOT NULL COMMENT '临时数据表id 需要用来比对数据 或者 流程拒绝时全量回写',
  `data_create_time` datetime DEFAULT NULL,
  `data_create_by` bigint(20) DEFAULT NULL,
  `data_update_time` datetime DEFAULT NULL,
  `data_update_by` bigint(20) DEFAULT NULL,
  `version_type` tinyint(4) DEFAULT '1' COMMENT '版本标志，0无效，1有效...业务自扩展',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='租后检查外部查询承租人/担保人信息版本表';

CREATE TABLE `contract_settle_plan_lib` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键id',
  `contract_id` bigint(20) unsigned NOT NULL COMMENT '合同id',
  `settle_type` varchar(20) NOT NULL COMMENT '结清类型',
  `outstanding_rent` bigint(20) unsigned NOT NULL COMMENT '到期未付租金',
  `before_maturity_principal` bigint(20) unsigned NOT NULL COMMENT '未到期本金',
  `loss` bigint(20) unsigned DEFAULT NULL COMMENT '损失金',
  `liquidated_damages` bigint(20) unsigned DEFAULT NULL COMMENT '违约金',
  `earnest_balance` bigint(20) unsigned DEFAULT NULL COMMENT '保证金余额',
  `is_earnest_deduction` tinyint(4) NOT NULL COMMENT '保证金是否内扣',
  `nominal_price` bigint(20) unsigned DEFAULT NULL COMMENT '名义货价',
  `apply_derate_amount` bigint(20) unsigned DEFAULT NULL COMMENT '申请减免金额',
  `original_deadline` date NOT NULL COMMENT '原到期日',
  `total_amount` bigint(20) unsigned DEFAULT NULL COMMENT '合计金额',
  `apply_settle_date` date DEFAULT NULL COMMENT '申请结清日期',
  `create_by` bigint(20) DEFAULT NULL COMMENT '创建人、发起人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` bigint(20) DEFAULT NULL COMMENT '最后更新人id',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `version` varchar(40) NOT NULL COMMENT '版本号',
  `origin_id` bigint(20) NOT NULL COMMENT '临时数据表id 需要用来比对数据 或者 流程拒绝时全量回写',
  `data_create_time` datetime DEFAULT NULL,
  `data_create_by` bigint(20) DEFAULT NULL,
  `data_update_time` datetime DEFAULT NULL,
  `data_update_by` bigint(20) DEFAULT NULL,
  `version_type` tinyint(4) DEFAULT '1' COMMENT '版本标志，0无效，1有效...业务自扩展',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='合同明细-结清方案版本表';