-- 删除新功能授权和功能点数据
delete from bifrost_org_menu_function where function_id =(select id from bifrost_function where code='dedup');
delete from bifrost_role_menu_function where function_id =(select id from bifrost_function where code='dedup');
delete from bifrost_function where code='dedup';


INSERT INTO bifrost_function (gmt_create, gmt_modified, code, name, sort_no, menu_id, create_by, update_by, en_name, `method`, `path`, `type`, group_id) VALUES
    ('2025-01-01 01:01:01', '2025-01-01 01:01:01', 'dedup', '租赁物内部查重', 0, (select id from bifrost_menu bm where code='leaseMaintain'), NULL, NULL, NULL, 'POST', '/ledger/detail/leaseitem/dedup', 1, NULL);

INSERT INTO bifrost_org_menu_function (gmt_create, gmt_modified, org_id, menu_id, function_id, create_by, update_by, custom_tree_id) VALUES('2025-01-01 01:01:01', '2025-01-01 01:01:01', (select id from bifrost_org where code='ZSZL'), (select id from bifrost_menu bm where code='leaseMaintain'), (select id from bifrost_function bf where code='dedup'), NULL, NULL, 141);
INSERT INTO bifrost_org_menu_function (gmt_create, gmt_modified, org_id, menu_id, function_id, create_by, update_by, custom_tree_id) VALUES('2025-01-01 01:01:01', '2025-01-01 01:01:01', (select id from bifrost_org where code='JXHJGYWB'), (select id from bifrost_menu bm where code='leaseMaintain'), (select id from bifrost_function bf where code='dedup'), NULL, NULL, 141);
INSERT INTO bifrost_org_menu_function (gmt_create, gmt_modified, org_id, menu_id, function_id, create_by, update_by, custom_tree_id) VALUES('2025-01-01 01:01:01', '2025-01-01 01:01:01', (select id from bifrost_org where code='ADMIN'), (select id from bifrost_menu bm where code='leaseMaintain'), (select id from bifrost_function bf where code='dedup'), NULL, NULL, 141);
INSERT INTO bifrost_org_menu_function (gmt_create, gmt_modified, org_id, menu_id, function_id, create_by, update_by, custom_tree_id) VALUES('2025-01-01 01:01:01', '2025-01-01 01:01:01', (select id from bifrost_org where code='YYGLB'), (select id from bifrost_menu bm where code='leaseMaintain'), (select id from bifrost_function bf where code='dedup'), NULL, NULL, 141);
INSERT INTO bifrost_org_menu_function (gmt_create, gmt_modified, org_id, menu_id, function_id, create_by, update_by, custom_tree_id) VALUES('2025-01-01 01:01:01', '2025-01-01 01:01:01', (select id from bifrost_org where code='SYCYWB'), (select id from bifrost_menu bm where code='leaseMaintain'), (select id from bifrost_function bf where code='dedup'), NULL, NULL, 141);
INSERT INTO bifrost_org_menu_function (gmt_create, gmt_modified, org_id, menu_id, function_id, create_by, update_by, custom_tree_id) VALUES('2025-01-01 01:01:01', '2025-01-01 01:01:01', (select id from bifrost_org where code='XXKJB'), (select id from bifrost_menu bm where code='leaseMaintain'), (select id from bifrost_function bf where code='dedup'), NULL, NULL, 141);

INSERT INTO bifrost_role_menu_function (gmt_create, gmt_modified, role_id, menu_id, function_id, create_by, update_by, custom_tree_id) VALUES('2025-01-01 01:01:01', '2025-01-01 01:01:01', (select id from bifrost_role where code='ADMIN_SUPERADMIN'), (select id from bifrost_menu bm where code='leaseMaintain'), (select id from bifrost_function bf where code='dedup'), NULL, NULL, 141);
INSERT INTO bifrost_role_menu_function (gmt_create, gmt_modified, role_id, menu_id, function_id, create_by, update_by, custom_tree_id) VALUES('2025-01-01 01:01:01', '2025-01-01 01:01:01', (select id from bifrost_role where code='XMJL'), (select id from bifrost_menu bm where code='leaseMaintain'), (select id from bifrost_function bf where code='dedup'), NULL, NULL, 141);
INSERT INTO bifrost_role_menu_function (gmt_create, gmt_modified, role_id, menu_id, function_id, create_by, update_by, custom_tree_id) VALUES('2025-01-01 01:01:01', '2025-01-01 01:01:01', (select id from bifrost_role where code='GLY'),  (select id from bifrost_menu bm where code='leaseMaintain'), (select id from bifrost_function bf where code='dedup'), NULL, NULL, 141);
INSERT INTO bifrost_role_menu_function (gmt_create, gmt_modified, role_id, menu_id, function_id, create_by, update_by, custom_tree_id) VALUES('2025-01-01 01:01:01', '2025-01-01 01:01:01', (select id from bifrost_role where code='YYGLB-TYCK'), (select id from bifrost_menu bm where code='leaseMaintain'), (select id from bifrost_function bf where code='dedup'), NULL, NULL, 141);
INSERT INTO bifrost_role_menu_function (gmt_create, gmt_modified, role_id, menu_id, function_id, create_by, update_by, custom_tree_id) VALUES('2025-01-01 01:01:01', '2025-01-01 01:01:01', (select id from bifrost_role where code='ZLWSHGL'), (select id from bifrost_menu bm where code='leaseMaintain'), (select id from bifrost_function bf where code='dedup'), NULL, NULL, 141);
