delete from file_authentication_config where file_type = '归档-归档资料模板';
INSERT INTO file_authentication_config (file_name, file_type, owner_type, owner_post, owner_id, create_by, update_by, create_time, update_time) VALUES(NULL, '归档-归档资料模板', 1, 'admin', NULL, 125, 125, '2025-10-14 09:17:43', '2025-10-14 09:17:43');

delete from filing_materials_config;
INSERT INTO filing_materials_config (filing_type, business_type, enable_flag, remark, create_time, create_by, update_time, update_by) VALUES('BUSINESS_MATERIALS', 'FILING_BUSINESS_LESSEE_CLIENT', 1, '基本信息-运营终审-承租人', '2025-12-08 16:02:36', NULL, '2025-12-11 08:33:27', NULL);
INSERT INTO filing_materials_config (filing_type, business_type, enable_flag, remark, create_time, create_by, update_time, update_by) VALUES('BUSINESS_MATERIALS', 'FILING_BUSINESS_ENT_CLIENT', 1, '基本信息-运营终审-法人保证人', '2025-12-08 16:02:36', NULL, '2025-12-11 08:33:27', NULL);
INSERT INTO filing_materials_config (filing_type, business_type, enable_flag, remark, create_time, create_by, update_time, update_by) VALUES('BUSINESS_MATERIALS', 'FILING_BUSINESS_IND_CLIENT', 1, '基本信息-运营终审-自然保证人', '2025-12-08 16:02:36', NULL, '2025-12-11 08:33:27', NULL);
INSERT INTO filing_materials_config (filing_type, business_type, enable_flag, remark, create_time, create_by, update_time, update_by) VALUES('BUSINESS_MATERIALS', 'FILING_BUSINESS_INNER_OPERATION', 1, '内部操作资料-运营终审', '2025-12-08 16:02:36', NULL, '2025-12-08 16:03:15', NULL);
INSERT INTO filing_materials_config (filing_type, business_type, enable_flag, remark, create_time, create_by, update_time, update_by) VALUES('BUSINESS_MATERIALS', 'FILING_BUSINESS_PAYMENT', 1, '合同信息-运营终审', '2025-12-08 16:02:36', NULL, '2025-12-08 16:03:15', NULL);
INSERT INTO filing_materials_config (filing_type, business_type, enable_flag, remark, create_time, create_by, update_time, update_by) VALUES('BUSINESS_MATERIALS', 'FILING_BUSINESS_LEASEHOLD', 1, '租赁物资料-运营资料', '2025-12-08 16:02:36', NULL, '2025-12-08 16:03:15', NULL);
INSERT INTO filing_materials_config (filing_type, business_type, enable_flag, remark, create_time, create_by, update_time, update_by) VALUES('BUSINESS_MATERIALS', 'FILING_BUSINESS_COLLATERALIZATION', 1, '抵质押资料-运营资料', '2025-12-08 16:02:36', NULL, '2025-12-08 16:03:15', NULL);


delete from filing_first_level_config ;
INSERT INTO filing_first_level_config (filing_materials_config_id, dir_code, dir_name, fixed_flag, condition_key, sort_code, enable_flag, create_time, create_by, update_time, update_by) VALUES((select id from filing_materials_config where business_type = 'FILING_BUSINESS_LESSEE_CLIENT'), 'LEASE_APPLICATION', '租赁业务申请书', 1, NULL, 1, '1', '2025-12-11 10:04:10', 3, '2025-12-11 10:04:10', 3);
INSERT INTO filing_first_level_config (filing_materials_config_id, dir_code, dir_name, fixed_flag, condition_key, sort_code, enable_flag, create_time, create_by, update_time, update_by) VALUES((select id from filing_materials_config where business_type = 'FILING_BUSINESS_LESSEE_CLIENT'), 'BUSINESS_LICENSE', '营业执照/民办非企业单位登记证书/事业单位法人证书', 1, NULL, 2, '1', '2025-12-11 10:04:10', 3, '2025-12-11 10:04:10', 3);
INSERT INTO filing_first_level_config (filing_materials_config_id, dir_code, dir_name, fixed_flag, condition_key, sort_code, enable_flag, create_time, create_by, update_time, update_by) VALUES((select id from filing_materials_config where business_type = 'FILING_BUSINESS_LESSEE_CLIENT'), 'ACCOUNT_CERTIFICATE', '开户许可证/基本存款账户', 1, NULL, 3, '1', '2025-12-11 10:04:10', 3, '2025-12-11 10:04:10', 3);
INSERT INTO filing_first_level_config (filing_materials_config_id, dir_code, dir_name, fixed_flag, condition_key, sort_code, enable_flag, create_time, create_by, update_time, update_by) VALUES((select id from filing_materials_config where business_type = 'FILING_BUSINESS_LESSEE_CLIENT'), 'AOA_AMENDMENT', '公司章程及章程修正案', 1, NULL, 4, '1', '2025-12-11 10:04:10', 3, '2025-12-11 10:04:10', 3);
INSERT INTO filing_first_level_config (filing_materials_config_id, dir_code, dir_name, fixed_flag, condition_key, sort_code, enable_flag, create_time, create_by, update_time, update_by) VALUES((select id from filing_materials_config where business_type = 'FILING_BUSINESS_LESSEE_CLIENT'), 'CAPITAL_VERIFICATION_CERTIFICATE', '注册资本验资报告或有关注册资本来源的证明材料', 1, NULL, 5, '1', '2025-12-11 10:04:10', 3, '2025-12-11 10:04:10', 3);
INSERT INTO filing_first_level_config (filing_materials_config_id, dir_code, dir_name, fixed_flag, condition_key, sort_code, enable_flag, create_time, create_by, update_time, update_by) VALUES((select id from filing_materials_config where business_type = 'FILING_BUSINESS_LESSEE_CLIENT'), 'QUALIFICATION_CERTIFICATE', '特许经营许可证或资质证明', 1, NULL, 6, '1', '2025-12-11 10:04:10', 3, '2025-12-11 10:04:10', 3);
INSERT INTO filing_first_level_config (filing_materials_config_id, dir_code, dir_name, fixed_flag, condition_key, sort_code, enable_flag, create_time, create_by, update_time, update_by) VALUES((select id from filing_materials_config where business_type = 'FILING_BUSINESS_LESSEE_CLIENT'), 'LEGAL_REPRESENTATIVE_ID_CARD', '法人代表/实际控制人身份证', 1, NULL, 7, '1', '2025-12-11 10:04:10', 3, '2025-12-11 10:04:10', 3);
INSERT INTO filing_first_level_config (filing_materials_config_id, dir_code, dir_name, fixed_flag, condition_key, sort_code, enable_flag, create_time, create_by, update_time, update_by) VALUES((select id from filing_materials_config where business_type = 'FILING_BUSINESS_LESSEE_CLIENT'), 'LEGAL_REPRESENTATIVE_CERTIFICATION', '法定代表人身份证明书', 1, NULL, 8, '1', '2025-12-11 10:04:10', 3, '2025-12-11 10:04:10', 3);
INSERT INTO filing_first_level_config (filing_materials_config_id, dir_code, dir_name, fixed_flag, condition_key, sort_code, enable_flag, create_time, create_by, update_time, update_by) VALUES((select id from filing_materials_config where business_type = 'FILING_BUSINESS_LESSEE_CLIENT'), 'LEGAL_REPRESENTATIVE_CREDIT_REPORT', '法人代表/实际控制个人信用报告', 1, NULL, 9, '1', '2025-12-11 10:04:10', 3, '2025-12-11 10:04:10', 3);
INSERT INTO filing_first_level_config (filing_materials_config_id, dir_code, dir_name, fixed_flag, condition_key, sort_code, enable_flag, create_time, create_by, update_time, update_by) VALUES((select id from filing_materials_config where business_type = 'FILING_BUSINESS_LESSEE_CLIENT'), 'ENTERPRISE_CREDIT_REPORT', '企业信用报告', 1, NULL, 10, '1', '2025-12-11 10:04:10', 3, '2025-12-11 10:04:10', 3);
INSERT INTO filing_first_level_config (filing_materials_config_id, dir_code, dir_name, fixed_flag, condition_key, sort_code, enable_flag, create_time, create_by, update_time, update_by) VALUES((select id from filing_materials_config where business_type = 'FILING_BUSINESS_LESSEE_CLIENT'), 'FINANCIAL_STATEMENTS_01', '近三年财务报表或近三年审计报告（含附注说明）复印件及最近一期的资产负债表及利润表', 1, NULL, 11, '1', '2025-12-11 10:04:10', 3, '2025-12-11 10:04:10', 3);
INSERT INTO filing_first_level_config (filing_materials_config_id, dir_code, dir_name, fixed_flag, condition_key, sort_code, enable_flag, create_time, create_by, update_time, update_by) VALUES((select id from filing_materials_config where business_type = 'FILING_BUSINESS_LESSEE_CLIENT'), 'FINANCIAL_STATEMENTS_02', '成立不足三年的，提供自成立至授信申请日的年度财务报表或审计报告（含附注说明）和最近一期的资产负债表及利润表', 1, NULL, 12, '1', '2025-12-11 10:04:10', 3, '2025-12-11 10:04:10', 3);
INSERT INTO filing_first_level_config (filing_materials_config_id, dir_code, dir_name, fixed_flag, condition_key, sort_code, enable_flag, create_time, create_by, update_time, update_by) VALUES((select id from filing_materials_config where business_type = 'FILING_BUSINESS_LESSEE_CLIENT'), 'TRIAL_BALANCE', '最近一个会计年度及最近一期财务报表科目余额表', 1, NULL, 13, '1', '2025-12-11 10:04:10', 3, '2025-12-11 10:04:10', 3);
INSERT INTO filing_first_level_config (filing_materials_config_id, dir_code, dir_name, fixed_flag, condition_key, sort_code, enable_flag, create_time, create_by, update_time, update_by) VALUES((select id from filing_materials_config where business_type = 'FILING_BUSINESS_LESSEE_CLIENT'), 'VAT_RETURN_01', '近三年一期增值税纳税申报表', 1, NULL, 14, '1', '2025-12-11 10:04:10', 3, '2025-12-11 10:04:10', 3);
INSERT INTO filing_first_level_config (filing_materials_config_id, dir_code, dir_name, fixed_flag, condition_key, sort_code, enable_flag, create_time, create_by, update_time, update_by) VALUES((select id from filing_materials_config where business_type = 'FILING_BUSINESS_LESSEE_CLIENT'), 'VAT_RETURN_02', '成立不足三年的，提供自成立至授信申请日的增值税纳税申报表', 1, NULL, 15, '1', '2025-12-11 10:04:10', 3, '2025-12-11 10:04:10', 3);
INSERT INTO filing_first_level_config (filing_materials_config_id, dir_code, dir_name, fixed_flag, condition_key, sort_code, enable_flag, create_time, create_by, update_time, update_by) VALUES((select id from filing_materials_config where business_type = 'FILING_BUSINESS_LESSEE_CLIENT'), 'BANK_STATEMENT', '不少于近6个月主要结算账户银行流水或银行对账单', 1, NULL, 16, '1', '2025-12-11 10:04:10', 3, '2025-12-11 10:04:10', 3);
INSERT INTO filing_first_level_config (filing_materials_config_id, dir_code, dir_name, fixed_flag, condition_key, sort_code, enable_flag, create_time, create_by, update_time, update_by) VALUES((select id from filing_materials_config where business_type = 'FILING_BUSINESS_LESSEE_CLIENT'), 'ENERGY_CONSUMPTION_CERTIFICATE', '耗能凭证（不少于近6个月，如电费、水费、蒸汽费等）', 1, NULL, 17, '1', '2025-12-11 10:04:10', 3, '2025-12-11 10:04:10', 3);
INSERT INTO filing_first_level_config (filing_materials_config_id, dir_code, dir_name, fixed_flag, condition_key, sort_code, enable_flag, create_time, create_by, update_time, update_by) VALUES((select id from filing_materials_config where business_type = 'FILING_BUSINESS_LESSEE_CLIENT'), 'FINANCING_DETAILS', '融资明细', 1, NULL, 18, '1', '2025-12-11 10:04:10', 3, '2025-12-11 10:04:10', 3);
INSERT INTO filing_first_level_config (filing_materials_config_id, dir_code, dir_name, fixed_flag, condition_key, sort_code, enable_flag, create_time, create_by, update_time, update_by) VALUES((select id from filing_materials_config where business_type = 'FILING_BUSINESS_LESSEE_CLIENT'), 'GUARANTEE_DETAILS', '担保明细', 1, NULL, 19, '1', '2025-12-11 10:04:10', 3, '2025-12-11 10:04:10', 3);
INSERT INTO filing_first_level_config (filing_materials_config_id, dir_code, dir_name, fixed_flag, condition_key, sort_code, enable_flag, create_time, create_by, update_time, update_by) VALUES((select id from filing_materials_config where business_type = 'FILING_BUSINESS_LESSEE_CLIENT'), 'NON-HIDDEN_DEBTS', '非隐债说明', 1, NULL, 20, '1', '2025-12-11 10:04:10', 3, '2025-12-11 10:04:10', 3);
INSERT INTO filing_first_level_config (filing_materials_config_id, dir_code, dir_name, fixed_flag, condition_key, sort_code, enable_flag, create_time, create_by, update_time, update_by) VALUES((select id from filing_materials_config where business_type = 'FILING_BUSINESS_LESSEE_CLIENT'), 'ON-SITE_DUE_DILIGENCE_IMG', '现场尽调照片', 1, NULL, 21, '1', '2025-12-11 10:04:10', 3, '2025-12-11 10:04:10', 3);
INSERT INTO filing_first_level_config (filing_materials_config_id, dir_code, dir_name, fixed_flag, condition_key, sort_code, enable_flag, create_time, create_by, update_time, update_by) VALUES((select id from filing_materials_config where business_type = 'FILING_BUSINESS_LESSEE_CLIENT'), 'OTHER', '其他资料', 1, NULL, 22, '1', '2025-12-11 10:04:10', 3, '2025-12-11 10:04:10', 3);
INSERT INTO filing_first_level_config (filing_materials_config_id, dir_code, dir_name, fixed_flag, condition_key, sort_code, enable_flag, create_time, create_by, update_time, update_by) VALUES((select id from filing_materials_config where business_type = 'FILING_BUSINESS_ENT_CLIENT'), 'BUSINESS_LICENSE', '营业执照', 1, NULL, 1, '1', '2025-12-11 10:04:10', 3, '2025-12-11 10:04:10', 3);
INSERT INTO filing_first_level_config (filing_materials_config_id, dir_code, dir_name, fixed_flag, condition_key, sort_code, enable_flag, create_time, create_by, update_time, update_by) VALUES((select id from filing_materials_config where business_type = 'FILING_BUSINESS_ENT_CLIENT'), 'ACCOUNT_CERTIFICATE', '开户许可证/基本存款账户', 1, NULL, 2, '1', '2025-12-11 10:04:10', 3, '2025-12-11 10:04:10', 3);
INSERT INTO filing_first_level_config (filing_materials_config_id, dir_code, dir_name, fixed_flag, condition_key, sort_code, enable_flag, create_time, create_by, update_time, update_by) VALUES((select id from filing_materials_config where business_type = 'FILING_BUSINESS_ENT_CLIENT'), 'AOA_AMENDMENT', '公司章程及章程修正案', 1, NULL, 3, '1', '2025-12-11 10:04:10', 3, '2025-12-11 10:04:10', 3);
INSERT INTO filing_first_level_config (filing_materials_config_id, dir_code, dir_name, fixed_flag, condition_key, sort_code, enable_flag, create_time, create_by, update_time, update_by) VALUES((select id from filing_materials_config where business_type = 'FILING_BUSINESS_ENT_CLIENT'), 'CAPITAL_VERIFICATION_CERTIFICATE', '注册资本验资报告或有关注册资本来源的证明材料', 1, NULL, 4, '1', '2025-12-11 10:04:10', 3, '2025-12-11 10:04:10', 3);
INSERT INTO filing_first_level_config (filing_materials_config_id, dir_code, dir_name, fixed_flag, condition_key, sort_code, enable_flag, create_time, create_by, update_time, update_by) VALUES((select id from filing_materials_config where business_type = 'FILING_BUSINESS_ENT_CLIENT'), 'QUALIFICATION_CERTIFICATE', '特许经营许可证或资质证明', 1, NULL, 5, '1', '2025-12-11 10:04:10', 3, '2025-12-11 10:04:10', 3);
INSERT INTO filing_first_level_config (filing_materials_config_id, dir_code, dir_name, fixed_flag, condition_key, sort_code, enable_flag, create_time, create_by, update_time, update_by) VALUES((select id from filing_materials_config where business_type = 'FILING_BUSINESS_ENT_CLIENT'), 'LEGAL_REPRESENTATIVE_ID_CARD', '法人代表/实际控制人身份证', 1, NULL, 6, '1', '2025-12-11 10:04:10', 3, '2025-12-11 10:04:10', 3);
INSERT INTO filing_first_level_config (filing_materials_config_id, dir_code, dir_name, fixed_flag, condition_key, sort_code, enable_flag, create_time, create_by, update_time, update_by) VALUES((select id from filing_materials_config where business_type = 'FILING_BUSINESS_ENT_CLIENT'), 'LEGAL_REPRESENTATIVE_CERTIFICATION', '法定代表人身份证明书', 1, NULL, 7, '1', '2025-12-11 10:04:10', 3, '2025-12-11 10:04:10', 3);
INSERT INTO filing_first_level_config (filing_materials_config_id, dir_code, dir_name, fixed_flag, condition_key, sort_code, enable_flag, create_time, create_by, update_time, update_by) VALUES((select id from filing_materials_config where business_type = 'FILING_BUSINESS_ENT_CLIENT'), 'ENTERPRISE_CREDIT_REPORT', '企业信用报告', 1, NULL, 8, '1', '2025-12-11 10:04:10', 3, '2025-12-11 10:04:10', 3);
INSERT INTO filing_first_level_config (filing_materials_config_id, dir_code, dir_name, fixed_flag, condition_key, sort_code, enable_flag, create_time, create_by, update_time, update_by) VALUES((select id from filing_materials_config where business_type = 'FILING_BUSINESS_ENT_CLIENT'), 'FINANCIAL_STATEMENTS_01', '近三年财务报表或近三年审计报告（含附注说明）复印件及最近一期的资产负债表及利润表', 1, NULL, 9, '1', '2025-12-11 10:04:10', 3, '2025-12-11 10:04:10', 3);
INSERT INTO filing_first_level_config (filing_materials_config_id, dir_code, dir_name, fixed_flag, condition_key, sort_code, enable_flag, create_time, create_by, update_time, update_by) VALUES((select id from filing_materials_config where business_type = 'FILING_BUSINESS_ENT_CLIENT'), 'FINANCIAL_STATEMENTS_02', '成立不足三年的，提供自成立至授信申请日的年度财务报表或审计报告（含附注说明）和最近一期的资产负债表及利润表', 1, NULL, 10, '1', '2025-12-11 10:04:10', 3, '2025-12-11 10:04:10', 3);
INSERT INTO filing_first_level_config (filing_materials_config_id, dir_code, dir_name, fixed_flag, condition_key, sort_code, enable_flag, create_time, create_by, update_time, update_by) VALUES((select id from filing_materials_config where business_type = 'FILING_BUSINESS_ENT_CLIENT'), 'TRIAL_BALANCE', '最近一个会计年度及最近一期财务报表科目余额表', 1, NULL, 11, '1', '2025-12-11 10:04:10', 3, '2025-12-11 10:04:10', 3);
INSERT INTO filing_first_level_config (filing_materials_config_id, dir_code, dir_name, fixed_flag, condition_key, sort_code, enable_flag, create_time, create_by, update_time, update_by) VALUES((select id from filing_materials_config where business_type = 'FILING_BUSINESS_ENT_CLIENT'), 'VAT_RETURN_01', '近三年一期增值税纳税申报表', 1, NULL, 12, '1', '2025-12-11 10:04:10', 3, '2025-12-11 10:04:10', 3);
INSERT INTO filing_first_level_config (filing_materials_config_id, dir_code, dir_name, fixed_flag, condition_key, sort_code, enable_flag, create_time, create_by, update_time, update_by) VALUES((select id from filing_materials_config where business_type = 'FILING_BUSINESS_ENT_CLIENT'), 'VAT_RETURN_02', '成立不足三年的，提供自成立至授信申请日的增值税纳税申报表', 1, NULL, 13, '1', '2025-12-11 10:04:10', 3, '2025-12-11 10:04:10', 3);
INSERT INTO filing_first_level_config (filing_materials_config_id, dir_code, dir_name, fixed_flag, condition_key, sort_code, enable_flag, create_time, create_by, update_time, update_by) VALUES((select id from filing_materials_config where business_type = 'FILING_BUSINESS_ENT_CLIENT'), 'FINANCING_DETAILS', '融资明细', 1, NULL, 14, '1', '2025-12-11 10:04:10', 3, '2025-12-11 10:04:10', 3);
INSERT INTO filing_first_level_config (filing_materials_config_id, dir_code, dir_name, fixed_flag, condition_key, sort_code, enable_flag, create_time, create_by, update_time, update_by) VALUES((select id from filing_materials_config where business_type = 'FILING_BUSINESS_ENT_CLIENT'), 'GUARANTEE_DETAILS', '担保明细', 1, NULL, 15, '1', '2025-12-11 10:04:10', 3, '2025-12-11 10:04:10', 3);
INSERT INTO filing_first_level_config (filing_materials_config_id, dir_code, dir_name, fixed_flag, condition_key, sort_code, enable_flag, create_time, create_by, update_time, update_by) VALUES((select id from filing_materials_config where business_type = 'FILING_BUSINESS_ENT_CLIENT'), 'ON-SITE_DUE_DILIGENCE_IMG', '现场尽调照片', 1, NULL, 16, '1', '2025-12-11 10:04:10', 3, '2025-12-11 10:04:10', 3);
INSERT INTO filing_first_level_config (filing_materials_config_id, dir_code, dir_name, fixed_flag, condition_key, sort_code, enable_flag, create_time, create_by, update_time, update_by) VALUES((select id from filing_materials_config where business_type = 'FILING_BUSINESS_ENT_CLIENT'), 'OTHER', '其他资料', 1, NULL, 17, '1', '2025-12-11 10:04:10', 3, '2025-12-11 10:04:10', 3);
INSERT INTO filing_first_level_config (filing_materials_config_id, dir_code, dir_name, fixed_flag, condition_key, sort_code, enable_flag, create_time, create_by, update_time, update_by) VALUES((select id from filing_materials_config where business_type = 'FILING_BUSINESS_IND_CLIENT'), 'GUARANTOR_CERT', '保证人身份证', 1, NULL, 1, '1', '2025-12-11 10:04:10', 3, '2025-12-11 10:04:10', 3);
INSERT INTO filing_first_level_config (filing_materials_config_id, dir_code, dir_name, fixed_flag, condition_key, sort_code, enable_flag, create_time, create_by, update_time, update_by) VALUES((select id from filing_materials_config where business_type = 'FILING_BUSINESS_IND_CLIENT'), 'MARRIAGE_CERTIFICATE', '结婚证', 1, NULL, 2, '1', '2025-12-11 10:04:10', 3, '2025-12-11 10:04:10', 3);
INSERT INTO filing_first_level_config (filing_materials_config_id, dir_code, dir_name, fixed_flag, condition_key, sort_code, enable_flag, create_time, create_by, update_time, update_by) VALUES((select id from filing_materials_config where business_type = 'FILING_BUSINESS_IND_CLIENT'), 'CERTIFICATE_OF_ASSET_OWNERSHIP', '保证人个人名下资产清单及资产权属证明', 1, NULL, 3, '1', '2025-12-11 10:04:10', 3, '2025-12-11 10:04:10', 3);
INSERT INTO filing_first_level_config (filing_materials_config_id, dir_code, dir_name, fixed_flag, condition_key, sort_code, enable_flag, create_time, create_by, update_time, update_by) VALUES((select id from filing_materials_config where business_type = 'FILING_BUSINESS_IND_CLIENT'), 'PERSON_CREDIT_REPORT', '保证人个人信用报告', 1, NULL, 4, '1', '2025-12-11 10:04:10', 3, '2025-12-11 10:04:10', 3);
INSERT INTO filing_first_level_config (filing_materials_config_id, dir_code, dir_name, fixed_flag, condition_key, sort_code, enable_flag, create_time, create_by, update_time, update_by) VALUES((select id from filing_materials_config where business_type = 'FILING_BUSINESS_IND_CLIENT'), 'OTHER', '其他资料', 1, NULL, 5, '1', '2025-12-11 10:04:10', 3, '2025-12-11 10:04:10', 3);
INSERT INTO filing_first_level_config (filing_materials_config_id, dir_code, dir_name, fixed_flag, condition_key, sort_code, enable_flag, create_time, create_by, update_time, update_by) VALUES((select id from filing_materials_config where business_type = 'FILING_BUSINESS_INNER_OPERATION'), 'ESTABLISH_APPLY_REPORT', '立项申请报告', 1, NULL, 1, '1', '2025-12-11 10:04:10', 3, '2025-12-11 10:04:10', 3);
INSERT INTO filing_first_level_config (filing_materials_config_id, dir_code, dir_name, fixed_flag, condition_key, sort_code, enable_flag, create_time, create_by, update_time, update_by) VALUES((select id from filing_materials_config where business_type = 'FILING_BUSINESS_INNER_OPERATION'), 'GROUP_ESTABLISH_APPROVE', '立项审批流程', 0, 'APPROVAL_CREDIT', 2, '1', '2025-12-11 10:04:10', 3, '2025-12-11 10:04:10', 3);
INSERT INTO filing_first_level_config (filing_materials_config_id, dir_code, dir_name, fixed_flag, condition_key, sort_code, enable_flag, create_time, create_by, update_time, update_by) VALUES((select id from filing_materials_config where business_type = 'FILING_BUSINESS_INNER_OPERATION'), 'GROUP_ESTABLISH_CHANGE', '立项变更审批流程', 0, 'APPROVAL_CHANGE_CREDIT', 3, '1', '2025-12-11 10:04:10', 3, '2025-12-11 10:04:10', 3);
INSERT INTO filing_first_level_config (filing_materials_config_id, dir_code, dir_name, fixed_flag, condition_key, sort_code, enable_flag, create_time, create_by, update_time, update_by) VALUES((select id from filing_materials_config where business_type = 'FILING_BUSINESS_INNER_OPERATION'), 'ESTABLISH_APPROVE', '立项审批流程', 0, 'APPROVAL_PROJECT', 2, '1', '2025-12-11 10:04:10', 3, '2025-12-11 10:04:10', 3);
INSERT INTO filing_first_level_config (filing_materials_config_id, dir_code, dir_name, fixed_flag, condition_key, sort_code, enable_flag, create_time, create_by, update_time, update_by) VALUES((select id from filing_materials_config where business_type = 'FILING_BUSINESS_INNER_OPERATION'), 'ESTABLISH_CHANGE', '立项变更审批流程', 0, 'APPROVAL_CHANGE_PROJECT', 3, '1', '2025-12-11 10:04:10', 3, '2025-12-11 10:04:10', 3);
INSERT INTO filing_first_level_config (filing_materials_config_id, dir_code, dir_name, fixed_flag, condition_key, sort_code, enable_flag, create_time, create_by, update_time, update_by) VALUES((select id from filing_materials_config where business_type = 'FILING_BUSINESS_INNER_OPERATION'), 'PROJECT_PRICING_REPORT', '项目定价审批表', 1, NULL, 4, '1', '2025-12-11 10:04:10', 3, '2025-12-11 10:04:10', 3);
INSERT INTO filing_first_level_config (filing_materials_config_id, dir_code, dir_name, fixed_flag, condition_key, sort_code, enable_flag, create_time, create_by, update_time, update_by) VALUES((select id from filing_materials_config where business_type = 'FILING_BUSINESS_INNER_OPERATION'), 'PROJECT_PRICING_APPROVE', '项目定价审批流程', 0, 'APPROVAL_PROJECT_PRICING', 5, '1', '2025-12-11 10:04:10', 3, '2025-12-11 10:04:10', 3);
INSERT INTO filing_first_level_config (filing_materials_config_id, dir_code, dir_name, fixed_flag, condition_key, sort_code, enable_flag, create_time, create_by, update_time, update_by) VALUES((select id from filing_materials_config where business_type = 'FILING_BUSINESS_INNER_OPERATION'), 'PROJECT_PRICING_CHANGE', '项目定价变更审批流程', 0, 'APPROVAL_CHANGE_PROJECT_PRICING', 6, '1', '2025-12-11 10:04:10', 3, '2025-12-11 10:04:10', 3);
INSERT INTO filing_first_level_config (filing_materials_config_id, dir_code, dir_name, fixed_flag, condition_key, sort_code, enable_flag, create_time, create_by, update_time, update_by) VALUES((select id from filing_materials_config where business_type = 'FILING_BUSINESS_INNER_OPERATION'), 'PROJECT_DUE_DILIGENCE_REPORT', '项目尽调报告', 1, NULL, 7, '1', '2025-12-11 10:04:10', 3, '2025-12-11 10:04:10', 3);
INSERT INTO filing_first_level_config (filing_materials_config_id, dir_code, dir_name, fixed_flag, condition_key, sort_code, enable_flag, create_time, create_by, update_time, update_by) VALUES((select id from filing_materials_config where business_type = 'FILING_BUSINESS_INNER_OPERATION'), 'PROJECT_REVIEW_REPORT', '项目审查报告', 1, NULL, 8, '1', '2025-12-11 10:04:10', 3, '2025-12-11 10:04:10', 3);
INSERT INTO filing_first_level_config (filing_materials_config_id, dir_code, dir_name, fixed_flag, condition_key, sort_code, enable_flag, create_time, create_by, update_time, update_by) VALUES((select id from filing_materials_config where business_type = 'FILING_BUSINESS_INNER_OPERATION'), 'COMPLIANCE_REVIEW_REPORT', '法律合规审查意见', 1, NULL, 9, '1', '2025-12-11 10:04:10', 3, '2025-12-11 10:04:10', 3);
INSERT INTO filing_first_level_config (filing_materials_config_id, dir_code, dir_name, fixed_flag, condition_key, sort_code, enable_flag, create_time, create_by, update_time, update_by) VALUES((select id from filing_materials_config where business_type = 'FILING_BUSINESS_INNER_OPERATION'), 'LEGAL_OPINION', '律师事务所法律意见书', 1, NULL, 10, '1', '2025-12-11 10:04:10', 3, '2025-12-11 10:04:10', 3);
INSERT INTO filing_first_level_config (filing_materials_config_id, dir_code, dir_name, fixed_flag, condition_key, sort_code, enable_flag, create_time, create_by, update_time, update_by) VALUES((select id from filing_materials_config where business_type = 'FILING_BUSINESS_INNER_OPERATION'), 'PROJECT_REVIEW_APPROVE', '项目评审流程', 0, 'APPROVAL_PROJECT_REVIEW', 11, '1', '2025-12-11 10:04:10', 3, '2025-12-11 10:04:10', 3);
INSERT INTO filing_first_level_config (filing_materials_config_id, dir_code, dir_name, fixed_flag, condition_key, sort_code, enable_flag, create_time, create_by, update_time, update_by) VALUES((select id from filing_materials_config where business_type = 'FILING_BUSINESS_INNER_OPERATION'), 'PROJECT_REVIEW_CHANGE', '项目评审变更流程', 0, 'APPROVAL_CHANGE_PROJECT_REVIEW', 12, '1', '2025-12-11 10:04:10', 3, '2025-12-11 10:04:10', 3);
INSERT INTO filing_first_level_config (filing_materials_config_id, dir_code, dir_name, fixed_flag, condition_key, sort_code, enable_flag, create_time, create_by, update_time, update_by) VALUES((select id from filing_materials_config where business_type = 'FILING_BUSINESS_INNER_OPERATION'), 'PROJECT_REVIEW_MEETING', '项目评审会记录', 1, NULL, 13, '1', '2025-12-11 10:04:10', 3, '2025-12-11 10:04:10', 3);
INSERT INTO filing_first_level_config (filing_materials_config_id, dir_code, dir_name, fixed_flag, condition_key, sort_code, enable_flag, create_time, create_by, update_time, update_by) VALUES((select id from filing_materials_config where business_type = 'FILING_BUSINESS_INNER_OPERATION'), 'PROJECT_REVIEW_MEETING_MINUTES', '项目评审会纪要', 1, NULL, 14, '1', '2025-12-11 10:04:10', 3, '2025-12-11 10:04:10', 3);
INSERT INTO filing_first_level_config (filing_materials_config_id, dir_code, dir_name, fixed_flag, condition_key, sort_code, enable_flag, create_time, create_by, update_time, update_by) VALUES((select id from filing_materials_config where business_type = 'FILING_BUSINESS_INNER_OPERATION'), 'PROJECT_REVIEW_OPINION_FORM', '项目评审意见单', 1, NULL, 15, '1', '2025-12-11 10:04:10', 3, '2025-12-11 10:04:10', 3);
INSERT INTO filing_first_level_config (filing_materials_config_id, dir_code, dir_name, fixed_flag, condition_key, sort_code, enable_flag, create_time, create_by, update_time, update_by) VALUES((select id from filing_materials_config where business_type = 'FILING_BUSINESS_INNER_OPERATION'), 'PROJECT_REVIEW_VOTING_FORM', '项目评审审议表决表', 1, NULL, 16, '1', '2025-12-11 10:04:10', 3, '2025-12-11 10:04:10', 3);
INSERT INTO filing_first_level_config (filing_materials_config_id, dir_code, dir_name, fixed_flag, condition_key, sort_code, enable_flag, create_time, create_by, update_time, update_by) VALUES((select id from filing_materials_config where business_type = 'FILING_BUSINESS_INNER_OPERATION'), 'MANAGER_APPROVAL_OPINION', '总经理核准意见', 1, NULL, 17, '1', '2025-12-11 10:04:10', 3, '2025-12-11 10:04:10', 3);
INSERT INTO filing_first_level_config (filing_materials_config_id, dir_code, dir_name, fixed_flag, condition_key, sort_code, enable_flag, create_time, create_by, update_time, update_by) VALUES((select id from filing_materials_config where business_type = 'FILING_BUSINESS_INNER_OPERATION'), 'BOARD_RESOLUTION', '董事会决议及流程', 1, NULL, 18, '1', '2025-12-11 10:04:10', 3, '2025-12-11 10:04:10', 3);
INSERT INTO filing_first_level_config (filing_materials_config_id, dir_code, dir_name, fixed_flag, condition_key, sort_code, enable_flag, create_time, create_by, update_time, update_by) VALUES((select id from filing_materials_config where business_type = 'FILING_BUSINESS_INNER_OPERATION'), 'LEASED_ASSET_APPROVAL_PROCESS', '租赁物审批流程', 0, 'APPROVAL_LEASEHOLD', 19, '1', '2025-12-11 10:04:10', 3, '2025-12-11 10:04:10', 3);
INSERT INTO filing_first_level_config (filing_materials_config_id, dir_code, dir_name, fixed_flag, condition_key, sort_code, enable_flag, create_time, create_by, update_time, update_by) VALUES((select id from filing_materials_config where business_type = 'FILING_BUSINESS_INNER_OPERATION'), 'LEASED_ASSET_CHANGE_APPROVAL_PROCESS', '租赁物变更审批流程', 0, 'APPROVAL_LEASEHOLD_REVIEW', 20, '1', '2025-12-11 10:04:10', 3, '2025-12-11 10:04:10', 3);
INSERT INTO filing_first_level_config (filing_materials_config_id, dir_code, dir_name, fixed_flag, condition_key, sort_code, enable_flag, create_time, create_by, update_time, update_by) VALUES((select id from filing_materials_config where business_type = 'FILING_BUSINESS_INNER_OPERATION'), 'LEGAL_REVIEW_OPINION', '租赁物法务审核意见书', 1, NULL, 21, '1', '2025-12-11 10:04:10', 3, '2025-12-11 10:04:10', 3);
INSERT INTO filing_first_level_config (filing_materials_config_id, dir_code, dir_name, fixed_flag, condition_key, sort_code, enable_flag, create_time, create_by, update_time, update_by) VALUES((select id from filing_materials_config where business_type = 'FILING_BUSINESS_INNER_OPERATION'), 'OPERATION_REVIEW_FORM', '租赁物运营审核表', 1, NULL, 22, '1', '2025-12-11 10:04:10', 3, '2025-12-11 10:04:10', 3);
INSERT INTO filing_first_level_config (filing_materials_config_id, dir_code, dir_name, fixed_flag, condition_key, sort_code, enable_flag, create_time, create_by, update_time, update_by) VALUES((select id from filing_materials_config where business_type = 'FILING_BUSINESS_INNER_OPERATION'), 'CONTRACT_SIGNING_APPROVAL_PROCESS', '合同签署审批流程', 0, 'APPROVAL_CONTRACT', 23, '1', '2025-12-11 10:04:10', 3, '2025-12-11 21:42:15', 3);
INSERT INTO filing_first_level_config (filing_materials_config_id, dir_code, dir_name, fixed_flag, condition_key, sort_code, enable_flag, create_time, create_by, update_time, update_by) VALUES((select id from filing_materials_config where business_type = 'FILING_BUSINESS_INNER_OPERATION'), 'PAYMENT_APPROVAL_PROCESS', '付款审批流程', 0, 'APPROVAL_PAYMENT', 24, '1', '2025-12-11 10:04:10', 3, '2025-12-11 21:42:33', 3);
INSERT INTO filing_first_level_config (filing_materials_config_id, dir_code, dir_name, fixed_flag, condition_key, sort_code, enable_flag, create_time, create_by, update_time, update_by) VALUES((select id from filing_materials_config where business_type = 'FILING_BUSINESS_INNER_OPERATION'), 'DISBURSEMENT_APPROVAL_FORM', '放款审批表', 1, '', 25, '1', '2025-12-11 10:04:10', 3, '2025-12-11 21:42:15', 3);
INSERT INTO filing_first_level_config (filing_materials_config_id, dir_code, dir_name, fixed_flag, condition_key, sort_code, enable_flag, create_time, create_by, update_time, update_by) VALUES((select id from filing_materials_config where business_type = 'FILING_BUSINESS_INNER_OPERATION'), 'DUE_DILIGENCE_COMMITMENT_LETTER', '尽职调查承诺书', 1, NULL, 26, '1', '2025-12-11 10:04:10', 3, '2025-12-11 10:04:10', 3);
INSERT INTO filing_first_level_config (filing_materials_config_id, dir_code, dir_name, fixed_flag, condition_key, sort_code, enable_flag, create_time, create_by, update_time, update_by) VALUES((select id from filing_materials_config where business_type = 'FILING_BUSINESS_INNER_OPERATION'), 'PRE_DISBURSEMENT_PUBLIC_REPORT', '放款前公开信息查询报告', 1, NULL, 27, '1', '2025-12-11 10:04:10', 3, '2025-12-11 10:04:10', 3);
INSERT INTO filing_first_level_config (filing_materials_config_id, dir_code, dir_name, fixed_flag, condition_key, sort_code, enable_flag, create_time, create_by, update_time, update_by) VALUES((select id from filing_materials_config where business_type = 'FILING_BUSINESS_INNER_OPERATION'), 'OTHER', '其他资料', 1, NULL, 28, '1', '2025-12-11 10:04:10', 3, '2025-12-11 10:04:10', 3);
INSERT INTO filing_first_level_config (filing_materials_config_id, dir_code, dir_name, fixed_flag, condition_key, sort_code, enable_flag, create_time, create_by, update_time, update_by) VALUES((select id from filing_materials_config where business_type = 'FILING_BUSINESS_PAYMENT'), 'SALES_CONTRACT', '买卖合同', 1, NULL, 1, '1', '2025-12-11 10:04:10', 3, '2025-12-11 10:04:10', 3);
INSERT INTO filing_first_level_config (filing_materials_config_id, dir_code, dir_name, fixed_flag, condition_key, sort_code, enable_flag, create_time, create_by, update_time, update_by) VALUES((select id from filing_materials_config where business_type = 'FILING_BUSINESS_PAYMENT'), 'FINANCIAL_LEASE_CONTRACT', '融资租赁合同', 1, NULL, 2, '1', '2025-12-11 10:04:10', 3, '2025-12-11 10:04:10', 3);
INSERT INTO filing_first_level_config (filing_materials_config_id, dir_code, dir_name, fixed_flag, condition_key, sort_code, enable_flag, create_time, create_by, update_time, update_by) VALUES((select id from filing_materials_config where business_type = 'FILING_BUSINESS_PAYMENT'), 'CONSULTING_CONTRACT', '租赁结构安排及管理咨询合同', 1, NULL, 3, '1', '2025-12-11 10:04:10', 3, '2025-12-11 10:04:10', 3);
INSERT INTO filing_first_level_config (filing_materials_config_id, dir_code, dir_name, fixed_flag, condition_key, sort_code, enable_flag, create_time, create_by, update_time, update_by) VALUES((select id from filing_materials_config where business_type = 'FILING_BUSINESS_PAYMENT'), 'GUARANTEE_CONTRACT', '保证合同', 1, NULL, 4, '1', '2025-12-11 10:04:10', 3, '2025-12-11 10:04:10', 3);
INSERT INTO filing_first_level_config (filing_materials_config_id, dir_code, dir_name, fixed_flag, condition_key, sort_code, enable_flag, create_time, create_by, update_time, update_by) VALUES((select id from filing_materials_config where business_type = 'FILING_BUSINESS_PAYMENT'), 'MORTGAGE_CONTRACT', '抵押合同', 1, NULL, 5, '1', '2025-12-11 10:04:10', 3, '2025-12-11 10:04:10', 3);
INSERT INTO filing_first_level_config (filing_materials_config_id, dir_code, dir_name, fixed_flag, condition_key, sort_code, enable_flag, create_time, create_by, update_time, update_by) VALUES((select id from filing_materials_config where business_type = 'FILING_BUSINESS_PAYMENT'), 'PLEDGE_CONTRACT', '质押合同', 1, NULL, 6, '1', '2025-12-11 10:04:10', 3, '2025-12-11 10:04:10', 3);
INSERT INTO filing_first_level_config (filing_materials_config_id, dir_code, dir_name, fixed_flag, condition_key, sort_code, enable_flag, create_time, create_by, update_time, update_by) VALUES((select id from filing_materials_config where business_type = 'FILING_BUSINESS_PAYMENT'), 'BOARD_MEETING_RESOLUTION', '董事会/股东（大）会决议/决定（关于同意申请融资/同意提供担保/抵质押）', 1, NULL, 7, '1', '2025-12-11 10:04:10', 3, '2025-12-11 10:04:10', 3);
INSERT INTO filing_first_level_config (filing_materials_config_id, dir_code, dir_name, fixed_flag, condition_key, sort_code, enable_flag, create_time, create_by, update_time, update_by) VALUES((select id from filing_materials_config where business_type = 'FILING_BUSINESS_PAYMENT'), 'SIGN_CONTRACT_DOCUMENTS', '授权签署合同文件', 1, NULL, 8, '1', '2025-12-11 10:04:10', 3, '2025-12-11 10:04:10', 3);
INSERT INTO filing_first_level_config (filing_materials_config_id, dir_code, dir_name, fixed_flag, condition_key, sort_code, enable_flag, create_time, create_by, update_time, update_by) VALUES((select id from filing_materials_config where business_type = 'FILING_BUSINESS_PAYMENT'), 'IN_PERSON_SIGNING_PHOTOS ', '合同面签照片（面签视频资料）', 1, NULL, 9, '1', '2025-12-11 10:04:10', 3, '2025-12-11 10:04:10', 3);
INSERT INTO filing_first_level_config (filing_materials_config_id, dir_code, dir_name, fixed_flag, condition_key, sort_code, enable_flag, create_time, create_by, update_time, update_by) VALUES((select id from filing_materials_config where business_type = 'FILING_BUSINESS_PAYMENT'), 'COMMITMENT_LETTER', '资料真实性承诺书', 1, NULL, 10, '1', '2025-12-11 10:04:10', 3, '2025-12-11 10:04:10', 3);
INSERT INTO filing_first_level_config (filing_materials_config_id, dir_code, dir_name, fixed_flag, condition_key, sort_code, enable_flag, create_time, create_by, update_time, update_by) VALUES((select id from filing_materials_config where business_type = 'FILING_BUSINESS_PAYMENT'), 'CREDIT_INQUIRY_AUTHORIZATION_LETTER', '征信查询授权书', 1, NULL, 11, '1', '2025-12-11 10:04:10', 3, '2025-12-11 10:04:10', 3);
INSERT INTO filing_first_level_config (filing_materials_config_id, dir_code, dir_name, fixed_flag, condition_key, sort_code, enable_flag, create_time, create_by, update_time, update_by) VALUES((select id from filing_materials_config where business_type = 'FILING_BUSINESS_PAYMENT'), 'INTEGRITY_INFORMATION_NOTICE', '廉洁告知书', 1, NULL, 12, '1', '2025-12-11 10:04:10', 3, '2025-12-11 10:04:10', 3);
INSERT INTO filing_first_level_config (filing_materials_config_id, dir_code, dir_name, fixed_flag, condition_key, sort_code, enable_flag, create_time, create_by, update_time, update_by) VALUES((select id from filing_materials_config where business_type = 'FILING_BUSINESS_PAYMENT'), 'CONTRACT_DOCUMENTS_RECEIPT', '合同文件签收单', 1, NULL, 13, '1', '2025-12-11 10:04:10', 3, '2025-12-11 10:04:10', 3);
INSERT INTO filing_first_level_config (filing_materials_config_id, dir_code, dir_name, fixed_flag, condition_key, sort_code, enable_flag, create_time, create_by, update_time, update_by) VALUES((select id from filing_materials_config where business_type = 'FILING_BUSINESS_PAYMENT'), 'VERIFICATION_DECLARATION', '核验声明书', 1, NULL, 14, '1', '2025-12-11 10:04:10', 3, '2025-12-11 10:04:10', 3);
INSERT INTO filing_first_level_config (filing_materials_config_id, dir_code, dir_name, fixed_flag, condition_key, sort_code, enable_flag, create_time, create_by, update_time, update_by) VALUES((select id from filing_materials_config where business_type = 'FILING_BUSINESS_PAYMENT'), 'FUND_USAGE_CONFIRMATION_LETTER', '款项用途确认函', 1, NULL, 15, '1', '2025-12-11 10:04:10', 3, '2025-12-11 10:04:10', 3);
INSERT INTO filing_first_level_config (filing_materials_config_id, dir_code, dir_name, fixed_flag, condition_key, sort_code, enable_flag, create_time, create_by, update_time, update_by) VALUES((select id from filing_materials_config where business_type = 'FILING_BUSINESS_PAYMENT'), 'OTHER', '其他资料', 1, NULL, 16, '1', '2025-12-11 10:04:10', 3, '2025-12-11 10:04:10', 3);
INSERT INTO filing_first_level_config (filing_materials_config_id, dir_code, dir_name, fixed_flag, condition_key, sort_code, enable_flag, create_time, create_by, update_time, update_by) VALUES((select id from filing_materials_config where business_type = 'FILING_BUSINESS_LEASEHOLD'), 'OWNERSHIP_CERTIFICATION', '划拨函/其他权属证明文件、资料', 1, NULL, 1, '1', '2025-12-11 10:04:10', 3, '2025-12-11 10:04:10', 3);
INSERT INTO filing_first_level_config (filing_materials_config_id, dir_code, dir_name, fixed_flag, condition_key, sort_code, enable_flag, create_time, create_by, update_time, update_by) VALUES((select id from filing_materials_config where business_type = 'FILING_BUSINESS_LEASEHOLD'), 'ASSET_HANDOVER_FORM', '资产交接单', 1, NULL, 2, '1', '2025-12-11 10:04:10', 3, '2025-12-11 10:04:10', 3);
INSERT INTO filing_first_level_config (filing_materials_config_id, dir_code, dir_name, fixed_flag, condition_key, sort_code, enable_flag, create_time, create_by, update_time, update_by) VALUES((select id from filing_materials_config where business_type = 'FILING_BUSINESS_LEASEHOLD'), 'CONTRACT', '买卖合同/采购合同/建设施工合同', 1, NULL, 3, '1', '2025-12-11 10:04:10', 3, '2025-12-11 10:04:10', 3);
INSERT INTO filing_first_level_config (filing_materials_config_id, dir_code, dir_name, fixed_flag, condition_key, sort_code, enable_flag, create_time, create_by, update_time, update_by) VALUES((select id from filing_materials_config where business_type = 'FILING_BUSINESS_LEASEHOLD'), 'LEASED_ASSET_INVOICES', '租赁物发票', 1, NULL, 4, '1', '2025-12-11 10:04:10', 3, '2025-12-11 10:04:10', 3);
INSERT INTO filing_first_level_config (filing_materials_config_id, dir_code, dir_name, fixed_flag, condition_key, sort_code, enable_flag, create_time, create_by, update_time, update_by) VALUES((select id from filing_materials_config where business_type = 'FILING_BUSINESS_LEASEHOLD'), 'VEHICLE_CERTIFICATE', '车辆登记证/合格证', 1, NULL, 5, '1', '2025-12-11 10:04:10', 3, '2025-12-11 10:04:10', 3);
INSERT INTO filing_first_level_config (filing_materials_config_id, dir_code, dir_name, fixed_flag, condition_key, sort_code, enable_flag, create_time, create_by, update_time, update_by) VALUES((select id from filing_materials_config where business_type = 'FILING_BUSINESS_LEASEHOLD'), 'SHIP_OWNERSHIP_CERTIFICATE', '船舶权证及交接文件', 1, NULL, 6, '1', '2025-12-11 10:04:10', 3, '2025-12-11 10:04:10', 3);
INSERT INTO filing_first_level_config (filing_materials_config_id, dir_code, dir_name, fixed_flag, condition_key, sort_code, enable_flag, create_time, create_by, update_time, update_by) VALUES((select id from filing_materials_config where business_type = 'FILING_BUSINESS_LEASEHOLD'), 'REAL_ESTATE_RIGHT_CERTIFICATE', '不动产权证', 1, NULL, 7, '1', '2025-12-11 10:04:10', 3, '2025-12-11 10:04:10', 3);
INSERT INTO filing_first_level_config (filing_materials_config_id, dir_code, dir_name, fixed_flag, condition_key, sort_code, enable_flag, create_time, create_by, update_time, update_by) VALUES((select id from filing_materials_config where business_type = 'FILING_BUSINESS_LEASEHOLD'), 'LEASED_ASSET_PAYMENT_VOUCHERS', '租赁物付款凭证', 1, NULL, 8, '1', '2025-12-11 10:04:10', 3, '2025-12-11 10:04:10', 3);
INSERT INTO filing_first_level_config (filing_materials_config_id, dir_code, dir_name, fixed_flag, condition_key, sort_code, enable_flag, create_time, create_by, update_time, update_by) VALUES((select id from filing_materials_config where business_type = 'FILING_BUSINESS_LEASEHOLD'), 'FIXED_ASSETS_LIST', '固定资产清单', 1, NULL, 9, '1', '2025-12-11 10:04:10', 3, '2025-12-11 10:04:10', 3);
INSERT INTO filing_first_level_config (filing_materials_config_id, dir_code, dir_name, fixed_flag, condition_key, sort_code, enable_flag, create_time, create_by, update_time, update_by) VALUES((select id from filing_materials_config where business_type = 'FILING_BUSINESS_LEASEHOLD'), 'ACCOUNTING_VOUCHERS', '记账凭证', 1, NULL, 10, '1', '2025-12-11 10:04:10', 3, '2025-12-11 10:04:10', 3);
INSERT INTO filing_first_level_config (filing_materials_config_id, dir_code, dir_name, fixed_flag, condition_key, sort_code, enable_flag, create_time, create_by, update_time, update_by) VALUES((select id from filing_materials_config where business_type = 'FILING_BUSINESS_LEASEHOLD'), 'LEASED_ASSET_INSURANCE', '租赁物财产保险单/批单', 1, NULL, 11, '1', '2025-12-11 10:04:10', 3, '2025-12-11 10:04:10', 3);
INSERT INTO filing_first_level_config (filing_materials_config_id, dir_code, dir_name, fixed_flag, condition_key, sort_code, enable_flag, create_time, create_by, update_time, update_by) VALUES((select id from filing_materials_config where business_type = 'FILING_BUSINESS_LEASEHOLD'), 'LEASED_ASSET_PHOTOS', '租赁物照片', 1, NULL, 12, '1', '2025-12-11 10:04:10', 3, '2025-12-11 10:04:10', 3);
INSERT INTO filing_first_level_config (filing_materials_config_id, dir_code, dir_name, fixed_flag, condition_key, sort_code, enable_flag, create_time, create_by, update_time, update_by) VALUES((select id from filing_materials_config where business_type = 'FILING_BUSINESS_LEASEHOLD'), 'CNR_INFORMATION', '中登网登记信息', 1, NULL, 13, '1', '2025-12-11 10:04:10', 3, '2025-12-11 10:04:10', 3);
INSERT INTO filing_first_level_config (filing_materials_config_id, dir_code, dir_name, fixed_flag, condition_key, sort_code, enable_flag, create_time, create_by, update_time, update_by) VALUES((select id from filing_materials_config where business_type = 'FILING_BUSINESS_LEASEHOLD'), 'MORTGAGE_REGISTRATION_CERTIFICATION', '租赁物抵押登记证明文件（如有，如车辆等）', 1, NULL, 14, '1', '2025-12-11 10:04:10', 3, '2025-12-11 10:04:10', 3);
INSERT INTO filing_first_level_config (filing_materials_config_id, dir_code, dir_name, fixed_flag, condition_key, sort_code, enable_flag, create_time, create_by, update_time, update_by) VALUES((select id from filing_materials_config where business_type = 'FILING_BUSINESS_LEASEHOLD'), 'LEASED_ASSET_EVALUATION_REPORT', '租赁物评估报告', 1, NULL, 15, '1', '2025-12-11 10:04:10', 3, '2025-12-11 10:04:10', 3);
INSERT INTO filing_first_level_config (filing_materials_config_id, dir_code, dir_name, fixed_flag, condition_key, sort_code, enable_flag, create_time, create_by, update_time, update_by) VALUES((select id from filing_materials_config where business_type = 'FILING_BUSINESS_LEASEHOLD'), 'OPERATIONAL_CERTIFICATION_DOCUMENTS', '经营性证明文件', 1, NULL, 16, '1', '2025-12-11 10:04:10', 3, '2025-12-11 10:04:10', 3);
INSERT INTO filing_first_level_config (filing_materials_config_id, dir_code, dir_name, fixed_flag, condition_key, sort_code, enable_flag, create_time, create_by, update_time, update_by) VALUES((select id from filing_materials_config where business_type = 'FILING_BUSINESS_LEASEHOLD'), 'OTHER', '其他资料', 1, NULL, 17, '1', '2025-12-11 10:04:10', 3, '2025-12-11 10:04:10', 3);
INSERT INTO filing_first_level_config (filing_materials_config_id, dir_code, dir_name, fixed_flag, condition_key, sort_code, enable_flag, create_time, create_by, update_time, update_by) VALUES((select id from filing_materials_config where business_type = 'FILING_BUSINESS_COLLATERALIZATION'), 'COLLATERAL_REGISTRATION', '抵/质押物登记权属凭证原件或核对无误的原件复印件', 1, NULL, 1, '1', '2025-12-11 10:04:10', 3, '2025-12-11 10:04:10', 3);
INSERT INTO filing_first_level_config (filing_materials_config_id, dir_code, dir_name, fixed_flag, condition_key, sort_code, enable_flag, create_time, create_by, update_time, update_by) VALUES((select id from filing_materials_config where business_type = 'FILING_BUSINESS_COLLATERALIZATION'), 'COLLATERAL_EVALUATION_REPORT', '抵押物、质押物评估报告（若有）', 1, NULL, 2, '1', '2025-12-11 10:04:10', 3, '2025-12-11 10:04:10', 3);
INSERT INTO filing_first_level_config (filing_materials_config_id, dir_code, dir_name, fixed_flag, condition_key, sort_code, enable_flag, create_time, create_by, update_time, update_by) VALUES((select id from filing_materials_config where business_type = 'FILING_BUSINESS_COLLATERALIZATION'), 'COLLATERAL_PROVIDER_ID_CARD', '抵/质押人身份证', 1, NULL, 3, '1', '2025-12-11 10:04:10', 3, '2025-12-11 10:04:10', 3);
INSERT INTO filing_first_level_config (filing_materials_config_id, dir_code, dir_name, fixed_flag, condition_key, sort_code, enable_flag, create_time, create_by, update_time, update_by) VALUES((select id from filing_materials_config where business_type = 'FILING_BUSINESS_COLLATERALIZATION'), 'BUSINESS_LICENSE', '营业执照', 1, NULL, 4, '1', '2025-12-11 10:04:10', 3, '2025-12-11 10:04:10', 3);
INSERT INTO filing_first_level_config (filing_materials_config_id, dir_code, dir_name, fixed_flag, condition_key, sort_code, enable_flag, create_time, create_by, update_time, update_by) VALUES((select id from filing_materials_config where business_type = 'FILING_BUSINESS_COLLATERALIZATION'), 'ACCOUNT_CERTIFICATE', '开户许可证/基本存款账户', 1, NULL, 5, '1', '2025-12-11 10:04:10', 3, '2025-12-11 10:04:10', 3);
INSERT INTO filing_first_level_config (filing_materials_config_id, dir_code, dir_name, fixed_flag, condition_key, sort_code, enable_flag, create_time, create_by, update_time, update_by) VALUES((select id from filing_materials_config where business_type = 'FILING_BUSINESS_COLLATERALIZATION'), 'VALID_LOAN_CARD', '有效贷款卡（如有）', 1, NULL, 6, '1', '2025-12-11 10:04:10', 3, '2025-12-11 10:04:10', 3);
INSERT INTO filing_first_level_config (filing_materials_config_id, dir_code, dir_name, fixed_flag, condition_key, sort_code, enable_flag, create_time, create_by, update_time, update_by) VALUES((select id from filing_materials_config where business_type = 'FILING_BUSINESS_COLLATERALIZATION'), 'COMPANY_ARTICLES', '公司章程及章程修正案', 1, NULL, 7, '1', '2025-12-11 10:04:10', 3, '2025-12-11 10:04:10', 3);
INSERT INTO filing_first_level_config (filing_materials_config_id, dir_code, dir_name, fixed_flag, condition_key, sort_code, enable_flag, create_time, create_by, update_time, update_by) VALUES((select id from filing_materials_config where business_type = 'FILING_BUSINESS_COLLATERALIZATION'), 'LEGAL_REPRESENTATIVE_ID_CARD', '法定代表人身份证', 1, NULL, 8, '1', '2025-12-11 10:04:10', 3, '2025-12-11 10:04:10', 3);
INSERT INTO filing_first_level_config (filing_materials_config_id, dir_code, dir_name, fixed_flag, condition_key, sort_code, enable_flag, create_time, create_by, update_time, update_by) VALUES((select id from filing_materials_config where business_type = 'FILING_BUSINESS_COLLATERALIZATION'), 'LEGAL_REPRESENTATIVE_CERTIFICATION', '法定代表人身份证明书', 1, NULL, 9, '1', '2025-12-11 10:04:10', 3, '2025-12-11 10:04:10', 3);
INSERT INTO filing_first_level_config (filing_materials_config_id, dir_code, dir_name, fixed_flag, condition_key, sort_code, enable_flag, create_time, create_by, update_time, update_by) VALUES((select id from filing_materials_config where business_type = 'FILING_BUSINESS_COLLATERALIZATION'), 'OTHER', '其他资料', 1, NULL, 10, '1', '2025-12-11 10:04:10', 3, '2025-12-11 10:04:10', 3);
INSERT INTO filing_first_level_config (filing_materials_config_id, dir_code, dir_name, fixed_flag, condition_key, sort_code, enable_flag, create_time, create_by, update_time, update_by) VALUES((select id from filing_materials_config where business_type = 'FILING_BUSINESS_COLLATERALIZATION'), 'BASIC_INFORMATION', '基础资料清单', 1, NULL, 0, '1', '2025-12-11 10:04:10', 3, '2025-12-11 10:04:10', 3);
INSERT INTO filing_first_level_config (filing_materials_config_id, dir_code, dir_name, fixed_flag, condition_key, sort_code, enable_flag, create_time, create_by, update_time, update_by) VALUES((select id from filing_materials_config where business_type = 'FILING_BUSINESS_LEASEHOLD'), 'BASIC_INFORMATION', '基础资料清单', 1, NULL, 0, '1', '2025-12-11 10:04:10', 3, '2025-12-11 10:04:10', 3);
INSERT INTO filing_first_level_config (filing_materials_config_id, dir_code, dir_name, fixed_flag, condition_key, sort_code, enable_flag, create_time, create_by, update_time, update_by) VALUES((select id from filing_materials_config where business_type = 'FILING_BUSINESS_PAYMENT'), 'BASIC_INFORMATION', '基础资料清单', 1, NULL, 0, '1', '2025-12-11 10:04:10', 3, '2025-12-11 10:04:10', 3);
INSERT INTO filing_first_level_config (filing_materials_config_id, dir_code, dir_name, fixed_flag, condition_key, sort_code, enable_flag, create_time, create_by, update_time, update_by) VALUES((select id from filing_materials_config where business_type = 'FILING_BUSINESS_INNER_OPERATION'), 'BASIC_INFORMATION', '基础资料清单', 1, NULL, 0, '1', '2025-12-11 10:04:10', 3, '2025-12-11 10:04:10', 3);
INSERT INTO filing_first_level_config (filing_materials_config_id, dir_code, dir_name, fixed_flag, condition_key, sort_code, enable_flag, create_time, create_by, update_time, update_by) VALUES((select id from filing_materials_config where business_type = 'FILING_BUSINESS_IND_CLIENT'), 'BASIC_INFORMATION', '基础资料清单', 1, NULL, 0, '1', '2025-12-11 10:04:10', 3, '2025-12-11 10:04:10', 3);
INSERT INTO filing_first_level_config (filing_materials_config_id, dir_code, dir_name, fixed_flag, condition_key, sort_code, enable_flag, create_time, create_by, update_time, update_by) VALUES((select id from filing_materials_config where business_type = 'FILING_BUSINESS_ENT_CLIENT'), 'BASIC_INFORMATION', '基础资料清单', 1, NULL, 0, '1', '2025-12-11 10:04:10', 3, '2025-12-11 10:04:10', 3);
INSERT INTO filing_first_level_config (filing_materials_config_id, dir_code, dir_name, fixed_flag, condition_key, sort_code, enable_flag, create_time, create_by, update_time, update_by) VALUES((select id from filing_materials_config where business_type = 'FILING_BUSINESS_LESSEE_CLIENT'), 'BASIC_INFORMATION', '基础资料清单', 1, NULL, 0, '1', '2025-12-11 10:04:10', 3, '2025-12-11 10:04:10', 3);


delete from filing_condition_config;
INSERT INTO filing_condition_config (condition_key, condition_desc, enable_flag, create_time, create_by, update_time, update_by) VALUES('APPROVAL_CREDIT', '授信立项审批是否审批通过', '1', '2025-12-11 10:31:37', 3, '2025-12-13 14:28:49', 3);
INSERT INTO filing_condition_config (condition_key, condition_desc, enable_flag, create_time, create_by, update_time, update_by) VALUES('APPROVAL_CHANGE_CREDIT', '授信立项变更审批是否审批通过', '1', '2025-12-11 10:31:37', 3, '2025-12-13 14:28:49', 3);
INSERT INTO filing_condition_config (condition_key, condition_desc, enable_flag, create_time, create_by, update_time, update_by) VALUES('APPROVAL_PROJECT', '项目立项审批是否审批通过', '1', '2025-12-11 10:31:37', 3, '2025-12-13 14:28:49', 3);
INSERT INTO filing_condition_config (condition_key, condition_desc, enable_flag, create_time, create_by, update_time, update_by) VALUES('APPROVAL_CHANGE_PROJECT', '项目立项审批是否审批通过', '1', '2025-12-11 10:31:37', 3, '2025-12-13 14:28:49', 3);
INSERT INTO filing_condition_config (condition_key, condition_desc, enable_flag, create_time, create_by, update_time, update_by) VALUES('APPROVAL_PROJECT_REVIEW', '项目评审流程是否审批通过', '1', '2025-12-11 10:31:37', 3, '2025-12-13 14:28:49', 3);
INSERT INTO filing_condition_config (condition_key, condition_desc, enable_flag, create_time, create_by, update_time, update_by) VALUES('APPROVAL_CHANGE_PROJECT_REVIEW', '项目评审变更流程是否审批通过', '1', '2025-12-11 10:31:37', 3, '2025-12-13 14:28:49', 3);
INSERT INTO filing_condition_config (condition_key, condition_desc, enable_flag, create_time, create_by, update_time, update_by) VALUES('APPROVAL_LEASEHOLD', '租赁物审批是否审批通过', '1', '2025-12-11 10:31:37', 3, '2025-12-13 14:28:49', 3);
INSERT INTO filing_condition_config (condition_key, condition_desc, enable_flag, create_time, create_by, update_time, update_by) VALUES('APPROVAL_LEASEHOLD_REVIEW', '租赁物变更审批是否审批通过', '1', '2025-12-11 10:31:37', 3, '2025-12-13 14:28:49', 3);
INSERT INTO filing_condition_config (condition_key, condition_desc, enable_flag, create_time, create_by, update_time, update_by) VALUES('APPROVAL_CONTRACT', '合同签署审批流程是否审批通过', '1', '2025-12-11 10:31:37', 3, '2025-12-13 14:28:49', 3);
INSERT INTO filing_condition_config (condition_key, condition_desc, enable_flag, create_time, create_by, update_time, update_by) VALUES('APPROVAL_PAYMENT', '付款审批流程是否审批通过', '1', '2025-12-11 10:31:37', 3, '2025-12-13 14:28:49', 3);
INSERT INTO filing_condition_config (condition_key, condition_desc, enable_flag, create_time, create_by, update_time, update_by) VALUES('APPROVAL_PROJECT_PRICING', '项目定价审批流程', '1', '2025-12-12 14:26:28', 3, '2025-12-13 14:28:49', 3);
INSERT INTO filing_condition_config (condition_key, condition_desc, enable_flag, create_time, create_by, update_time, update_by) VALUES('APPROVAL_CHANGE_PROJECT_PRICING', '项目定价变更审批流程', '1', '2025-12-12 14:26:28', 3, '2025-12-13 14:28:49', 3);


delete from  bifrost_system_config where config_key in ('filingFlowInitReviewUser','filingFlowEmailUser','filingFlowSupplementFollowUpEmailUser');
INSERT INTO bifrost_system_config (config_key, config_value, created_by, updated_by, description, status, `type`) VALUES('filingFlowInitReviewUser', '[150]', 'admin', 'admin', '项目资料归档流程-档案管理岗经办人', 1, 'Json');
INSERT INTO bifrost_system_config (config_key, config_value, created_by, updated_by, description, status, `type`) VALUES('filingFlowEmailUser', '[150,103,193,151]', 'admin', 'admin', '项目资料归档流程-邮件接收人', 1, 'Json');
INSERT INTO bifrost_system_config (config_key, config_value, created_by, updated_by, description, status, `type`) VALUES('filingFlowSupplementFollowUpEmailUser', '[150,103,193,151,50]', 'admin', 'admin', '项目资料归档流程-邮件接收人', 1, 'Json');




delete from bifrost_menu where code ='archivesfilingMaterials';
INSERT INTO bifrost_menu (code, `level`, sort_no, `type`, `path`, parent_id, icon, name,en_name, target, create_by, update_by) VALUES('archivesfilingMaterials', 3, 0, '0', '/archives/filingMaterials', NULL, NULL, '资料归档', '', '_self', 'system', 'system');

delete from gruul_function_group where code in ('filing-Read','filing-Edit');
INSERT INTO gruul_function_group ( sort_no, code, name, group_describe,menu_id) VALUES( 0, 'filing-Read', '项目资料归档-查看', '项目资料归档-查看',(select id from bifrost_menu bm where code = 'archivesfilingMaterials'));
INSERT INTO gruul_function_group ( sort_no, code, name, group_describe,menu_id) VALUES( 0, 'filing-Edit', '项目资料归档-编辑', '项目资料归档-编辑',(select id from bifrost_menu bm where code = 'archivesfilingMaterials'));

delete from bifrost_role_menu_function where function_id in (select id from bifrost_function where code in (
    'filingFileBatchDownload',
    'filingGetTab',
    'filingGetCustomerReferenceMaterials',
    'filingSynchronizationButtonFlag',
    'filingMaterialsSynchronization',
    'filingMaterialsImport',
    'filingGetNonCustomerReferenceMaterials',
    'filingGetOperationsDirDict',
    'filingBusinessInnerOperationFileBatchRemove',
    'filingBusinessClientFileBatchRemove',
    'filingBusinessPaymentFileBatchRemove',
    'filingBusinessLeaseholdFileBatchRemove',
    'filingBusinessCollateralizationFileBatchRemove',
    'filingBusinessInnerOperationFilingUpload',
    'filingBusinessClientFilingUpload',
    'filingBusinessPaymentFilingUpload',
    'filingBusinessLeaseholdFilingUpload',
    'filingBusinessCollateralizationFilingUpload',
    'filingBusinessInnerOperationFileDownload',
    'filingBusinessClientFileDownload',
    'filingBusinessPaymentFileDownload',
    'filingBusinessLeaseholdFileDownload',
    'filingBusinessCollateralizationFileDownload'
));
delete from bifrost_function where code in (
    'filingFileBatchDownload',
    'filingGetTab',
    'filingGetCustomerReferenceMaterials',
    'filingSynchronizationButtonFlag',
    'filingMaterialsSynchronization',
    'filingMaterialsImport',
    'filingGetNonCustomerReferenceMaterials',
    'filingGetOperationsDirDict',
    'filingBusinessInnerOperationFileBatchRemove',
    'filingBusinessClientFileBatchRemove',
    'filingBusinessPaymentFileBatchRemove',
    'filingBusinessLeaseholdFileBatchRemove',
    'filingBusinessCollateralizationFileBatchRemove',
    'filingBusinessInnerOperationFilingUpload',
    'filingBusinessClientFilingUpload',
    'filingBusinessPaymentFilingUpload',
    'filingBusinessLeaseholdFilingUpload',
    'filingBusinessCollateralizationFilingUpload',
    'filingBusinessInnerOperationFileDownload',
    'filingBusinessClientFileDownload',
    'filingBusinessPaymentFileDownload',
    'filingBusinessLeaseholdFileDownload',
    'filingBusinessCollateralizationFileDownload'
);
INSERT INTO bifrost_function ( code, name, sort_no, menu_id, create_by, update_by, en_name, `method`, `path`, `type`, group_id) VALUES('filingFileBatchDownload', '批量下载', 0, (select id from bifrost_menu where code= 'archivesfilingMaterials'), NULL, NULL, 'filingFileBatchDownload', 'GET', '/filingMaterial/batchDownload', 1, (select id from gruul_function_group where group_describe = '项目资料归档-编辑'));
INSERT INTO bifrost_function ( code, name, sort_no, menu_id, create_by, update_by, en_name, `method`, `path`, `type`, group_id) VALUES('filingGetTab', '项目资料归档-获取tab', 0, (select id from bifrost_menu where code= 'archivesfilingMaterials'), NULL, NULL, 'filingGetTab', 'POST', '/filingMaterial/getTab', 1, (select id from gruul_function_group where group_describe = '项目资料归档-编辑'));
INSERT INTO bifrost_function ( code, name, sort_no, menu_id, create_by, update_by, en_name, `method`, `path`, `type`, group_id) VALUES('filingGetCustomerReferenceMaterials', '项目资料归档-基本信息资料清单', 0, (select id from bifrost_menu where code= 'archivesfilingMaterials'), NULL, NULL, 'filingGetCustomerReferenceMaterials', 'POST', '/filingMaterial/getCustomerReferenceMaterials', 1, (select id from gruul_function_group where group_describe = '项目资料归档-编辑'));
INSERT INTO bifrost_function ( code, name, sort_no, menu_id, create_by, update_by, en_name, `method`, `path`, `type`, group_id) VALUES('filingSynchronizationButtonFlag', '项目资料归档-资料同步是否展示', 0, (select id from bifrost_menu where code= 'archivesfilingMaterials'), NULL, NULL, 'filingSynchronizationButtonFlag', 'POST', '/filingMaterial/synchronizationButtonFlag', 1, (select id from gruul_function_group where group_describe = '项目资料归档-编辑'));
INSERT INTO bifrost_function ( code, name, sort_no, menu_id, create_by, update_by, en_name, `method`, `path`, `type`, group_id) VALUES( 'filingMaterialsSynchronization', '项目资料归档-资料同步', 0, (select id from bifrost_menu where code= 'archivesfilingMaterials'), NULL, NULL, 'filingMaterialsSynchronization', 'POST', '/filingMaterial/materialsSynchronization', 1, (select id from gruul_function_group where group_describe = '项目资料归档-编辑'));
INSERT INTO bifrost_function ( code, name, sort_no, menu_id, create_by, update_by, en_name, `method`, `path`, `type`, group_id) VALUES('filingMaterialsImport', '项目资料归档-资料引入', 0, (select id from bifrost_menu where code= 'archivesfilingMaterials'), NULL, NULL, 'filingMaterialsImport', 'POST', '/filingMaterial/materialsImport', 1, (select id from gruul_function_group where group_describe = '项目资料归档-编辑'));
INSERT INTO bifrost_function ( code, name, sort_no, menu_id, create_by, update_by, en_name, `method`, `path`, `type`, group_id) VALUES('filingGetNonCustomerReferenceMaterials', '项目资料归档-非基础信息的参考资料', 0, (select id from bifrost_menu where code= 'archivesfilingMaterials'), NULL, NULL, 'filingGetNonCustomerReferenceMaterials', 'POST', '/filingMaterial/getNonCustomerReferenceMaterials', 1, (select id from gruul_function_group where group_describe = '项目资料归档-编辑'));
INSERT INTO bifrost_function ( code, name, sort_no, menu_id, create_by, update_by, en_name, `method`, `path`, `type`, group_id) VALUES('filingGetOperationsDirDict', '获取运营终审列表展示一级目录', 0, (select id from bifrost_menu where code= 'archivesfilingMaterials'), NULL, NULL, 'filingGetOperationsDirDict', 'POST', '/filingMaterial/getOperationsDirDict', 1, (select id from gruul_function_group where group_describe = '项目资料归档-编辑'));
INSERT INTO bifrost_function ( code, name, sort_no, menu_id, create_by, update_by, en_name, `method`, `path`, `type`, group_id) VALUES('filingBusinessInnerOperationFileBatchRemove', '内部操作-文件删除', 0, (select id from bifrost_menu where code= 'archivesfilingMaterials'), NULL, NULL, 'filingBusinessInnerOperationFileBatchRemove', 'POST', '/file/batch/remove', 1, (select id from gruul_function_group where group_describe = '项目资料归档-编辑'));
INSERT INTO bifrost_function ( code, name, sort_no, menu_id, create_by, update_by, en_name, `method`, `path`, `type`, group_id) VALUES('filingBusinessClientFileBatchRemove', '基本信息-文件删除', 0, (select id from bifrost_menu where code= 'archivesfilingMaterials'), NULL, NULL, 'filingBusinessClientFileBatchRemove', 'POST', '/file/batch/remove', 1, (select id from gruul_function_group where group_describe = '项目资料归档-编辑'));
INSERT INTO bifrost_function ( code, name, sort_no, menu_id, create_by, update_by, en_name, `method`, `path`, `type`, group_id) VALUES('filingBusinessPaymentFileBatchRemove', '合同资料-文件删除', 0, (select id from bifrost_menu where code= 'archivesfilingMaterials'), NULL, NULL, 'filingBusinessPaymentFileBatchRemove', 'POST', '/file/batch/remove', 1, (select id from gruul_function_group where group_describe = '项目资料归档-编辑'));
INSERT INTO bifrost_function ( code, name, sort_no, menu_id, create_by, update_by, en_name, `method`, `path`, `type`, group_id) VALUES('filingBusinessLeaseholdFileBatchRemove', '租赁物资料-文件删除', 0, (select id from bifrost_menu where code= 'archivesfilingMaterials'), NULL, NULL, 'filingBusinessLeaseholdFileBatchRemove', 'POST', '/file/batch/remove', 1, (select id from gruul_function_group where group_describe = '项目资料归档-编辑'));
INSERT INTO bifrost_function ( code, name, sort_no, menu_id, create_by, update_by, en_name, `method`, `path`, `type`, group_id) VALUES('filingBusinessCollateralizationFileBatchRemove', '抵质押资料-文件删除', 0, (select id from bifrost_menu where code= 'archivesfilingMaterials'), NULL, NULL, 'filingBusinessCollateralizationFileBatchRemove', 'POST', '/file/batch/remove', 1, (select id from gruul_function_group where group_describe = '项目资料归档-编辑'));
INSERT INTO bifrost_function ( code, name, sort_no, menu_id, create_by, update_by, en_name, `method`, `path`, `type`, group_id) VALUES('filingBusinessInnerOperationFilingUpload', '内部操作-文件上传', 0, (select id from bifrost_menu where code= 'archivesfilingMaterials'), NULL, NULL, 'filingBusinessInnerOperationFilingUpload', 'POST', '/file/upload', 1, (select id from gruul_function_group where group_describe = '项目资料归档-编辑'));
INSERT INTO bifrost_function ( code, name, sort_no, menu_id, create_by, update_by, en_name, `method`, `path`, `type`, group_id) VALUES('filingBusinessClientFilingUpload', '基本信息-文件上传', 0, (select id from bifrost_menu where code= 'archivesfilingMaterials'), NULL, NULL, 'filingBusinessClientFilingUpload', 'POST', '/file/upload', 1, (select id from gruul_function_group where group_describe = '项目资料归档-编辑'));
INSERT INTO bifrost_function ( code, name, sort_no, menu_id, create_by, update_by, en_name, `method`, `path`, `type`, group_id) VALUES('filingBusinessPaymentFilingUpload', '合同资料-文件上传', 0, (select id from bifrost_menu where code= 'archivesfilingMaterials'), NULL, NULL, 'filingBusinessPaymentFilingUpload', 'POST', '/file/upload', 1, (select id from gruul_function_group where group_describe = '项目资料归档-编辑'));
INSERT INTO bifrost_function ( code, name, sort_no, menu_id, create_by, update_by, en_name, `method`, `path`, `type`, group_id) VALUES('filingBusinessLeaseholdFilingUpload', '租赁物资料-文件上传', 0, (select id from bifrost_menu where code= 'archivesfilingMaterials'), NULL, NULL, 'filingBusinessLeaseholdFilingUpload', 'POST', '/file/upload', 1, (select id from gruul_function_group where group_describe = '项目资料归档-编辑'));
INSERT INTO bifrost_function ( code, name, sort_no, menu_id, create_by, update_by, en_name, `method`, `path`, `type`, group_id) VALUES('filingBusinessCollateralizationFilingUpload', '抵质押资料-文件上传', 0, (select id from bifrost_menu where code= 'archivesfilingMaterials'), NULL, NULL, 'filingBusinessCollateralizationFilingUpload', 'POST', '/file/upload', 1, (select id from gruul_function_group where group_describe = '项目资料归档-编辑'));
INSERT INTO bifrost_function ( code, name, sort_no, menu_id, create_by, update_by, en_name, `method`, `path`, `type`, group_id) VALUES('filingBusinessInnerOperationFileDownload', '内部操作-文件下载', 0, (select id from bifrost_menu where code= 'archivesfilingMaterials'), NULL, NULL, 'filingBusinessInnerOperationFileDownload', 'GET', '/file/download', 1, (select id from gruul_function_group where group_describe = '项目资料归档-编辑'));
INSERT INTO bifrost_function ( code, name, sort_no, menu_id, create_by, update_by, en_name, `method`, `path`, `type`, group_id) VALUES('filingBusinessClientFileDownload', '基本信息-文件下载', 0, (select id from bifrost_menu where code= 'archivesfilingMaterials'), NULL, NULL, 'filingBusinessClientFileDownload', 'GET', '/file/download', 1, (select id from gruul_function_group where group_describe = '项目资料归档-编辑'));
INSERT INTO bifrost_function ( code, name, sort_no, menu_id, create_by, update_by, en_name, `method`, `path`, `type`, group_id) VALUES('filingBusinessPaymentFileDownload', '合同资料-文件上传', 0, (select id from bifrost_menu where code= 'archivesfilingMaterials'), NULL, NULL, 'filingBusinessPaymentFileDownload', 'GET', '/file/download', 1, (select id from gruul_function_group where group_describe = '项目资料归档-编辑'));
INSERT INTO bifrost_function ( code, name, sort_no, menu_id, create_by, update_by, en_name, `method`, `path`, `type`, group_id) VALUES('filingBusinessLeaseholdFileDownload', '租赁物资料-文件下载', 0, (select id from bifrost_menu where code= 'archivesfilingMaterials'), NULL, NULL, 'filingBusinessLeaseholdFileDownload', 'GET', '/file/download', 1, (select id from gruul_function_group where group_describe = '项目资料归档-编辑'));
INSERT INTO bifrost_function ( code, name, sort_no, menu_id, create_by, update_by, en_name, `method`, `path`, `type`, group_id) VALUES('filingBusinessCollateralizationFileDownload', '抵质押资料-文件下载', 0, (select id from bifrost_menu where code= 'archivesfilingMaterials'), NULL, NULL, 'filingBusinessCollateralizationFileDownload', 'GET', '/file/download', 1, (select id from gruul_function_group where group_describe = '项目资料归档-编辑'));


INSERT INTO bifrost_role_menu_function(role_id, menu_id, function_id, custom_tree_id)
SELECT role.id, menu.id, function.id, tree.id
FROM bifrost_role role,
     bifrost_function function,
     bifrost_menu menu,
     bifrost_custom_tree tree
WHERE role.name IN ('运营管理部经办人')
  and function.code like 'filing%'
  and menu.name = '资料归档'
  and tree.name = '档案管理';

INSERT INTO bifrost_role_menu_function(role_id, menu_id, function_id, custom_tree_id)
SELECT role.id, menu.id, function.id, tree.id
FROM bifrost_role role,
     bifrost_function function,
     bifrost_menu menu,
     bifrost_custom_tree tree
WHERE role.name IN ('项目经理')
  and function.code like 'filing%' and function.path not in ('/file/upload','/file/batch/remove')
  and menu.name = '资料归档'
  and tree.name = '档案管理';