package cn.zswltech.mithras.fund.directfinancing.application.directfinancing;

import cn.zswltech.mithras.api.fund.directfinancing.FundDirectFinancingSubscriptionDetailApi;

public interface FundDirectFinancingSubscriptionDetailApplicationService extends FundDirectFinancingSubscriptionDetailApi {
}
