export { default as CpmMarginManagement } from './MarginManagement'
export { default as CpmMarginManagementDetail } from './MarginManagement/detail/[id$]'
export { default as CpmMarginManagementPaymentRecords } from './MarginManagement/PaymentRecords'
export { default as CpmMarginManagementRefundRecords } from './MarginManagement/RefundRecords'
export { default as CpmMarginManagementVerificationRecords } from './MarginManagement/VerificationRecords'
