<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>zswl-mithras</artifactId>
        <groupId>cn.zswltech</groupId>
        <version>${revision}</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>zswl-mithras-identity</artifactId>

    <dependencies>
        <dependency>
            <groupId>cn.zswltech</groupId>
            <artifactId>zswl-mithras-api</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>cn.zswltech</groupId>
            <artifactId>zswl-mithras-service-core</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>cn.zswltech</groupId>
            <artifactId>zswl-mithras-blackgray</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>cn.zswltech</groupId>
            <artifactId>gruul-spring-boot-starter</artifactId>
            <version>3.5.2-mithras.RELEASE</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>cn.hutool</groupId>
            <artifactId>hutool-all</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>fastjson</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-web</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>javax.servlet</groupId>
            <artifactId>javax.servlet-api</artifactId>
            <scope>provided</scope>
        </dependency>
    </dependencies>
</project>
