<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>zswl-mithras</artifactId>
        <groupId>cn.zswltech</groupId>
        <version>${revision}</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>zswl-mithras-archives</artifactId>

    <dependencies>
        <dependency>
            <groupId>cn.zswltech</groupId>
            <artifactId>zswl-mithras-api</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>cn.zswltech</groupId>
            <artifactId>zswl-mithras-foundation</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>cn.zswltech</groupId>
            <artifactId>zswl-mithras-projectprocess</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>cn.zswltech</groupId>
            <artifactId>zswl-mithras-workflow</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>cn.zswltech</groupId>
            <artifactId>zswl-mithras-system</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>cn.zswltech</groupId>
            <artifactId>zswl-mithras-message</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>cn.zswltech</groupId>
            <artifactId>zswl-mithras-document</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>cn.zswltech.flow</groupId>
            <artifactId>core</artifactId>
            <version>1.5.11-mithras-RELEASE</version>
            <scope>provided</scope>
            <exclusions>
                <exclusion>
                    <groupId>org.flywaydb</groupId>
                    <artifactId>flyway-core</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>cn.zswltech</groupId>
            <artifactId>gruul-spring-boot-starter</artifactId>
            <version>3.5.2-mithras.RELEASE</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-boot-starter</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-context</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-web</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-tx</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>javax.validation</groupId>
            <artifactId>validation-api</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>cn.hutool</groupId>
            <artifactId>hutool-all</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
            <scope>provided</scope>
        </dependency>
    </dependencies>
</project>
