CREATE TABLE `after_lease_adjust_info`
(
    `id`                      bigint(20) NOT NULL AUTO_INCREMENT,
    `client_id`               bigint(20) DEFAULT NULL COMMENT '客户id',
    `biz_type`                varchar(20)   DEFAULT NULL COMMENT '业务类型。租赁、保理、转租赁',
    `proj_id`                 bigint(20) DEFAULT NULL COMMENT '项目id',
    `proj_name`               varchar(200)  DEFAULT NULL COMMENT '项目名称',
    `proj_code`               varchar(20)   DEFAULT NULL COMMENT '项目编号',
    `lease_types`             varchar(100)  DEFAULT NULL COMMENT '租赁类型。直租、回租、经营性租赁',
    `factoring_types`         varchar(100)  DEFAULT NULL COMMENT '保理类型。有追明保理、无追明保理、有追暗保理',
    `zr_types`                varchar(100)  DEFAULT NULL COMMENT '转让类型。有追、无追',
    `proj_sponsor_user_id`    bigint(20) DEFAULT NULL COMMENT '项目主办用户id',
    `proj_cosponsor_user_ids` json          DEFAULT NULL COMMENT '项目协办方用户id列表',
    `biz_dept_id`             bigint(20) DEFAULT NULL COMMENT '业务部门id',
    `biz_dept_leader_id`      bigint(20) DEFAULT NULL COMMENT '业务部门负责人id',
    `biz_division_leader_id`  bigint(20) DEFAULT NULL COMMENT '业务分管领导id',
    `apply_credit_amount`     bigint(20) DEFAULT NULL COMMENT '申报授信金额',
    `after_lease_adjust_type` varchar(20)   DEFAULT NULL COMMENT '业务调整类型,展期,调整还款类型',
    `extensionMonth`          bigint(20) DEFAULT NULL COMMENT '展期月数',
    `adjust_explain`          varchar(1000) DEFAULT NULL COMMENT '调整说明',
    `adjust_status`           varchar(50)   DEFAULT NULL COMMENT '项目调整状态',
    `adjust_process_status`   varchar(50)   DEFAULT NULL COMMENT '调整流程状态',
    `risk_control_manager_id` bigint(20) DEFAULT NULL COMMENT '风控经理id',
    `legal_manager_user_id`   bigint(20) DEFAULT NULL COMMENT '法务经理id',
    `create_by`               bigint(20) DEFAULT NULL COMMENT '创建人、发起人',
    `create_time`             datetime      DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_by`               bigint(20) DEFAULT NULL COMMENT '最后更新人id',
    `update_time`             datetime      DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=198 DEFAULT CHARSET=utf8mb4 COMMENT='租后调整信息表';
