CREATE TABLE `after_lease_check_plan_base` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `plan_name` varchar(100) DEFAULT '' COMMENT '计划名称',
  `plan_type` varchar(20) NOT NULL COMMENT '计划类型',
  `year` int(11) DEFAULT NULL COMMENT '检查所属年份',
  `quarter` tinyint(4) DEFAULT NULL COMMENT '检查所属季度',
  `month` tinyint(4) DEFAULT NULL COMMENT '检查所属月份',
  `start_date` date DEFAULT NULL COMMENT '检查填报开始时间',
  `end_date` date DEFAULT NULL COMMENT '检查填报结束时间',
  `plan_status` varchar(20) NOT NULL COMMENT '计划状态',
  `approval_status` varchar(50) DEFAULT NULL COMMENT '审批状态',
  `create_by` bigint(20) DEFAULT NULL COMMENT '创建人、发起人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` bigint(20) DEFAULT NULL COMMENT '最后更新人id',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='租后检查计划表';

CREATE TABLE `after_lease_check_plan_base_lib` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `plan_name` varchar(100) DEFAULT '' COMMENT '计划名称',
  `plan_type` varchar(20) NOT NULL COMMENT '计划类型',
  `year` int(11) DEFAULT NULL COMMENT '检查所属年份',
  `quarter` tinyint(4) DEFAULT NULL COMMENT '检查所属季度',
  `month` tinyint(4) DEFAULT NULL COMMENT '检查所属月份',
  `start_date` date DEFAULT NULL COMMENT '检查填报开始时间',
  `end_date` date DEFAULT NULL COMMENT '检查填报结束时间',
  `plan_status` varchar(20) NOT NULL COMMENT '计划状态',
  `approval_status` varchar(50) DEFAULT NULL COMMENT '审批状态',
  `create_by` bigint(20) DEFAULT NULL COMMENT '创建人、发起人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` bigint(20) DEFAULT NULL COMMENT '最后更新人id',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `version` varchar(40) NOT NULL COMMENT '版本号',
  `origin_id` bigint(20) NOT NULL COMMENT '临时数据表id 需要用来比对数据 或者 流程拒绝时全量回写',
  `data_create_time` datetime DEFAULT NULL,
  `data_create_by` bigint(20) DEFAULT NULL,
  `data_update_time` datetime DEFAULT NULL,
  `data_update_by` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_origin_id` (`origin_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='租后检查计划版本表';

CREATE TABLE `after_lease_check_plan_project` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `plan_id` bigint(20) NOT NULL COMMENT '租后检查计划id',
  `project_id` bigint(20) NOT NULL COMMENT '项目评审id',
  `project_code` varchar(20) DEFAULT NULL COMMENT '项目编号',
  `project_name` varchar(200) DEFAULT NULL COMMENT '项目名称',
  `project_dept_id` bigint(20) NOT NULL COMMENT '项目所属业务部门id',
  `project_sponsor_id` bigint(20) NOT NULL COMMENT '项目主办id',
  `project_cosponsor_ids` varchar(100) DEFAULT NULL COMMENT '项目协办id',
  `is_check` tinyint(4) DEFAULT '0' COMMENT '是否需要检查',
  `check_way` varchar(20) DEFAULT '' COMMENT '检查形式',
  `risk_manager_id` bigint(20) DEFAULT NULL COMMENT '协查风控经理id',
  `risk_manager_name` varchar(20) DEFAULT NULL COMMENT '协查风控经理名称',
  `approval_status` varchar(20) NOT NULL COMMENT '审批状态',
  `report_type` varchar(20) DEFAULT NULL COMMENT '检查报告类型',
  `create_by` bigint(20) DEFAULT NULL COMMENT '创建人、发起人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` bigint(20) DEFAULT NULL COMMENT '最后更新人id',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_project_id` (`project_id`),
  KEY `idx_project_dept_id` (`project_dept_id`),
  KEY `idx_plan_id` (`plan_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='租后检查计划项目表';

CREATE TABLE `after_lease_check_plan_project_lib` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `plan_id` bigint(20) NOT NULL COMMENT '租后检查计划id',
  `project_id` bigint(20) NOT NULL COMMENT '项目评审id',
  `project_code` varchar(20) DEFAULT NULL COMMENT '项目编号',
  `project_name` varchar(200) DEFAULT NULL COMMENT '项目名称',
  `project_dept_id` bigint(20) NOT NULL COMMENT '项目归属业务部门id',
  `project_sponsor_id` bigint(20) NOT NULL COMMENT '项目主办id',
  `project_cosponsor_ids` varchar(100) DEFAULT NULL COMMENT '项目协办id',
  `is_check` tinyint(4) DEFAULT '0' COMMENT '是否需要检查',
  `check_way` varchar(20) DEFAULT '' COMMENT '检查形式',
  `risk_manager_id` bigint(20) DEFAULT NULL COMMENT '协查风控经理id',
  `risk_manager_name` varchar(20) DEFAULT NULL COMMENT '协查风控经理名称',
  `approval_status` varchar(20) NOT NULL COMMENT '审批状态',
  `report_type` varchar(20) NOT NULL DEFAULT '' COMMENT '报告类型',
  `create_by` bigint(20) DEFAULT NULL COMMENT '创建人、发起人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` bigint(20) DEFAULT NULL COMMENT '最后更新人id',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `version` varchar(40) NOT NULL COMMENT '版本号',
  `origin_id` bigint(20) NOT NULL COMMENT '临时数据表id 需要用来比对数据 或者 流程拒绝时全量回写',
  `data_create_time` datetime DEFAULT NULL,
  `data_create_by` bigint(20) DEFAULT NULL,
  `data_update_time` datetime DEFAULT NULL,
  `data_update_by` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_origin_id` (`origin_id`),
  KEY `idx_plan_id` (`plan_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='租后检查计划项目版本表';

CREATE TABLE `after_lease_check_project_report_base` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `check_plan_project_id` bigint(20) NOT NULL COMMENT '检查计划项目表主键id',
  `check_period_start` date DEFAULT NULL COMMENT '检查时段（开始）',
  `check_period_end` date DEFAULT NULL COMMENT '检查时段（结束）',
  `check_date` date NOT NULL COMMENT '检查日期',
  `main_person` varchar(50) DEFAULT '' COMMENT '主要受访人员',
  `job` varchar(50) DEFAULT '' COMMENT '职务',
  `contact_way` varchar(50) DEFAULT '' COMMENT '联系方式',
  `contract_amount` bigint(20) NOT NULL COMMENT '合同金额',
  `risk_exposure` bigint(20) NOT NULL COMMENT '风险敞口',
  `deadline` date NOT NULL COMMENT '到期日',
  `client_name` varchar(200) DEFAULT NULL COMMENT '客户名称',
  `industry` varchar(50) DEFAULT NULL COMMENT '行业',
  `next_repay_date` date DEFAULT NULL COMMENT '下次还款日期',
  `next_repay_amount` bigint(20) DEFAULT NULL COMMENT '下次还款金额',
  `create_by` bigint(20) DEFAULT NULL COMMENT '创建人、发起人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` bigint(20) DEFAULT NULL COMMENT '最后更新人id',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_plan_project_id` (`check_plan_project_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='租后检查报告基本信息表';

CREATE TABLE `after_lease_check_project_report_content` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `check_plan_project_id` bigint(20) NOT NULL COMMENT '检查计划项目表主键id',
  `template_id` bigint(20) NOT NULL COMMENT '检查内容模板id',
  `template_group_name` varchar(50) DEFAULT NULL COMMENT '检查内容模板分组名称',
  `template_code` varchar(50) DEFAULT NULL COMMENT '检查内容模板条目code',
  `template_title` varchar(100) NOT NULL COMMENT '检查内容模板条目',
  `template_content_input_type` varchar(20) NOT NULL COMMENT '检查内容模板输入框类型',
  `template_content_input_option` varchar(100) DEFAULT NULL COMMENT '检查内容模板输入框枚举类型（如果是下拉框等才会有值）',
  `template_order_num` int(11) NOT NULL DEFAULT '0' COMMENT '检查模板条目排序',
  `content` varchar(2000) DEFAULT NULL COMMENT '填写的检查内容',
  `create_by` bigint(20) DEFAULT NULL COMMENT '创建人、发起人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` bigint(20) DEFAULT NULL COMMENT '最后更新人id',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_plan_project_id` (`check_plan_project_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='租后检查报告检查内容表';

CREATE TABLE `after_lease_check_project_report_extra` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `check_plan_project_id` bigint(20) NOT NULL COMMENT '检查计划项目表主键id',
  `template_id` bigint(20) NOT NULL COMMENT '检查报告模板id',
  `template_code` varchar(50) DEFAULT NULL COMMENT '检查报告模板条目code',
  `template_title` varchar(100) NOT NULL DEFAULT '' COMMENT '检查报告模板条目',
  `template_order_num` int(11) NOT NULL DEFAULT '0' COMMENT '检查报告模板条目排序',
  `check_result` tinyint(4) DEFAULT NULL COMMENT '检查结果',
  `remark` varchar(2000) DEFAULT NULL COMMENT '备注',
  `create_by` bigint(20) DEFAULT NULL COMMENT '创建人、发起人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` bigint(20) DEFAULT NULL COMMENT '最后更新人id',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_plan_project_id` (`check_plan_project_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='租后检查报告补充说明（非公用事业）表';

CREATE TABLE `after_lease_check_project_report_summary` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `check_plan_project_id` bigint(20) NOT NULL COMMENT '检查计划项目表主键id',
  `template_id` bigint(20) NOT NULL COMMENT '检查总结模板id',
  `template_group_name` varchar(50) DEFAULT NULL COMMENT '检查总结条目分组',
  `template_code` varchar(50) DEFAULT NULL COMMENT '检查总结模板条目code',
  `template_title` varchar(100) NOT NULL DEFAULT '' COMMENT '检查总结模板条目',
  `template_content_input_type` varchar(20) NOT NULL DEFAULT '' COMMENT '检查总结模板输入框类型',
  `template_content_input_option` varchar(100) DEFAULT NULL COMMENT '检查总结模板输入框枚举类型（如果是下拉框等才会有值）',
  `template_order_num` int(11) NOT NULL DEFAULT '0' COMMENT '检查总结模板条目排序',
  `content` varchar(2000) DEFAULT NULL COMMENT '填写的检查内容',
  `create_by` bigint(20) DEFAULT NULL COMMENT '创建人、发起人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` bigint(20) DEFAULT NULL COMMENT '最后更新人id',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_plan_project_id` (`check_plan_project_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='租后检查报告检查总结表';

CREATE TABLE `after_lease_check_project_report_template` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `report_type` varchar(20) NOT NULL DEFAULT '' COMMENT '报告类型',
  `area_type` varchar(20) DEFAULT NULL COMMENT '区域类型',
  `group_name` varchar(50) DEFAULT NULL COMMENT '检查内容条目分组',
  `code` varchar(50) NOT NULL DEFAULT '' COMMENT '检查内容条目code',
  `title` varchar(100) NOT NULL COMMENT '检查内容条目',
  `content_input_type` varchar(20) DEFAULT '' COMMENT '检查内容输入框类型',
  `content_input_option` varchar(100) DEFAULT NULL COMMENT '检查内容输入框枚举类型（如果是下拉框等才会有值）',
  `order_num` int(11) NOT NULL DEFAULT '0' COMMENT '排序字段',
  `create_by` bigint(20) DEFAULT NULL COMMENT '创建人、发起人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` bigint(20) DEFAULT NULL COMMENT '最后更新人id',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='租后检查报告模板表';

CREATE TABLE `after_lease_check_external_query` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键id',
  `inspection_month` datetime DEFAULT NULL COMMENT '所属检查月',
  `proj_review_id` bigint(20) DEFAULT NULL COMMENT '项目id',
  `proj_name` varchar(255) DEFAULT NULL COMMENT '项目名称',
  `client_id` bigint(20) DEFAULT NULL COMMENT '客户id',
  `proj_sponsor_user_id` bigint(20) DEFAULT NULL COMMENT '项目主办用户id',
  `deadline` date DEFAULT NULL COMMENT '合同最终到期日',
  `inspection_date` date DEFAULT NULL COMMENT '检查日期',
  `approval_pass_time` datetime DEFAULT NULL COMMENT '审批通过时间',
  `approval_status` varchar(20) DEFAULT NULL COMMENT '状态',
  `dept_id` bigint(20) DEFAULT NULL COMMENT '租后检查部门',
  `industry_type` varchar(50) DEFAULT NULL COMMENT '行业',
  `risk_exposure` bigint(20) DEFAULT NULL COMMENT '风险敞口余额',
  `contract_total_amount` bigint(20) DEFAULT NULL COMMENT '合同金额',
  `next_repay_date` date DEFAULT NULL COMMENT '下次还款日',
  `next_repay_amount` bigint(20) DEFAULT NULL COMMENT '下次还款金额',
  `preventive_measures` varchar(500) DEFAULT NULL COMMENT '风险信号及重大事项、风险防范措施',
  `query_conclusion` varchar(500) DEFAULT NULL COMMENT '查询分析与查询结论',
  `create_by` bigint(20) DEFAULT NULL COMMENT '创建人、发起人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` bigint(20) DEFAULT NULL COMMENT '最后更新人id',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `biz_dept_leader` bigint(20) DEFAULT NULL,
  `biz_division_leader` bigint(20) DEFAULT NULL,
  `process_instance_id` varchar(50) DEFAULT NULL COMMENT '运行中的流程id',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='租后检查外部查询任务';

CREATE TABLE `after_lease_check_external_query_client_info` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `query_id` bigint(20) DEFAULT NULL COMMENT '所属外部信息查询任务id',
  `client_role` varchar(20) DEFAULT NULL COMMENT '客户角色-主承租人（Main lessee）承租人（）担保人（）',
  `client_id` bigint(20) DEFAULT NULL COMMENT '承租人/担保人id',
  `client_type` varchar(30) DEFAULT NULL COMMENT '客户类型',
  `query_time_from` date DEFAULT NULL COMMENT '查询时间',
  `query_time_to` date DEFAULT NULL COMMENT '查询时间',
  `credit_info` varchar(500) DEFAULT NULL COMMENT '全国企业信用信息公示系统查询',
  `court_info` varchar(500) DEFAULT NULL COMMENT '全国法院被执行人或被纳入失信人查询',
  `referee_network_info` varchar(500) DEFAULT NULL COMMENT '裁判文书网',
  `zhongdeng_info` varchar(500) DEFAULT NULL COMMENT '中登网登记及抵押登记',
  `credit_report` varchar(500) DEFAULT NULL COMMENT '信用报告',
  `other` varchar(500) DEFAULT NULL COMMENT '其他',
  `create_by` bigint(20) DEFAULT NULL COMMENT '创建人、发起人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` bigint(20) DEFAULT NULL COMMENT '最后更新人id',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='租后检查外部查询承租人/担保人信息';

CREATE TABLE `after_lease_check_project_report_finance` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `check_plan_project_id` bigint(20) NOT NULL COMMENT '检查计划项目表主键id',
  `client_id` bigint(20) NOT NULL COMMENT '客户id',
  `subject_type` varchar(50) NOT NULL DEFAULT '' COMMENT '报表类型',
  `query_json` text COMMENT '查询条件json',
  `data_json` text COMMENT '查询结果json',
  `create_by` bigint(20) DEFAULT NULL COMMENT '创建人、发起人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` bigint(20) DEFAULT NULL COMMENT '最后更新人id',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_plan_project_client_subjecttype` (`check_plan_project_id`,`client_id`,`subject_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='租后检查报告财务报表快照数据表';

INSERT INTO `after_lease_check_project_report_template` (`report_type`, `area_type`, `group_name`, `code`, `title`, `content_input_type`, `content_input_option`, `order_num`)
VALUES
	('PUBLIC', 'CONTENT', '当地区域经济情况', 'P_C_1_01', '承租人所在区域GDP、一般公共预算收入是否较上一年度下滑超过20%', 'radio', '[{\"label\":\"是\",\"value\":\"1\"},{\"label\":\"否\",\"value\":\"0\"},{\"label\":\"不适用\",\"value\":\"-1\"}]', 0),
	('PUBLIC', 'CONTENT', '当地区域经济情况', 'P_C_1_02', '承租人所在区域内是否有融资主体出现违约行为', 'radio', '[{\"label\":\"是\",\"value\":\"1\"},{\"label\":\"否\",\"value\":\"0\"},{\"label\":\"不适用\",\"value\":\"-1\"}]', 10),
	('PUBLIC', 'CONTENT', '承租人经营情况', 'P_C_2_01', '承租人本期是否出现变更股东、注册资本、经营范围、法定代表人等情况', 'radio', '[{\"label\":\"是\",\"value\":\"1\"},{\"label\":\"否\",\"value\":\"0\"},{\"label\":\"不适用\",\"value\":\"-1\"}]', 20),
	('PUBLIC', 'CONTENT', '承租人经营情况', 'P_C_2_02', '承租人本期是否出现住所、通讯地址、联系人、联系方式变更', 'radio', '[{\"label\":\"是\",\"value\":\"1\"},{\"label\":\"否\",\"value\":\"0\"},{\"label\":\"不适用\",\"value\":\"-1\"}]', 30),
	('PUBLIC', 'CONTENT', '承租人经营情况', 'P_C_2_03', '承租人主要职能定位及经营业务是否发生重大变化', 'radio', '[{\"label\":\"是\",\"value\":\"1\"},{\"label\":\"否\",\"value\":\"0\"},{\"label\":\"不适用\",\"value\":\"-1\"}]', 40),
	('PUBLIC', 'CONTENT', '承租人经营情况', 'P_C_2_04', '承租人融资渠道是否通畅', 'radio', '[{\"label\":\"是\",\"value\":\"1\"},{\"label\":\"否\",\"value\":\"0\"},{\"label\":\"不适用\",\"value\":\"-1\"}]', 50),
	('PUBLIC', 'CONTENT', '承租人经营情况', 'P_C_2_05', '是否存在被关闭或划转兼并的明确安排', 'radio', '[{\"label\":\"是\",\"value\":\"1\"},{\"label\":\"否\",\"value\":\"0\"},{\"label\":\"不适用\",\"value\":\"-1\"}]', 60),
	('PUBLIC', 'CONTENT', '担保人经营情况', 'P_C_3_01', '担保人本期是否出现变更股东、注册资本、经营范围、法定代表人等情况', 'radio', '[{\"label\":\"是\",\"value\":\"1\"},{\"label\":\"否\",\"value\":\"0\"},{\"label\":\"不适用\",\"value\":\"-1\"}]', 70),
	('PUBLIC', 'CONTENT', '担保人经营情况', 'P_C_3_02', '担保人本期是否出现住所、通讯地址、联系人、联系方式变更', 'radio', '[{\"label\":\"是\",\"value\":\"1\"},{\"label\":\"否\",\"value\":\"0\"},{\"label\":\"不适用\",\"value\":\"-1\"}]', 80),
	('PUBLIC', 'CONTENT', '担保人经营情况', 'P_C_3_03', '担保人主要职能定位及经营业务是否发生重大变化', 'radio', '[{\"label\":\"是\",\"value\":\"1\"},{\"label\":\"否\",\"value\":\"0\"},{\"label\":\"不适用\",\"value\":\"-1\"}]', 90),
	('PUBLIC', 'CONTENT', '担保人经营情况', 'P_C_3_04', '担保人融资渠道是否通畅', 'radio', '[{\"label\":\"是\",\"value\":\"1\"},{\"label\":\"否\",\"value\":\"0\"},{\"label\":\"不适用\",\"value\":\"-1\"}]', 100),
	('PUBLIC', 'CONTENT', '担保人经营情况', 'P_C_3_05', '是否存在被关闭或划转兼并的明确安排', 'radio', '[{\"label\":\"是\",\"value\":\"1\"},{\"label\":\"否\",\"value\":\"0\"},{\"label\":\"不适用\",\"value\":\"-1\"}]', 110),
	('PUBLIC', 'CONTENT', '租赁物', 'P_C_4_01', '承租人是否将租赁物进行再次销售、转让', 'radio', '[{\"label\":\"是\",\"value\":\"1\"},{\"label\":\"否\",\"value\":\"0\"},{\"label\":\"不适用\",\"value\":\"-1\"}]', 120),
	('PUBLIC', 'CONTENT', '租赁物', 'P_C_4_02', '承租人是否将租赁物进行了转租', 'radio', '[{\"label\":\"是\",\"value\":\"1\"},{\"label\":\"否\",\"value\":\"0\"},{\"label\":\"不适用\",\"value\":\"-1\"}]', 130),
	('PUBLIC', 'CONTENT', '租赁物', 'P_C_4_03', '承租人是否将租赁物进行再次抵押、质押', 'radio', '[{\"label\":\"是\",\"value\":\"1\"},{\"label\":\"否\",\"value\":\"0\"},{\"label\":\"不适用\",\"value\":\"-1\"}]', 140),
	('PUBLIC', 'CONTENT', '租赁物', 'P_C_4_04', '承租人是否将租赁物进行了投资入股、抵偿', 'radio', '[{\"label\":\"是\",\"value\":\"1\"},{\"label\":\"否\",\"value\":\"0\"},{\"label\":\"不适用\",\"value\":\"-1\"}]', 150),
	('PUBLIC', 'CONTENT', '租赁物', 'P_C_4_05', '承租人是否将租赁物进行诉讼担保、是否对租赁物进行了保全担保等处置行为', 'radio', '[{\"label\":\"是\",\"value\":\"1\"},{\"label\":\"否\",\"value\":\"0\"},{\"label\":\"不适用\",\"value\":\"-1\"}]', 160),
	('PUBLIC', 'CONTENT', '租赁物', 'P_C_4_06', '承租人是否以其他任何方式进行了侵害出租人对租赁设备的所有权的行为', 'radio', '[{\"label\":\"是\",\"value\":\"1\"},{\"label\":\"否\",\"value\":\"0\"},{\"label\":\"不适用\",\"value\":\"-1\"}]', 170),
	('PUBLIC', 'CONTENT', '租赁物', 'P_C_4_07', '租赁物是否能够正常使用', 'radio', '[{\"label\":\"是\",\"value\":\"1\"},{\"label\":\"否\",\"value\":\"0\"},{\"label\":\"不适用\",\"value\":\"-1\"}]', 180),
	('PUBLIC', 'CONTENT', '租赁物', 'P_C_4_08', '租赁物是否发生过升级换代、改造', 'radio', '[{\"label\":\"是\",\"value\":\"1\"},{\"label\":\"否\",\"value\":\"0\"},{\"label\":\"不适用\",\"value\":\"-1\"}]', 190),
	('PUBLIC', 'CONTENT', '租赁物', 'P_C_4_09', '租赁物的位置是否被移动', 'radio', '[{\"label\":\"是\",\"value\":\"1\"},{\"label\":\"否\",\"value\":\"0\"},{\"label\":\"不适用\",\"value\":\"-1\"}]', 200),
	('PUBLIC', 'CONTENT', '租赁物', 'P_C_4_10', '租赁物是否发生过重大停产停运、重大故障、维修情况', 'radio', '[{\"label\":\"是\",\"value\":\"1\"},{\"label\":\"否\",\"value\":\"0\"},{\"label\":\"不适用\",\"value\":\"-1\"}]', 210),
	('PUBLIC', 'SUMMARY', '检查总结', 'P_S_1_01', '以上检查事项异常说明', 'textArea', NULL, 0),
	('PUBLIC', 'SUMMARY', '检查总结', 'P_S_1_02', '有权机构审批意见未落实事项', 'textArea', NULL, 10),
	('PUBLIC', 'SUMMARY', '检查总结', 'P_S_1_03', '其他重要跟踪事项', 'textArea', NULL, 20),
	('NON_PUBLIC', 'CONTENT', '有权机构审批意见落实情况', 'NP_C_1_01', '有权机构审批意见落实情况', 'textArea', NULL, 0),
	('NON_PUBLIC', 'CONTENT', '客户经营情况分析', 'NP_C_2_01', '主体资格分析', 'textArea', NULL, 10),
	('NON_PUBLIC', 'CONTENT', '客户经营情况分析', 'NP_C_2_02', '行业分析', 'textArea', NULL, 20),
	('NON_PUBLIC', 'CONTENT', '客户经营情况分析', 'NP_C_2_03', '财务分析', 'textArea', NULL, 30),
	('NON_PUBLIC', 'CONTENT', '客户经营情况分析', 'NP_C_2_04', '经营状况分析', 'textArea', NULL, 40),
	('NON_PUBLIC', 'CONTENT', '客户经营情况分析', 'NP_C_2_05', '其它情况搜集与分析', 'textArea', NULL, 50),
	('NON_PUBLIC', 'CONTENT', '客户经营情况分析', 'NP_C_2_06', '租赁物分析', 'textArea', NULL, 60),
	('NON_PUBLIC', 'CONTENT', '客户经营情况分析', 'NP_C_2_07', '租赁资金使用情况', 'textArea', NULL, 70),
	('NON_PUBLIC', 'CONTENT', '第二还款来源分析', 'NP_C_3_01', '担保人分析', 'textArea', NULL, 80),
	('NON_PUBLIC', 'CONTENT', '第二还款来源分析', 'NP_C_3_02', '抵质押物分析', 'textArea', NULL, 90),
	('NON_PUBLIC', 'SUMMARY', '检查总结', 'NP_S_1_01', '风险信号及重大事项、风险防范措施', 'textArea', NULL, 0),
	('NON_PUBLIC', 'SUMMARY', '检查总结', 'NP_S_1_02', '检查分析与检查结果', 'textArea', NULL, 10),
	('LOW_RISK', 'CONTENT', '有权机构审批意见落实情况', 'LR_C_1_01', '有权机构审批意见落实情况', 'textArea', NULL, 0),
	('LOW_RISK', 'CONTENT', '客户经营分析', 'LR_C_2_01', '抵质押物是否合规、合法以及有效', 'textArea', NULL, 10),
	('LOW_RISK', 'CONTENT', '客户经营分析', 'LR_C_2_02', '抵质押物是否存在被查封等情况', 'textArea', NULL, 20),
	('LOW_RISK', 'CONTENT', '客户经营分析', 'LR_C_2_03', '承租人或者担保人是否存在重大诉讼等情况', 'textArea', NULL, 30),
	('LOW_RISK', 'SUMMARY', '检查总结', 'LR_S_1_01', '检查分析与检查结果', 'textArea', NULL, 40),
	('NON_PUBLIC', 'EXTRA_CONTENT', NULL, 'NP_EC_01', '一、承租人是否将租赁物进行再次销售', NULL, NULL, 0),
	('NON_PUBLIC', 'EXTRA_CONTENT', NULL, 'NP_EC_02', '二、承租人是否将租赁物进行再次转让', NULL, NULL, 10),
	('NON_PUBLIC', 'EXTRA_CONTENT', NULL, 'NP_EC_03', '三、承租人是否将租赁物进行了转租', NULL, NULL, 20),
	('NON_PUBLIC', 'EXTRA_CONTENT', NULL, 'NP_EC_04', '四、承租人是否将租赁物进行再次抵押', NULL, NULL, 30),
	('NON_PUBLIC', 'EXTRA_CONTENT', NULL, 'NP_EC_05', '五、承租人是否将租赁物进行再次质押', NULL, NULL, 40),
	('NON_PUBLIC', 'EXTRA_CONTENT', NULL, 'NP_EC_06', '六、承租人是否将租赁物进行了投资入股', NULL, NULL, 50),
	('NON_PUBLIC', 'EXTRA_CONTENT', NULL, 'NP_EC_07', '七、承租人是否将租赁物用于抵偿', NULL, NULL, 60),
	('NON_PUBLIC', 'EXTRA_CONTENT', NULL, 'NP_EC_08', '八、承租人是否将租赁物进行诉讼担保', NULL, NULL, 70),
	('NON_PUBLIC', 'EXTRA_CONTENT', NULL, 'NP_EC_09', '九、承租人是否对租赁物进行了保全担保等处置行为', NULL, NULL, 80),
	('NON_PUBLIC', 'EXTRA_CONTENT', NULL, 'NP_EC_10', '十、承租人是否以其他任何方式进行了侵害出租人对租赁设备的所有权的行为', NULL, NULL, 90),
	('NON_PUBLIC', 'EXTRA_CONTENT', NULL, 'NP_EC_11', '十一、租赁物是否能够正常使用', NULL, NULL, 100),
	('NON_PUBLIC', 'EXTRA_CONTENT', NULL, 'NP_EC_12', '十二、租赁物是否发生过重大停产停运、重大故障、维修情况', NULL, NULL, 110),
	('NON_PUBLIC', 'EXTRA_CONTENT', NULL, 'NP_EC_13', '十三、租赁物是否发生过升级换代、改造（如果选“是”，需提供改造方案）', NULL, NULL, 120),
	('NON_PUBLIC', 'EXTRA_CONTENT', NULL, 'NP_EC_14', '十四、承租人是否对租赁物定期进行保养（如果选“是”，需提供保养、维修方案和记录）', NULL, NULL, 130),
	('NON_PUBLIC', 'EXTRA_CONTENT', NULL, 'NP_EC_15', '十五、租赁物的位置是否被移动（如果选“是”，需提供解释说明）', NULL, NULL, 140),
	('NON_PUBLIC', 'EXTRA_CONTENT', NULL, 'NP_EC_16', '十六、承租人是否对租赁物计提折旧（如果选“否”，需提供解释说明）', NULL, NULL, 150),
	('NON_PUBLIC', 'EXTRA_CONTENT', NULL, 'NP_EC_17', '十七、承租人是否在租赁设备的显著位置设置出租人为租赁设备所有权人的标志，并保证其不被移走或遮盖', NULL, NULL, 160),
	('NON_PUBLIC', 'EXTRA_CONTENT', NULL, 'NP_EC_18', '十八、承租人所购买的原料本月/季是否出现上涨10%的价格波动（如果选“是”，需说明具体原因，对企业造成的影响及应对措施）', NULL, NULL, 170),
	('NON_PUBLIC', 'EXTRA_CONTENT', NULL, 'NP_EC_19', '十九、承租人所销售的产品本月/季是否出现下跌10%的价格波动（如果选“是”，需说明具体原因，对企业造成的影响及应对措施）', NULL, NULL, 180),
	('NON_PUBLIC', 'EXTRA_CONTENT', NULL, 'NP_EC_20', '二十、承租人的供货商本月/季是否出现违约情况（如果选“是”，需说明具体原因，对企业造成的影响及应对措施）', NULL, NULL, 190),
	('NON_PUBLIC', 'EXTRA_CONTENT', NULL, 'NP_EC_21', '二十一、承租人的客户本月/季是否出现违约情况（如果选“是”，需说明具体原因，对企业造成的影响及应对措施）', NULL, NULL, 200),
	('NON_PUBLIC', 'EXTRA_CONTENT', NULL, 'NP_EC_22', '二十二、承租人是否有进一步按约偿还租金的意愿（如果选“否”，需说明具体原因）', NULL, NULL, 210),
	('NON_PUBLIC', 'EXTRA_CONTENT', NULL, 'NP_EC_23', '二十三、承租人本月/季是否出现变更注册资本、住所、通讯地址、经营范围、法定代表人等情况（如果选“是”，需说明具体原因，对企业造成的影响及应对措施）', NULL, NULL, 220),
	('NON_PUBLIC', 'EXTRA_CONTENT', NULL, 'NP_EC_24', '二十四、承租人本月/季是否出现转让涉及到其总资产30%以上的资产的行为（如果选“是”，需说明具体原因，对企业造成的影响及应对措施）', NULL, NULL, 230),
	('NON_PUBLIC', 'EXTRA_CONTENT', NULL, 'NP_EC_25', '二十五、承租人本月/季是否出现重大经济纠纷、诉讼、破产、财务状况恶化等情况（如果选“是”，需说明具体原因，对企业造成的影响及应对措施）', NULL, NULL, 240),
	('NON_PUBLIC', 'EXTRA_CONTENT', NULL, 'NP_EC_26', '二十六、承租人本月/季是否发生歇业、解散、停业整顿、被吊销营业执照或被撤销等情况（如果选“是”，需说明具体原因，对企业造成的影响及应对措施）', NULL, NULL, 250),
	('NON_PUBLIC', 'EXTRA_CONTENT', NULL, 'NP_EC_27', '二十七、担保人本月/季是否出现转让涉及到其总资产30%以上的资产的行为（如果选“是”，需说明具体原因，对企业造成的影响及应对措施）', NULL, NULL, 260),
	('NON_PUBLIC', 'EXTRA_CONTENT', NULL, 'NP_EC_28', '二十八、担保人本月/季是否出现变更注册资本、住所、通讯地址、经营范围、法定代表人等情况（如果选“是”，需说明具体原因，对企业造成的影响及应对措施）', NULL, NULL, 270),
	('NON_PUBLIC', 'EXTRA_CONTENT', NULL, 'NP_EC_29', '二十九、担保人本月/季是否出现重大经济纠纷、诉讼、破产、财务状况恶化等情况（如果选“是”，需说明具体原因，对企业造成的影响及应对措施）', NULL, NULL, 280),
	('NON_PUBLIC', 'EXTRA_CONTENT', NULL, 'NP_EC_30', '三十、担保人本月/季是否发生歇业、解散、停业整顿、被吊销营业执照或被撤销等情况（如果选“是”，需说明具体原因，对企业造成的影响及应对措施）', NULL, NULL, 290);
