CREATE TABLE `fund_receipt_account` (
    `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键id',
    `receipt_repay_id` bigint(20) DEFAULT NULL COMMENT '收付款id',
    `client_name` varchar(200) DEFAULT NULL COMMENT '客户名称',
    `account_name` varchar(200) DEFAULT NULL COMMENT '账户名称',
    `account_num` varchar(30) DEFAULT NULL COMMENT '银行账号',
    `account_address` varchar(200) DEFAULT NULL COMMENT '开户行',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `create_by` bigint(20) DEFAULT NULL COMMENT '创建人id',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `update_by` bigint(20) DEFAULT NULL,
    PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COMMENT='资金管理-融资管理-对方收款账户';

CREATE TABLE `fund_receipt_account_lib` (
    `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键id',
    `receipt_repay_id` bigint(20) DEFAULT NULL COMMENT '收付款id',
    `client_name` varchar(200) DEFAULT NULL COMMENT '客户名称',
    `account_name` varchar(200) DEFAULT NULL COMMENT '账户名称',
    `account_num` varchar(30) DEFAULT NULL COMMENT '银行账号',
    `account_address` varchar(200) DEFAULT NULL COMMENT '开户行',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `create_by` bigint(20) DEFAULT NULL COMMENT '创建人id',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `update_by` bigint(20) DEFAULT NULL,
    `version` varchar(40) NOT NULL COMMENT '版本号',
    `origin_id` bigint(20) NOT NULL COMMENT '临时数据表id 需要用来比对数据 或者 流程拒绝时全量回写',
    `data_create_time` datetime DEFAULT NULL,
    `data_create_by` bigint(20) DEFAULT NULL,
    `data_update_time` datetime DEFAULT NULL,
    `data_update_by` bigint(20) DEFAULT NULL,
    `version_type` tinyint(4) DEFAULT '1' COMMENT '版本标志，0无效，1有效...业务自扩展',
    PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COMMENT='资金管理-融资管理-对方收款账户版本';

CREATE TABLE `fund_receipt_repay_base_info` (
    `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
    `receipt_repay_code` varchar(20) DEFAULT NULL COMMENT '收付款编号',
    `financing_id` bigint(20) DEFAULT NULL COMMENT '融资id',
    `financing_amount` bigint(20) DEFAULT NULL COMMENT '冗余的融资金额',
    `next_repay_date` date DEFAULT NULL COMMENT '下次还款日期',
    `financing_org_id` bigint(20) DEFAULT NULL COMMENT '融资机构id',
    `financing_version` varchar(30) DEFAULT NULL,
    `receipt_repay_state` varchar(30) DEFAULT NULL COMMENT '收付款状态',
    `process_state` varchar(30) DEFAULT NULL COMMENT '流程状态',
    `fund_manager` bigint(20) DEFAULT NULL COMMENT '资金经理',
    `create_by` bigint(20) DEFAULT NULL COMMENT '创建人、发起人',
    `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_by` bigint(20) DEFAULT NULL COMMENT '最后更新人id',
    `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `remark` varchar(500) DEFAULT NULL,
    PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COMMENT='收付款';

CREATE TABLE `fund_receipt_repay_base_info_lib` (
    `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
    `receipt_repay_code` varchar(20) DEFAULT NULL COMMENT '收付款编号',
    `financing_id` bigint(20) DEFAULT NULL COMMENT '融资id',
    `financing_amount` bigint(20) DEFAULT NULL COMMENT '冗余的融资金额',
    `next_repay_date` date DEFAULT NULL COMMENT '下次还款日期',
    `financing_org_id` bigint(20) DEFAULT NULL COMMENT '融资机构id',
    `receipt_repay_state` varchar(30) DEFAULT NULL COMMENT '收付款状态',
    `process_state` varchar(30) DEFAULT NULL COMMENT '流程状态',
    `fund_manager` bigint(20) DEFAULT NULL COMMENT '资金经理',
    `financing_version` varchar(30) DEFAULT NULL,
    `remark` varchar(500) DEFAULT NULL,
    `create_by` bigint(20) DEFAULT NULL COMMENT '创建人、发起人',
    `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_by` bigint(20) DEFAULT NULL COMMENT '最后更新人id',
    `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `version` varchar(40) NOT NULL COMMENT '版本号',
    `origin_id` bigint(20) NOT NULL COMMENT '临时数据表id 需要用来比对数据 或者 流程拒绝时全量回写',
    `data_create_time` datetime DEFAULT NULL,
    `data_create_by` bigint(20) DEFAULT NULL,
    `data_update_time` datetime DEFAULT NULL,
    `data_update_by` bigint(20) DEFAULT NULL,
    `version_type` tinyint(4) DEFAULT '1' COMMENT '版本标志，0无效，1有效...业务自扩展',
    PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COMMENT='收付款';

CREATE TABLE `fund_receipt_repay_batch` (
    `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
    `process_state` varchar(30) DEFAULT NULL COMMENT '流程id',
    `remark` varchar(255) DEFAULT NULL COMMENT '备注',
    `create_by` bigint(20) DEFAULT NULL COMMENT '创建人、发起人',
    `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_by` bigint(20) DEFAULT NULL COMMENT '最后更新人id',
    `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;

CREATE TABLE `fund_receipt_repay_borrowing` (
    `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
    `receipt_repay_id` bigint(20) DEFAULT NULL COMMENT '收付款id',
    `cash_flow_code` varchar(30) DEFAULT NULL COMMENT '现金流编号',
    `term` int(11) DEFAULT NULL COMMENT '期项',
    `principal` bigint(20) DEFAULT NULL COMMENT '本金',
    `write_off_state` varchar(30) DEFAULT NULL COMMENT '核销状态',
    `actual_loan_date` date DEFAULT NULL COMMENT '实际贷款日期',
    `remark` varchar(255) DEFAULT NULL COMMENT '备注',
    `create_by` bigint(20) DEFAULT NULL COMMENT '创建人、发起人',
    `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_by` bigint(20) DEFAULT NULL COMMENT '最后更新人id',
    `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;

CREATE TABLE `fund_receipt_repay_borrowing_lib` (
    `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
    `receipt_repay_id` bigint(20) DEFAULT NULL COMMENT '收付款id',
    `cash_flow_code` varchar(30) DEFAULT NULL COMMENT '现金流编号',
    `term` int(11) DEFAULT NULL COMMENT '期项',
    `principal` bigint(20) DEFAULT NULL COMMENT '本金',
    `write_off_state` varchar(30) DEFAULT NULL COMMENT '核销状态',
    `actual_loan_date` date DEFAULT NULL COMMENT '实际贷款日期',
    `remark` varchar(255) DEFAULT NULL COMMENT '备注',
    `create_by` bigint(20) DEFAULT NULL COMMENT '创建人、发起人',
    `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_by` bigint(20) DEFAULT NULL COMMENT '最后更新人id',
    `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `version` varchar(40) NOT NULL COMMENT '版本号',
    `origin_id` bigint(20) NOT NULL COMMENT '临时数据表id 需要用来比对数据 或者 流程拒绝时全量回写',
    `data_create_time` datetime DEFAULT NULL,
    `data_create_by` bigint(20) DEFAULT NULL,
    `data_update_time` datetime DEFAULT NULL,
    `data_update_by` bigint(20) DEFAULT NULL,
    `version_type` tinyint(4) DEFAULT '1' COMMENT '版本标志，0无效，1有效...业务自扩展',
    PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;

CREATE TABLE `fund_receipt_repay_cash_deposit` (
    `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
    `receipt_repay_id` bigint(20) DEFAULT NULL COMMENT '收付款id',
    `cash_flow_code` varchar(30) DEFAULT NULL COMMENT '现金流编号',
    `deposit_cash_flow_type` varchar(30) DEFAULT NULL COMMENT '费用类型',
    `amount` bigint(20) DEFAULT NULL COMMENT '金额',
    `write_off_state` varchar(30) DEFAULT NULL COMMENT '核销状态',
    `paid_amount` bigint(20) DEFAULT NULL COMMENT '本月支付金额',
    `receipt_amount` bigint(20) DEFAULT NULL COMMENT '本月收入金额',
    `remark` varchar(255) DEFAULT NULL COMMENT '备注',
    `create_by` bigint(20) DEFAULT NULL COMMENT '创建人、发起人',
    `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_by` bigint(20) DEFAULT NULL COMMENT '最后更新人id',
    `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;

CREATE TABLE `fund_receipt_repay_cash_deposit_lib` (
    `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
    `receipt_repay_id` bigint(20) DEFAULT NULL COMMENT '收付款id',
    `cash_flow_code` varchar(30) DEFAULT NULL COMMENT '现金流编号',
    `deposit_cash_flow_type` varchar(30) DEFAULT NULL COMMENT '费用类型',
    `amount` bigint(20) DEFAULT NULL COMMENT '金额',
    `write_off_state` varchar(30) DEFAULT NULL COMMENT '核销状态',
    `paid_amount` bigint(20) DEFAULT NULL COMMENT '本月支付金额',
    `receipt_amount` bigint(20) DEFAULT NULL COMMENT '本月收入金额',
    `remark` varchar(255) DEFAULT NULL COMMENT '备注',
    `create_by` bigint(20) DEFAULT NULL COMMENT '创建人、发起人',
    `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_by` bigint(20) DEFAULT NULL COMMENT '最后更新人id',
    `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `version` varchar(40) NOT NULL COMMENT '版本号',
    `origin_id` bigint(20) NOT NULL COMMENT '临时数据表id 需要用来比对数据 或者 流程拒绝时全量回写',
    `data_create_time` datetime DEFAULT NULL,
    `data_create_by` bigint(20) DEFAULT NULL,
    `data_update_time` datetime DEFAULT NULL,
    `data_update_by` bigint(20) DEFAULT NULL,
    `version_type` tinyint(4) DEFAULT '1' COMMENT '版本标志，0无效，1有效...业务自扩展',
    PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;

CREATE TABLE `fund_receipt_repay_cash_flow` (
    `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
    `receipt_repay_id` bigint(20) DEFAULT NULL COMMENT '收付款id',
    `financing_id` bigint(20) DEFAULT NULL COMMENT '融资id',
    `cash_flow_id` bigint(20) DEFAULT NULL COMMENT '现金流id',
    `cash_flow_code` varchar(60) DEFAULT NULL COMMENT '现金流编号',
    `repay_date` date DEFAULT NULL COMMENT '还款日期',
    `phase` int(10) DEFAULT NULL COMMENT '还款期项',
    `principle_amount` bigint(20) DEFAULT NULL COMMENT '本金',
    `interest_amount` bigint(20) DEFAULT NULL COMMENT '利息',
    `repay_amount` bigint(20) DEFAULT NULL COMMENT '应还总额',
    `remaining_principle_amount` bigint(20) DEFAULT NULL COMMENT '剩余未还本金',
    `write_off_state` varchar(30) DEFAULT NULL COMMENT '核销状态',
    `remark` varchar(255) DEFAULT NULL COMMENT '备注',
    `approval_pass_date` date DEFAULT NULL COMMENT '审批通过时间（用于计算累加额）',
    `create_by` bigint(20) DEFAULT NULL COMMENT '创建人、发起人',
    `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_by` bigint(20) DEFAULT NULL COMMENT '最后更新人id',
    `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;

CREATE TABLE `fund_receipt_repay_cash_flow_lib` (
    `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
    `receipt_repay_id` bigint(20) DEFAULT NULL COMMENT '收付款id',
    `financing_id` bigint(20) DEFAULT NULL COMMENT '融资id',
    `cash_flow_id` bigint(20) DEFAULT NULL COMMENT '现金流id',
    `cash_flow_code` varchar(60) DEFAULT NULL COMMENT '现金流编号',
    `repay_date` date DEFAULT NULL COMMENT '还款日期',
    `phase` int(10) DEFAULT NULL COMMENT '还款期项',
    `principle_amount` bigint(20) DEFAULT NULL COMMENT '本金',
    `interest_amount` bigint(20) DEFAULT NULL COMMENT '利息',
    `repay_amount` bigint(20) DEFAULT NULL COMMENT '应还总额',
    `remaining_principle_amount` bigint(20) DEFAULT NULL COMMENT '剩余未还本金',
    `write_off_state` varchar(30) DEFAULT NULL COMMENT '核销状态',
    `remark` varchar(255) DEFAULT NULL COMMENT '备注',
    `approval_pass_date` date DEFAULT NULL COMMENT '审批通过时间（用于计算累加额）',
    `create_by` bigint(20) DEFAULT NULL COMMENT '创建人、发起人',
    `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_by` bigint(20) DEFAULT NULL COMMENT '最后更新人id',
    `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `version` varchar(40) NOT NULL COMMENT '版本号',
    `origin_id` bigint(20) NOT NULL COMMENT '临时数据表id 需要用来比对数据 或者 流程拒绝时全量回写',
    `data_create_time` datetime DEFAULT NULL,
    `data_create_by` bigint(20) DEFAULT NULL,
    `data_update_time` datetime DEFAULT NULL,
    `data_update_by` bigint(20) DEFAULT NULL,
    `version_type` tinyint(4) DEFAULT '1' COMMENT '版本标志，0无效，1有效...业务自扩展',
    PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;

CREATE TABLE `fund_receipt_repay_expense` (
    `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
    `receipt_repay_id` bigint(20) DEFAULT NULL COMMENT '收付款id',
    `cash_flow_code` varchar(30) DEFAULT NULL COMMENT '现金流编号',
    `expense_type` varchar(30) DEFAULT NULL COMMENT '费用类型',
    `total_amount` bigint(20) DEFAULT NULL COMMENT '费用总金额',
    `total_paid_amount` bigint(20) DEFAULT NULL COMMENT '累计支付金额',
    `pay_amount` bigint(20) DEFAULT NULL COMMENT '本月支付金额',
    `write_off_state` varchar(30) DEFAULT NULL COMMENT '核销状态',
    `remark` varchar(255) DEFAULT NULL COMMENT '备注',
    `create_by` bigint(20) DEFAULT NULL COMMENT '创建人、发起人',
    `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_by` bigint(20) DEFAULT NULL COMMENT '最后更新人id',
    `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COMMENT='费用一览表';

CREATE TABLE `fund_receipt_repay_expense_lib` (
    `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
    `receipt_repay_id` bigint(20) DEFAULT NULL COMMENT '收付款id',
    `cash_flow_code` varchar(30) DEFAULT NULL COMMENT '现金流编号',
    `expense_type` varchar(30) DEFAULT NULL COMMENT '费用类型',
    `total_amount` bigint(20) DEFAULT NULL COMMENT '费用总金额',
    `total_paid_amount` bigint(20) DEFAULT NULL COMMENT '累计支付金额',
    `pay_amount` bigint(20) DEFAULT NULL COMMENT '本月支付金额',
    `write_off_state` varchar(30) DEFAULT NULL COMMENT '核销状态',
    `remark` varchar(255) DEFAULT NULL COMMENT '备注',
    `create_by` bigint(20) DEFAULT NULL COMMENT '创建人、发起人',
    `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_by` bigint(20) DEFAULT NULL COMMENT '最后更新人id',
    `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `version` varchar(40) NOT NULL COMMENT '版本号',
    `origin_id` bigint(20) NOT NULL COMMENT '临时数据表id 需要用来比对数据 或者 流程拒绝时全量回写',
    `data_create_time` datetime DEFAULT NULL,
    `data_create_by` bigint(20) DEFAULT NULL,
    `data_update_time` datetime DEFAULT NULL,
    `data_update_by` bigint(20) DEFAULT NULL,
    `version_type` tinyint(4) DEFAULT '1' COMMENT '版本标志，0无效，1有效...业务自扩展',
    PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COMMENT='费用一览表';

CREATE TABLE `fund_receipt_repay_plan` (
    `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
    `receipt_repay_id` bigint(20) DEFAULT NULL COMMENT '收付款id',
    `batch_id` bigint(20) DEFAULT NULL,
    `receipt_repay_code` varchar(20) DEFAULT NULL COMMENT '收付款编号',
    `financing_org_name` varchar(64) DEFAULT NULL COMMENT '融资机构名称',
    `receipt_repay_version` varchar(20) DEFAULT NULL COMMENT '资金收付款版本',
    `financing_amount` bigint(20) DEFAULT NULL COMMENT '融资金额（元）',
    `paid_principal` bigint(20) DEFAULT NULL COMMENT '累计已还本金（元）',
    `paid_interest` bigint(20) DEFAULT NULL COMMENT '累计已还利息（元）',
    `supporting_project_json` varchar(200) DEFAULT NULL COMMENT '配套项目',
    `pledge_contrac_code_json` json DEFAULT NULL COMMENT '质押合同编号',
    `borrowing_date` date DEFAULT NULL COMMENT '借款日期',
    `expiration_date` date DEFAULT NULL COMMENT '到期日期',
    `planed_repay_amount` bigint(20) DEFAULT NULL COMMENT '本月计划还款合计（元）',
    `planed_repay_principal` bigint(20) DEFAULT NULL COMMENT '本月计划还款本金（元）',
    `planed_repay_interest` bigint(20) DEFAULT NULL COMMENT '本月计划还款利息（元）',
    `planed_repay_principle_date` date DEFAULT NULL COMMENT '计划还本日\n',
    `planed_repay_interest_date` date DEFAULT NULL COMMENT '计划还息日\n',
    `create_by` bigint(20) DEFAULT NULL COMMENT '创建人、发起人',
    `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_by` bigint(20) DEFAULT NULL COMMENT '最后更新人id',
    `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COMMENT='还款计划';

CREATE TABLE `fund_repay_account` (
    `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键id',
    `receipt_repay_id` bigint(20) DEFAULT NULL COMMENT '收付款id',
    `bank_account_id` bigint(20) DEFAULT NULL COMMENT '基础数据-我方银行账户id',
    `account_bank` varchar(255) DEFAULT NULL COMMENT '支行名称',
    `account_number` varchar(50) DEFAULT NULL COMMENT '账号',
    `account_type` varchar(20) DEFAULT NULL COMMENT '账户类型',
    `account_opening_date` date DEFAULT NULL COMMENT '开户时间',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `create_by` bigint(20) DEFAULT NULL COMMENT '创建人id',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `update_by` bigint(20) DEFAULT NULL,
    PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COMMENT='资金管理-融资管理-我方付款账户';

CREATE TABLE `fund_repay_account_lib` (
    `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键id',
    `receipt_repay_id` bigint(20) DEFAULT NULL COMMENT '收付款id',
    `bank_account_id` bigint(20) DEFAULT NULL COMMENT '基础数据-我方银行账户id',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `create_by` bigint(20) DEFAULT NULL COMMENT '创建人id',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `update_by` bigint(20) DEFAULT NULL,
    `version` varchar(40) NOT NULL COMMENT '版本号',
    `origin_id` bigint(20) NOT NULL COMMENT '临时数据表id 需要用来比对数据 或者 流程拒绝时全量回写',
    `data_create_time` datetime DEFAULT NULL,
    `data_create_by` bigint(20) DEFAULT NULL,
    `data_update_time` datetime DEFAULT NULL,
    `data_update_by` bigint(20) DEFAULT NULL,
    `version_type` tinyint(4) DEFAULT '1' COMMENT '版本标志，0无效，1有效...业务自扩展',
    `account_bank` varchar(255) DEFAULT NULL COMMENT '支行名称',
    `account_number` varchar(50) DEFAULT NULL COMMENT '账号',
    `account_type` varchar(20) DEFAULT NULL COMMENT '账户类型',
    `account_opening_date` date DEFAULT NULL COMMENT '开户时间 ',
    PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COMMENT='资金管理-融资管理-我方付款账户版本';