-- 对外融资信息表
CREATE TABLE association_external_financing
(
    id                     BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '自增主键',
    row_num                INT                 NOT NULL COMMENT '行号 | 同一批次数据，行号1开始进行递增（确认数据问题快速定位）',
    unif_soci_cred_code    VARCHAR(32)         NOT NULL COMMENT '企业统一社会信用代码',
    onum                   VARCHAR(128)                 DEFAULT NULL COMMENT '序号',
    loan_bal               DECIMAL(25, 8)               DEFAULT NULL COMMENT '借款余额 | 单位：万元',
    fin_busi_type_code     VARCHAR(64)                  DEFAULT NULL COMMENT '融资业务类型 | 数据字典：EVT00052',
    cptl_prov              VARCHAR(64)                  DEFAULT NULL COMMENT '资金提供方',
    fin_intr               DECIMAL(21, 8)               DEFAULT NULL COMMENT '融资利率',
    fin_loan_date          DATE                         DEFAULT NULL COMMENT '融资借款日期',
    fin_matu_date          DATE                         DEFAULT NULL COMMENT '融资到期日期',
    report_instance_id     VARCHAR(64)         NOT NULL COMMENT '报表实例编号 | 格式：UUID',
    report_instance_period VARCHAR(24)         NOT NULL COMMENT '报表实例周期 | 格式：YYYYQQ',
    batch_no               VARCHAR(4)          NOT NULL COMMENT '批次号 | 4位字符，根据月报/季报/年报的上报周期，同期数据重复上传时从0000开始递增，9999后重置',
    version                VARCHAR(128)        NOT NULL COMMENT '版本号 | 报表实例周期+版本号',
    op                     VARCHAR(16)         NOT NULL DEFAULT 'insert' COMMENT '操作标识 | 值域：insert/update',
    report_time            DATETIME            NOT NULL COMMENT '上报时间 | 数据文件上传时间',
    write_time             datetime            NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '写入时间 | 数据库写入时间',
    `create_time`          datetime            NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `create_by`            bigint(20)                   DEFAULT NULL COMMENT '创建人id',
    `update_time`          datetime            NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `update_by`            bigint(20)                   DEFAULT NULL COMMENT '更新人id',
    PRIMARY KEY (id)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4 COMMENT ='金融局报送-对外融资信息清单表';

-- 服务实体经济情况表
CREATE TABLE association_entity_economy_service
(
    id                      BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '自增主键',
    row_num                 INT(11)                      DEFAULT NULL COMMENT '行号 | 同一批次数据从1开始递增',
    unif_soci_cred_code     VARCHAR(32)         NOT NULL COMMENT '企业统一社会信用代码',
    tyag_leas_busi_amt_abop DECIMAL(25, 8)               DEFAULT NULL COMMENT '本年累计租赁业务金额_期初数(万元)',
    tyag_leas_busi_amt_aotc DECIMAL(25, 8)               DEFAULT NULL COMMENT '本年累计租赁业务金额_本期发生额(万元)',
    tyag_leas_busi_amt_aeop DECIMAL(25, 8)               DEFAULT NULL COMMENT '本年累计租赁业务金额_期末数(万元)',
    tyag_mnft_leas_amt_abop DECIMAL(25, 8)               DEFAULT NULL COMMENT '制造业租赁_期初数(万元)',
    tyag_mnft_leas_amt_aotc DECIMAL(25, 8)               DEFAULT NULL COMMENT '制造业租赁_发生额(万元)',
    tyag_mnft_leas_amt_aeop DECIMAL(25, 8)               DEFAULT NULL COMMENT '制造业租赁_期末数(万元)',
    tyag_indt_leas_amt_abop DECIMAL(25, 8)               DEFAULT NULL COMMENT '产业链租赁_期初数(万元)',
    tyag_indt_leas_amt_aotc DECIMAL(25, 8)               DEFAULT NULL COMMENT '产业链租赁_发生额(万元)',
    tyag_indt_leas_amt_aeop DECIMAL(25, 8)               DEFAULT NULL COMMENT '产业链租赁_期末数(万元)',
    tyag_cons_leas_amt_abop DECIMAL(25, 8)               DEFAULT NULL COMMENT '民生消费租赁_期初数(万元)',
    tyag_cons_leas_amt_aotc DECIMAL(25, 8)               DEFAULT NULL COMMENT '民生消费租赁_发生额(万元)',
    tyag_cons_leas_amt_aeop DECIMAL(25, 8)               DEFAULT NULL COMMENT '民生消费租赁_期末数(万元)',
    tyag_saty_leas_amt_abop DECIMAL(25, 8)               DEFAULT NULL COMMENT '科技金融租赁_期初数(万元)',
    tyag_saty_leas_amt_aotc DECIMAL(25, 8)               DEFAULT NULL COMMENT '科技金融租赁_发生额(万元)',
    tyag_saty_leas_amt_aeop DECIMAL(25, 8)               DEFAULT NULL COMMENT '科技金融租赁_期末数(万元)',
    tyag_gren_leas_amt_abop DECIMAL(25, 8)               DEFAULT NULL COMMENT '绿色金融租赁_期初数(万元)',
    tyag_gren_leas_amt_aotc DECIMAL(25, 8)               DEFAULT NULL COMMENT '绿色金融租赁_发生额(万元)',
    tyag_gren_leas_amt_aeop DECIMAL(25, 8)               DEFAULT NULL COMMENT '绿色金融租赁_期末数(万元)',
    tyag_icve_leas_amt_abop DECIMAL(25, 8)               DEFAULT NULL COMMENT '普惠金融租赁_期初数(万元)',
    tyag_icve_leas_amt_aotc DECIMAL(25, 8)               DEFAULT NULL COMMENT '普惠金融租赁_发生额(万元)',
    tyag_icve_leas_amt_aeop DECIMAL(25, 8)               DEFAULT NULL COMMENT '普惠金融租赁_期末数(万元)',
    tyag_pens_leas_amt_abop DECIMAL(25, 8)               DEFAULT NULL COMMENT '养老金融租赁_期初数(万元)',
    tyag_pens_leas_amt_aotc DECIMAL(25, 8)               DEFAULT NULL COMMENT '养老金融租赁_发生额(万元)',
    tyag_pens_leas_amt_aeop DECIMAL(25, 8)               DEFAULT NULL COMMENT '养老金融租赁_期末数(万元)',
    tyag_ocea_leas_amt_abop DECIMAL(25, 8)               DEFAULT NULL COMMENT '海洋金融租赁_期初数(万元)',
    tyag_ocea_leas_amt_aotc DECIMAL(25, 8)               DEFAULT NULL COMMENT '海洋金融租赁_发生额(万元)',
    tyag_ocea_leas_amt_aeop DECIMAL(25, 8)               DEFAULT NULL COMMENT '海洋金融租赁_期末数(万元)',
    tyag_open_leas_amt_abop DECIMAL(25, 8)               DEFAULT NULL COMMENT '开放金融租赁_期初数(万元)',
    tyag_open_leas_amt_aotc DECIMAL(25, 8)               DEFAULT NULL COMMENT '开放金融租赁_发生额(万元)',
    tyag_open_leas_amt_aeop DECIMAL(25, 8)               DEFAULT NULL COMMENT '开放金融租赁_期末数(万元)',
    tyag_serv_cust_num_abop INT(11)                      DEFAULT NULL COMMENT '服务客户数_期初数',
    tyag_serv_cust_num_aotc INT(11)                      DEFAULT NULL COMMENT '服务客户数_发生额',
    tyag_serv_cust_num_aeop INT(11)                      DEFAULT NULL COMMENT '服务客户数_期末数',
    oyag_leas_busi_amt_abop DECIMAL(25, 8)               DEFAULT NULL COMMENT '历年租赁金额_期初(万元)',
    oyag_leas_busi_amt_aotc DECIMAL(25, 8)               DEFAULT NULL COMMENT '历年租赁金额_发生(万元)',
    oyag_leas_busi_amt_aeop DECIMAL(25, 8)               DEFAULT NULL COMMENT '历年租赁金额_期末(万元)',
    oyag_serv_cust_num_abop INT(11)                      DEFAULT NULL COMMENT '历年客户数_期初',
    oyag_serv_cust_num_aotc INT(11)                      DEFAULT NULL COMMENT '历年客户数_发生',
    oyag_serv_cust_num_aeop INT(11)                      DEFAULT NULL COMMENT '历年客户数_期末',
    thsy_taxp_amt_abop      DECIMAL(25, 8)               DEFAULT NULL COMMENT '实缴税金_期初(万元)',
    thsy_taxp_amt_aotc      DECIMAL(25, 8)               DEFAULT NULL COMMENT '实缴税金_发生(万元)',
    thsy_taxp_amt_aeop      DECIMAL(25, 8)               DEFAULT NULL COMMENT '实缴税金_期末(万元)',
    incr_tax_abop           DECIMAL(25, 8)               DEFAULT NULL COMMENT '增值税_期初(万元)',
    incr_tax_aotc           DECIMAL(25, 8)               DEFAULT NULL COMMENT '增值税_发生(万元)',
    incr_tax_aeop           DECIMAL(25, 8)               DEFAULT NULL COMMENT '增值税_期末(万元)',
    corp_inct_abop          DECIMAL(25, 8)               DEFAULT NULL COMMENT '企业所得税_期初(万元)',
    corp_inct_aotc          DECIMAL(25, 8)               DEFAULT NULL COMMENT '企业所得税_发生(万元)',
    corp_inct_aeop          DECIMAL(25, 8)               DEFAULT NULL COMMENT '企业所得税_期末(万元)',
    oth_tax_abop            DECIMAL(25, 8)               DEFAULT NULL COMMENT '其他税金_期初(万元)',
    oth_tax_aotc            DECIMAL(25, 8)               DEFAULT NULL COMMENT '其他税金_发生(万元)',
    oth_tax_aeop            DECIMAL(25, 8)               DEFAULT NULL COMMENT '其他税金_期末(万元)',
    oty_taxp_amt_abop       DECIMAL(25, 8)               DEFAULT NULL COMMENT '历年税金_期初(万元)',
    oty_taxp_amt_aotc       DECIMAL(25, 8)               DEFAULT NULL COMMENT '历年税金_发生(万元)',
    oty_taxp_amt_aeop       DECIMAL(25, 8)               DEFAULT NULL COMMENT '历年税金_期末(万元)',
    ofbl_amt_abop           DECIMAL(25, 8)               DEFAULT NULL COMMENT '表外业务_期初(万元)',
    ofbl_amt_aotc           DECIMAL(25, 8)               DEFAULT NULL COMMENT '表外业务_发生(万元)',
    ofbl_amt_aeop           DECIMAL(25, 8)               DEFAULT NULL COMMENT '表外业务_期末(万元)',
    report_instance_id      VARCHAR(64)         NOT NULL COMMENT '报表实例ID | UUID',
    report_instance_period  VARCHAR(24)         NOT NULL COMMENT '报表周期 | YYYYQQ格式',
    batch_no                VARCHAR(4)          NOT NULL COMMENT '批次号 | 0000-9999',
    version                 VARCHAR(128)        NOT NULL COMMENT '版本号 | 周期+版本',
    op                      VARCHAR(16)         NOT NULL DEFAULT 'insert' COMMENT '操作标识 | insert/update',
    report_time             DATETIME            NOT NULL COMMENT '上报时间',
    write_time              datetime            NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '入库时间',
    `create_time`           datetime            NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `create_by`             bigint(20)                   DEFAULT NULL COMMENT '创建人id',
    `update_time`           datetime            NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `update_by`             bigint(20)                   DEFAULT NULL COMMENT '更新人id',
    PRIMARY KEY (id)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4 COMMENT ='实体经济服务数据表';

CREATE TABLE association_company_profit_statement
(
    id                     BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '自增主键',
    row_num                INT(11)             NOT NULL COMMENT '行号 | 同一批次数据从1开始递增',
    unif_soci_cred_code    VARCHAR(32)         NOT NULL COMMENT '企业统一社会信用代码',
    main_busi_incm_actm    DECIMAL(21, 8)               DEFAULT NULL COMMENT '主营业务收入_本季发生额(元)',
    main_busi_cost_actm    DECIMAL(21, 8)               DEFAULT NULL COMMENT '主营业务成本_本季发生额(元)',
    main_busi_tax_add_actm DECIMAL(21, 8)               DEFAULT NULL COMMENT '主营业务税金及附加_本季发生额(元)',
    main_busi_prof_actm    DECIMAL(21, 8)               DEFAULT NULL COMMENT '主营业务利润_本季发生额(元)',
    oth_busi_prof_actm     DECIMAL(21, 8)               DEFAULT NULL COMMENT '其他业务利润_本季发生额(元)',
    busi_fee_actm          DECIMAL(21, 8)               DEFAULT NULL COMMENT '营业费用_本季发生额(元)',
    mag_fee_actm           DECIMAL(21, 8)               DEFAULT NULL COMMENT '管理费用_本季发生额(元)',
    fin_fee_actm           DECIMAL(21, 8)               DEFAULT NULL COMMENT '财务费用_本季发生额(元)',
    ipoa_loss_actm         DECIMAL(21, 8)               DEFAULT NULL COMMENT '资产减值损失_本季发生额(元)',
    cred_decr_loss_actm    DECIMAL(21, 8)               DEFAULT NULL COMMENT '信用减值损失_本季发生额(元)',
    busi_prof_actm         DECIMAL(21, 8)               DEFAULT NULL COMMENT '营业利润_本季发生额(元)',
    ivsm_payf_actm         DECIMAL(21, 8)               DEFAULT NULL COMMENT '投资收益_本季发生额(元)',
    nopr_incm_actm         DECIMAL(21, 8)               DEFAULT NULL COMMENT '营业外收入_本季发生额(元)',
    nopr_pay_actm          DECIMAL(21, 8)               DEFAULT NULL COMMENT '营业外支出_本季发生额(元)',
    prof_gamt_actm         DECIMAL(21, 8)               DEFAULT NULL COMMENT '利润总额_本季发生额(元)',
    inct_fee_actm          DECIMAL(21, 8)               DEFAULT NULL COMMENT '所得税费用_本季发生额(元)',
    net_prof_actm          DECIMAL(21, 8)               DEFAULT NULL COMMENT '净利润_本季发生额(元)',
    main_busi_incm_tyag    DECIMAL(21, 8)               DEFAULT NULL COMMENT '主营业务收入_本年累计(元)',
    main_busi_cost_tyag    DECIMAL(21, 8)               DEFAULT NULL COMMENT '主营业务成本_本年累计(元)',
    main_busi_tax_add_tyag DECIMAL(21, 8)               DEFAULT NULL COMMENT '主营业务税金及附加_本年累计(元)',
    main_busi_prof_tyag    DECIMAL(21, 8)               DEFAULT NULL COMMENT '主营业务利润_本年累计(元)',
    oth_busi_prof_tyag     DECIMAL(21, 8)               DEFAULT NULL COMMENT '其他业务利润_本年累计(元)',
    busi_fee_tyag          DECIMAL(21, 8)               DEFAULT NULL COMMENT '营业费用_本年累计(元)',
    mag_fee_tyag           DECIMAL(21, 8)               DEFAULT NULL COMMENT '管理费用_本年累计(元)',
    fin_fee_tyag           DECIMAL(21, 8)               DEFAULT NULL COMMENT '财务费用_本年累计(元)',
    ipoa_loss_tyag         DECIMAL(21, 8)               DEFAULT NULL COMMENT '资产减值损失_本年累计(元)',
    cred_decr_loss_tyag    DECIMAL(21, 8)               DEFAULT NULL COMMENT '信用减值损失_本年累计(元)',
    busi_prof_tyag         DECIMAL(21, 8)               DEFAULT NULL COMMENT '营业利润_本年累计(元)',
    ivsm_payf_tyag         DECIMAL(21, 8)               DEFAULT NULL COMMENT '投资收益_本年累计(元)',
    nopr_incm_tyag         DECIMAL(21, 8)               DEFAULT NULL COMMENT '营业外收入_本年累计(元)',
    nopr_pay_tyag          DECIMAL(21, 8)               DEFAULT NULL COMMENT '营业外支出_本年累计(元)',
    prof_gamt_tyag         DECIMAL(21, 8)               DEFAULT NULL COMMENT '利润总额_本年累计(元)',
    inct_fee_tyag          DECIMAL(21, 8)               DEFAULT NULL COMMENT '所得税费用_本年累计(元)',
    net_prof_tyag          DECIMAL(21, 8)               DEFAULT NULL COMMENT '净利润_本年累计(元)',
    main_busi_incm_cply    DECIMAL(21, 8)               DEFAULT NULL COMMENT '主营业务收入_去年同期(元)',
    main_busi_cost_cply    DECIMAL(21, 8)               DEFAULT NULL COMMENT '主营业务成本_去年同期(元)',
    main_busi_tax_add_cply DECIMAL(21, 8)               DEFAULT NULL COMMENT '主营业务税金及附加_去年同期(元)',
    main_busi_prof_cply    DECIMAL(21, 8)               DEFAULT NULL COMMENT '主营业务利润_去年同期(元)',
    oth_busi_prof_cply     DECIMAL(21, 8)               DEFAULT NULL COMMENT '其他业务利润_去年同期(元)',
    busi_fee_cply          DECIMAL(21, 8)               DEFAULT NULL COMMENT '营业费用_去年同期(元)',
    mag_fee_cply           DECIMAL(21, 8)               DEFAULT NULL COMMENT '管理费用_去年同期(元)',
    fin_fee_cply           DECIMAL(21, 8)               DEFAULT NULL COMMENT '财务费用_去年同期(元)',
    ipoa_loss_cply         DECIMAL(21, 8)               DEFAULT NULL COMMENT '资产减值损失_去年同期(元)',
    cred_decr_loss_cply    DECIMAL(21, 8)               DEFAULT NULL COMMENT '信用减值损失_去年同期(元)',
    busi_prof_cply         DECIMAL(21, 8)               DEFAULT NULL COMMENT '营业利润_去年同期(元)',
    ivsm_payf_cply         DECIMAL(21, 8)               DEFAULT NULL COMMENT '投资收益_去年同期(元)',
    nopr_incm_cply         DECIMAL(21, 8)               DEFAULT NULL COMMENT '营业外收入_去年同期(元)',
    nopr_pay_cply          DECIMAL(21, 8)               DEFAULT NULL COMMENT '营业外支出_去年同期(元)',
    prof_gamt_cply         DECIMAL(21, 8)               DEFAULT NULL COMMENT '利润总额_去年同期(元)',
    inct_fee_cply          DECIMAL(21, 8)               DEFAULT NULL COMMENT '所得税费用_去年同期(元)',
    net_prof_cply          DECIMAL(21, 8)               DEFAULT NULL COMMENT '净利润_去年同期(元)',
    report_instance_id     VARCHAR(64)         NOT NULL COMMENT '报表实例ID | UUID',
    report_instance_period VARCHAR(24)         NOT NULL COMMENT '报表周期 | YYYYQQ格式',
    batch_no               VARCHAR(4)          NOT NULL COMMENT '批次号 | 0000-9999',
    version                VARCHAR(128)        NOT NULL COMMENT '版本号 | 周期+版本',
    op                     VARCHAR(16)         NOT NULL DEFAULT 'insert' COMMENT '操作标识 | insert/update',
    report_time            DATETIME            NOT NULL COMMENT '上报时间',
    write_time             datetime            NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '入库时间',
    `create_time`          datetime            NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `create_by`            bigint(20)                   DEFAULT NULL COMMENT '创建人id',
    `update_time`          datetime            NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `update_by`            bigint(20)                   DEFAULT NULL COMMENT '更新人id',
    PRIMARY KEY (id)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4 COMMENT ='公司利润表数据表';

-- 资产负债表
CREATE TABLE association_balance_sheet_partial
(
    id                      BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '自增主键',
    row_num                 INT(11)             NOT NULL COMMENT '行号 | 同一批次数据从1开始递增',
    unif_soci_cred_code     VARCHAR(32)         NOT NULL COMMENT '企业统一社会信用代码',
    crcp_aboy               DECIMAL(21, 8)               DEFAULT NULL COMMENT '货币资金_年初数(元)',
    trd_finl_ast_aboy       DECIMAL(21, 8)               DEFAULT NULL COMMENT '交易性金融资产_年初数(元)',
    devd_finl_ast_aboy      DECIMAL(21, 8)               DEFAULT NULL COMMENT '衍生金融资产_年初数(元)',
    recv_bill_aboy          DECIMAL(21, 8)               DEFAULT NULL COMMENT '应收票据_年初数(元)',
    recv_amt_aboy           DECIMAL(21, 8)               DEFAULT NULL COMMENT '应收账款_年初数(元)',
    recv_amt_fin_aboy       DECIMAL(21, 8)               DEFAULT NULL COMMENT '应收款项融资_年初数(元)',
    pia_amt_aboy            DECIMAL(21, 8)               DEFAULT NULL COMMENT '预付账款_年初数(元)',
    oth_recv_amt_tot_aboy   DECIMAL(21, 8)               DEFAULT NULL COMMENT '其他应收款总计_年初数(元)',
    recv_divd_aboy          DECIMAL(21, 8)               DEFAULT NULL COMMENT '应收股利_年初数(元)',
    recv_intr_aboy          DECIMAL(21, 8)               DEFAULT NULL COMMENT '应收利息_年初数(元)',
    oth_recv_amt_aboy       DECIMAL(21, 8)               DEFAULT NULL COMMENT '其他应收款_年初数(元)',
    inv_aboy                DECIMAL(21, 8)               DEFAULT NULL COMMENT '存货_年初数(元)',
    agmt_ast_aboy           DECIMAL(21, 8)               DEFAULT NULL COMMENT '合同资产_年初数(元)',
    hold_sale_ast_aboy      DECIMAL(21, 8)               DEFAULT NULL COMMENT '持有待售资产_年初数(元)',
    ncoy_aboy               DECIMAL(21, 8)               DEFAULT NULL COMMENT '一年内到期的非流动资产_年初数(元)',
    oth_liqd_ast_aboy       DECIMAL(21, 8)               DEFAULT NULL COMMENT '其他流动资产_年初数(元)',
    liqd_ast_tot_aboy       DECIMAL(21, 8)               DEFAULT NULL COMMENT '流动资产合计_年初数(元)',
    clam_ivsm_aboy          DECIMAL(21, 8)               DEFAULT NULL COMMENT '债权投资_年初数(元)',
    oth_clam_ivsm_aboy      DECIMAL(21, 8)               DEFAULT NULL COMMENT '其他债权投资_年初数(元)',
    long_recv_amt_aboy      DECIMAL(21, 8)               DEFAULT NULL COMMENT '长期应收款_年初数(元)',
    lsri_aboy               DECIMAL(21, 8)               DEFAULT NULL COMMENT '长期股权投资_年初数(元)',
    oth_equi_inst_ivsm_aboy DECIMAL(21, 8)               DEFAULT NULL COMMENT '其他权益工具投资_年初数(元)',
    oth_nocr_finl_ast_aboy  DECIMAL(21, 8)               DEFAULT NULL COMMENT '其他非流动金融资产_年初数(元)',
    ivsm_estt_aboy          DECIMAL(21, 8)               DEFAULT NULL COMMENT '投资性房地产_年初数(元)',
    fix_ast_aboy            DECIMAL(21, 8)               DEFAULT NULL COMMENT '固定资产_年初数(元)',
    udcs_proj_aboy          DECIMAL(21, 8)               DEFAULT NULL COMMENT '在建工程_年初数(元)',
    prod_biol_matr_aboy     DECIMAL(21, 8)               DEFAULT NULL COMMENT '生产性生物资产_年初数(元)',
    olgs_ast_aboy           DECIMAL(21, 8)               DEFAULT NULL COMMENT '油气资产_年初数(元)',
    use_ast_aboy            DECIMAL(21, 8)               DEFAULT NULL COMMENT '使用权资产_年初数(元)',
    imtr_ast_aboy           DECIMAL(21, 8)               DEFAULT NULL COMMENT '无形资产_年初数(元)',
    dev_pay_aboy            DECIMAL(21, 8)               DEFAULT NULL COMMENT '开发支出_年初数(元)',
    gdwl_aboy               DECIMAL(21, 8)               DEFAULT NULL COMMENT '商誉_年初数(元)',
    long_tbat_fee_aboy      DECIMAL(21, 8)               DEFAULT NULL COMMENT '长期待摊费用_年初数(元)',
    defr_tax_ast_aboy       DECIMAL(21, 8)               DEFAULT NULL COMMENT '递延所得税资产_年初数(元)',
    oth_nocr_ast_aboy       DECIMAL(21, 8)               DEFAULT NULL COMMENT '其他非流动资产_年初数(元)',
    nocr_ast_tot_aboy       DECIMAL(21, 8)               DEFAULT NULL COMMENT '非流动资产合计_年初数(元)',
    ast_tot_aboy            DECIMAL(21, 8)               DEFAULT NULL COMMENT '资产总计_年初数(元)',
    shtt_loan_aboy          DECIMAL(21, 8)               DEFAULT NULL COMMENT '短期借款_年初数(元)',
    trd_finl_liab_aboy      DECIMAL(21, 8)               DEFAULT NULL COMMENT '交易性金融负债_年初数(元)',
    devd_finl_liab_aboy     DECIMAL(21, 8)               DEFAULT NULL COMMENT '衍生金融负债_年初数(元)',
    payb_bill_aboy          DECIMAL(21, 8)               DEFAULT NULL COMMENT '应付票据_年初数(元)',
    payb_amt_aboy           DECIMAL(21, 8)               DEFAULT NULL COMMENT '应付账款_年初数(元)',
    ciad_amt_aboy           DECIMAL(21, 8)               DEFAULT NULL COMMENT '预收账款_年初数(元)',
    agmt_liab_aboy          DECIMAL(21, 8)               DEFAULT NULL COMMENT '合同负债_年初数(元)',
    payb_emp_cmps_aboy      DECIMAL(21, 8)               DEFAULT NULL COMMENT '应付职工薪酬_年初数(元)',
    payc_tax_fee_aboy       DECIMAL(21, 8)               DEFAULT NULL COMMENT '应交税费_年初数(元)',
    oth_payb_amt_tot_aboy   DECIMAL(21, 8)               DEFAULT NULL COMMENT '其他应付款总计_年初数(元)',
    payb_intr_aboy          DECIMAL(21, 8)               DEFAULT NULL COMMENT '应付利息_年初数(元)',
    payb_divd_aboy          DECIMAL(21, 8)               DEFAULT NULL COMMENT '应付股利_年初数(元)',
    oth_payb_amt_aboy       DECIMAL(21, 8)               DEFAULT NULL COMMENT '其他应付款_年初数(元)',
    hold_sale_liab_aboy     DECIMAL(21, 8)               DEFAULT NULL COMMENT '持有待售负债_年初数(元)',
    oney_nocr_liab_aboy     DECIMAL(21, 8)               DEFAULT NULL COMMENT '一年内到期的非流动负债_年初数(元)',
    oth_liqd_liab_aboy      DECIMAL(21, 8)               DEFAULT NULL COMMENT '其他流动负债_年初数(元)',
    liqd_liab_tot_aboy      DECIMAL(21, 8)               DEFAULT NULL COMMENT '流动负债合计_年初数(元)',
    long_loan_aboy          DECIMAL(21, 8)               DEFAULT NULL COMMENT '长期借款_年初数(元)',
    payb_bond_aboy          DECIMAL(21, 8)               DEFAULT NULL COMMENT '应付债券_年初数(元)',
    long_payb_amt_aboy      DECIMAL(21, 8)               DEFAULT NULL COMMENT '长期应付款_年初数(元)',
    long_payb_emp_cmps_aboy DECIMAL(21, 8)               DEFAULT NULL COMMENT '长期应付职工薪酬_年初数(元)',
    leas_liab_aboy          DECIMAL(21, 8)               DEFAULT NULL COMMENT '租赁负债_年初数(元)',
    expe_liab_aboy          DECIMAL(21, 8)               DEFAULT NULL COMMENT '预计负债_年初数(元)',
    defr_payf_aboy          DECIMAL(21, 8)               DEFAULT NULL COMMENT '递延收益_年初数(元)',
    defr_inct_liab_aboy     DECIMAL(21, 8)               DEFAULT NULL COMMENT '递延所得税负债_年初数(元)',
    oth_nocr_liab_aboy      DECIMAL(21, 8)               DEFAULT NULL COMMENT '其他非流动负债_年初数(元)',
    nocr_liab_tot_aboy      DECIMAL(21, 8)               DEFAULT NULL COMMENT '非流动负债合计_年初数(元)',
    liab_tot_aboy           DECIMAL(21, 8)               DEFAULT NULL COMMENT '负债合计_年初数(元)',
    paid_cptl_aboy          DECIMAL(21, 8)               DEFAULT NULL COMMENT '实收资本_年初数(元)',
    oth_equi_inst_aboy      DECIMAL(21, 8)               DEFAULT NULL COMMENT '其他权益工具_年初数(元)',
    cptl_rsrv_aboy          DECIMAL(21, 8)               DEFAULT NULL COMMENT '资本公积_年初数(元)',
    oth_cmph_payf_aboy      DECIMAL(21, 8)               DEFAULT NULL COMMENT '其他综合收益_年初数(元)',
    spcl_rsrv_aboy          DECIMAL(21, 8)               DEFAULT NULL COMMENT '专项储备_年初数(元)',
    surp_rsrv_aboy          DECIMAL(21, 8)               DEFAULT NULL COMMENT '盈余公积_年初数(元)',
    risk_prep_aboy          DECIMAL(21, 8)               DEFAULT NULL COMMENT '一般风险准备_年初数(元)',
    no_assn_prof_aboy       DECIMAL(21, 8)               DEFAULT NULL COMMENT '未分配利润_年初数(元)',
    attr_prn_cpon_equi_aboy DECIMAL(21, 8)               DEFAULT NULL COMMENT '归属母公司所有者权益合计_年初数(元)',
    mish_equi_aboy          DECIMAL(21, 8)               DEFAULT NULL COMMENT '少数股东权益_年初数(元)',
    toeq_aboy               DECIMAL(21, 8)               DEFAULT NULL COMMENT '所有者权益合计_年初数(元)',
    liab_toeq_aboy          DECIMAL(21, 8)               DEFAULT NULL COMMENT '负债及所有者权益合计_年初数(元)',
    crcp_aeop               DECIMAL(21, 8)               DEFAULT NULL COMMENT '货币资金_期末数(元)',
    trd_finl_ast_aeop       DECIMAL(21, 8)               DEFAULT NULL COMMENT '交易性金融资产_期末数(元)',
    devd_finl_ast_aeop      DECIMAL(21, 8)               DEFAULT NULL COMMENT '衍生金融资产_期末数(元)',
    recv_bill_aeop          DECIMAL(21, 8)               DEFAULT NULL COMMENT '应收票据_期末数(元)',
    recv_amt_aeop           DECIMAL(21, 8)               DEFAULT NULL COMMENT '应收账款_期末数(元)',
    recv_amt_fin_aeop       DECIMAL(21, 8)               DEFAULT NULL COMMENT '应收款项融资_期末数(元)',
    pia_amt_aeop            DECIMAL(21, 8)               DEFAULT NULL COMMENT '预付账款_期末数(元)',
    oth_recv_amt_tot_aeop   DECIMAL(21, 8)               DEFAULT NULL COMMENT '其他应收款总计_期末数(元)',
    recv_divd_aeop          DECIMAL(21, 8)               DEFAULT NULL COMMENT '应收股利_期末数(元)',
    recv_intr_aeop          DECIMAL(21, 8)               DEFAULT NULL COMMENT '应收利息_期末数(元)',
    oth_recv_amt_aeop       DECIMAL(21, 8)               DEFAULT NULL COMMENT '其他应收款_期末数(元)',
    inv_aeop                DECIMAL(21, 8)               DEFAULT NULL COMMENT '存货_期末数(元)',
    agmt_ast_aeop           DECIMAL(21, 8)               DEFAULT NULL COMMENT '合同资产_期末数(元)',
    hold_sale_ast_aeop      DECIMAL(21, 8)               DEFAULT NULL COMMENT '持有待售资产_期末数(元)',
    ncoy_aeop               DECIMAL(21, 8)               DEFAULT NULL COMMENT '一年内到期的非流动资产_期末数(元)',
    oth_liqd_ast_aeop       DECIMAL(21, 8)               DEFAULT NULL COMMENT '其他流动资产_期末数(元)',
    liqd_ast_tot_aeop       DECIMAL(21, 8)               DEFAULT NULL COMMENT '流动资产合计_期末数(元)',
    clam_ivsm_aeop          DECIMAL(21, 8)               DEFAULT NULL COMMENT '债权投资_期末数(元)',
    oth_clam_ivsm_aeop      DECIMAL(21, 8)               DEFAULT NULL COMMENT '其他债权投资_期末数(元)',
    long_recv_amt_aeop      DECIMAL(21, 8)               DEFAULT NULL COMMENT '长期应收款_期末数(元)',
    lsri_aeop               DECIMAL(21, 8)               DEFAULT NULL COMMENT '长期股权投资_期末数(元)',
    oth_equi_inst_ivsm_aeop DECIMAL(21, 8)               DEFAULT NULL COMMENT '其他权益工具投资_期末数(元)',
    oth_nocr_finl_ast_aeop  DECIMAL(21, 8)               DEFAULT NULL COMMENT '其他非流动金融资产_期末数(元)',
    ivsm_estt_aeop          DECIMAL(21, 8)               DEFAULT NULL COMMENT '投资性房地产_期末数(元)',
    fix_ast_aeop            DECIMAL(21, 8)               DEFAULT NULL COMMENT '固定资产_期末数(元)',
    udcs_proj_aeop          DECIMAL(21, 8)               DEFAULT NULL COMMENT '在建工程_期末数(元)',
    prod_biol_matr_aeop     DECIMAL(21, 8)               DEFAULT NULL COMMENT '生产性生物资产_期末数(元)',
    olgs_ast_aeop           DECIMAL(21, 8)               DEFAULT NULL COMMENT '油气资产_期末数(元)',
    use_ast_aeop            DECIMAL(21, 8)               DEFAULT NULL COMMENT '使用权资产_期末数(元)',
    imtr_ast_aeop           DECIMAL(21, 8)               DEFAULT NULL COMMENT '无形资产_期末数(元)',
    dev_pay_aeop            DECIMAL(21, 8)               DEFAULT NULL COMMENT '开发支出_期末数(元)',
    gdwl_aeop               DECIMAL(21, 8)               DEFAULT NULL COMMENT '商誉_期末数(元)',
    long_tbat_fee_aeop      DECIMAL(21, 8)               DEFAULT NULL COMMENT '长期待摊费用_期末数(元)',
    defr_tax_ast_aeop       DECIMAL(21, 8)               DEFAULT NULL COMMENT '递延所得税资产_期末数(元)',
    oth_nocr_ast_aeop       DECIMAL(21, 8)               DEFAULT NULL COMMENT '其他非流动资产_期末数(元)',
    nocr_ast_tot_aeop       DECIMAL(21, 8)               DEFAULT NULL COMMENT '非流动资产合计_期末数(元)',
    ast_tot_aeop            DECIMAL(21, 8)               DEFAULT NULL COMMENT '资产总计_期末数(元)',
    shtt_loan_aeop          DECIMAL(21, 8)               DEFAULT NULL COMMENT '短期借款_期末数(元)',
    trd_finl_liab_aeop      DECIMAL(21, 8)               DEFAULT NULL COMMENT '交易性金融负债_期末数(元)',
    devd_finl_liab_aeop     DECIMAL(21, 8)               DEFAULT NULL COMMENT '衍生金融负债_期末数(元)',
    payb_bill_aeop          DECIMAL(21, 8)               DEFAULT NULL COMMENT '应付票据_期末数(元)',
    payb_amt_aeop           DECIMAL(21, 8)               DEFAULT NULL COMMENT '应付账款_期末数(元)',
    ciad_amt_aeop           DECIMAL(21, 8)               DEFAULT NULL COMMENT '预收账款_期末数(元)',
    agmt_liab_aeop          DECIMAL(21, 8)               DEFAULT NULL COMMENT '合同负债_期末数(元)',
    payb_emp_cmps_aeop      DECIMAL(21, 8)               DEFAULT NULL COMMENT '应付职工薪酬_期末数(元)',
    payc_tax_fee_aeop       DECIMAL(21, 8)               DEFAULT NULL COMMENT '应交税费_期末数(元)',
    oth_payb_amt_tot_aeop   DECIMAL(21, 8)               DEFAULT NULL COMMENT '其他应付款总计_期末数(元)',
    payb_intr_aeop          DECIMAL(21, 8)               DEFAULT NULL COMMENT '应付利息_期末数(元)',
    payb_divd_aeop          DECIMAL(21, 8)               DEFAULT NULL COMMENT '应付股利_期末数(元)',
    oth_payb_amt_aeop       DECIMAL(21, 8)               DEFAULT NULL COMMENT '其他应付款_期末数(元)',
    hold_sale_liab_aeop     DECIMAL(21, 8)               DEFAULT NULL COMMENT '持有待售负债_期末数(元)',
    oney_nocr_liab_aeop     DECIMAL(21, 8)               DEFAULT NULL COMMENT '一年内到期的非流动负债_期末数(元)',
    oth_liqd_liab_aeop      DECIMAL(21, 8)               DEFAULT NULL COMMENT '其他流动负债_期末数(元)',
    liqd_liab_tot_aeop      DECIMAL(21, 8)               DEFAULT NULL COMMENT '流动负债合计_期末数(元)',
    long_loan_aeop          DECIMAL(21, 8)               DEFAULT NULL COMMENT '长期借款_期末数(元)',
    payb_bond_aeop          DECIMAL(21, 8)               DEFAULT NULL COMMENT '应付债券_期末数(元)',
    long_payb_amt_aeop      DECIMAL(21, 8)               DEFAULT NULL COMMENT '长期应付款_期末数(元)',
    long_payb_emp_cmps_aeop DECIMAL(21, 8)               DEFAULT NULL COMMENT '长期应付职工薪酬_期末数(元)',
    leas_liab_aeop          DECIMAL(21, 8)               DEFAULT NULL COMMENT '租赁负债_期末数(元)',
    expe_liab_aeop          DECIMAL(21, 8)               DEFAULT NULL COMMENT '预计负债_期末数(元)',
    defr_payf_aeop          DECIMAL(21, 8)               DEFAULT NULL COMMENT '递延收益_期末数(元)',
    defr_inct_liab_aeop     DECIMAL(21, 8)               DEFAULT NULL COMMENT '递延所得税负债_期末数(元)',
    oth_nocr_liab_aeop      DECIMAL(21, 8)               DEFAULT NULL COMMENT '其他非流动负债_期末数(元)',
    nocr_liab_tot_aeop      DECIMAL(21, 8)               DEFAULT NULL COMMENT '非流动负债合计_期末数(元)',
    liab_tot_aeop           DECIMAL(21, 8)               DEFAULT NULL COMMENT '负债合计_期末数(元)',
    paid_cptl_aeop          DECIMAL(21, 8)               DEFAULT NULL COMMENT '实收资本_期末数(元)',
    oth_equi_inst_aeop      DECIMAL(21, 8)               DEFAULT NULL COMMENT '其他权益工具_期末数(元)',
    cptl_rsrv_aeop          DECIMAL(21, 8)               DEFAULT NULL COMMENT '资本公积_期末数(元)',
    oth_cmph_payf_aeop      DECIMAL(21, 8)               DEFAULT NULL COMMENT '其他综合收益_期末数(元)',
    spcl_rsrv_aeop          DECIMAL(21, 8)               DEFAULT NULL COMMENT '专项储备_期末数(元)',
    surp_rsrv_aeop          DECIMAL(21, 8)               DEFAULT NULL COMMENT '盈余公积_期末数(元)',
    risk_prep_aeop          DECIMAL(21, 8)               DEFAULT NULL COMMENT '一般风险准备_期末数(元)',
    no_assn_prof_aeop       DECIMAL(21, 8)               DEFAULT NULL COMMENT '未分配利润_期末数(元)',
    attr_prn_cpon_equi_aeop DECIMAL(21, 8)               DEFAULT NULL COMMENT '归属母公司所有者权益合计_期末数(元)',
    mish_equi_aeop          DECIMAL(21, 8)               DEFAULT NULL COMMENT '少数股东权益_期末数(元)',
    toeq_aeop               DECIMAL(21, 8)               DEFAULT NULL COMMENT '所有者权益合计_期末数(元)',
    liab_toeq_aeop          DECIMAL(21, 8)               DEFAULT NULL COMMENT '负债及所有者权益合计_期末数(元)',
    report_instance_id      VARCHAR(32)         NOT NULL COMMENT '报表实例编号 UUID联合主键：(report_instance_id, row_num)同一批次数据报表实例编号值相同',
    report_instance_period  VARCHAR(32)         NOT NULL COMMENT '报表实例周期格式：YYYYQQ',
    batch_no                VARCHAR(32)         NOT NULL COMMENT '批次号',
    version                 VARCHAR(32)         NOT NULL COMMENT '版本号',
    op                      VARCHAR(32)         NOT NULL COMMENT '操作标识 新增数据为insert,更新数据记录时值为update',
    report_time             datetime            NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '上报时间',
    write_time              datetime            NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '写入时间',
    `create_time`           datetime            NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `create_by`             bigint(20)                   DEFAULT NULL COMMENT '创建人id',
    `update_time`           datetime            NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `update_by`             bigint(20)                   DEFAULT NULL COMMENT '更新人id',
    PRIMARY KEY (id)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
    COMMENT ='资产负债表';


CREATE TABLE association_business_situation
(
    id                       BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '自增主键',
    row_num                  INT(11)             NOT NULL COMMENT '行号 | 同一批次数据从1开始递增',
    unif_soci_cred_code      VARCHAR(32)         NOT NULL COMMENT '企业统一社会信用代码',
    tot_incm_abop            DECIMAL(25, 8)               DEFAULT NULL COMMENT '总收入_期初数（万元）',
    tot_incm_aotc            DECIMAL(25, 8)               DEFAULT NULL COMMENT '总收入_本期发生额（万元）',
    tot_incm_aeop            DECIMAL(25, 8)               DEFAULT NULL COMMENT '总收入_期末数（万元）',
    oper_leas_busi_incm_abop DECIMAL(25, 8)               DEFAULT NULL COMMENT '经营租赁业务收入_期初数（万元）',
    oper_leas_busi_incm_aotc DECIMAL(25, 8)               DEFAULT NULL COMMENT '经营租赁业务收入_本期发生额（万元）',
    oper_leas_busi_incm_aeop DECIMAL(25, 8)               DEFAULT NULL COMMENT '经营租赁业务收入_期末数（万元）',
    fnl_busi_incm_abop       DECIMAL(25, 8)               DEFAULT NULL COMMENT '融资租赁业务收入_期初数（万元）',
    fnl_busi_incm_aotc       DECIMAL(25, 8)               DEFAULT NULL COMMENT '融资租赁业务收入_本期发生额（万元）',
    fnl_busi_incm_aeop       DECIMAL(25, 8)               DEFAULT NULL COMMENT '融资租赁业务收入_期末数（万元）',
    intr_incm_abop           DECIMAL(25, 8)               DEFAULT NULL COMMENT '利息收入_期初数（万元）',
    intr_incm_aotc           DECIMAL(25, 8)               DEFAULT NULL COMMENT '利息收入_本期发生额（万元）',
    intr_incm_aeop           DECIMAL(25, 8)               DEFAULT NULL COMMENT '利息收入_期末数（万元）',
    fee_incm_abop            DECIMAL(25, 8)               DEFAULT NULL COMMENT '费用收入_期初数（万元）',
    fee_incm_aotc            DECIMAL(25, 8)               DEFAULT NULL COMMENT '费用收入_本期发生额（万元）',
    fee_incm_aeop            DECIMAL(25, 8)               DEFAULT NULL COMMENT '费用收入_期末数（万元）',
    oth_incm_abop            DECIMAL(25, 8)               DEFAULT NULL COMMENT '其他收入_期初数（万元）',
    oth_incm_aotc            DECIMAL(25, 8)               DEFAULT NULL COMMENT '其他收入_本期发生额（万元）',
    oth_incm_aeop            DECIMAL(25, 8)               DEFAULT NULL COMMENT '其他收入_期末数（万元）',
    leas_ast_abop            DECIMAL(25, 8)               DEFAULT NULL COMMENT '租赁资产_期初数（万元）',
    leas_ast_aotc            DECIMAL(25, 8)               DEFAULT NULL COMMENT '租赁资产_本期发生额（万元）',
    leas_ast_aeop            DECIMAL(25, 8)               DEFAULT NULL COMMENT '租赁资产_期末数（万元）',
    oper_leas_ast_abop       DECIMAL(25, 8)               DEFAULT NULL COMMENT '经营性租赁资产_期初数（万元）',
    oper_leas_ast_aotc       DECIMAL(25, 8)               DEFAULT NULL COMMENT '经营性租赁资产_本期发生额（万元）',
    oper_leas_ast_aeop       DECIMAL(25, 8)               DEFAULT NULL COMMENT '经营性租赁资产_期末数（万元）',
    fin_leas_ast_abop        DECIMAL(25, 8)               DEFAULT NULL COMMENT '融资租赁资产_期初数（万元）',
    fin_leas_ast_aotc        DECIMAL(25, 8)               DEFAULT NULL COMMENT '融资租赁资产_本期发生额（万元）',
    fin_leas_ast_aeop        DECIMAL(25, 8)               DEFAULT NULL COMMENT '融资租赁资产_期末数（万元）',
    dirt_leas_ast_abop       DECIMAL(25, 8)               DEFAULT NULL COMMENT '直接租赁资产_期初数（万元）',
    dirt_leas_ast_aotc       DECIMAL(25, 8)               DEFAULT NULL COMMENT '直接租赁资产_本期发生额（万元）',
    dirt_leas_ast_aeop       DECIMAL(25, 8)               DEFAULT NULL COMMENT '直接租赁资产_期末数（万元）',
    slbk_ast_abop            DECIMAL(25, 8)               DEFAULT NULL COMMENT '售后回租资产_期初数（万元）',
    slbk_ast_aotc            DECIMAL(25, 8)               DEFAULT NULL COMMENT '售后回租资产_本期发生额（万元）',
    slbk_ast_aeop            DECIMAL(25, 8)               DEFAULT NULL COMMENT '售后回租资产_期末数（万元）',
    iprv_fnl_ast_bal_abop    DECIMAL(25, 8)               DEFAULT NULL COMMENT '跨省融资租赁资产余额_期初数（万元）',
    iprv_fnl_ast_bal_aotc    DECIMAL(25, 8)               DEFAULT NULL COMMENT '跨省融资租赁资产余额_本期发生额（万元）',
    iprv_fnl_ast_bal_aeop    DECIMAL(25, 8)               DEFAULT NULL COMMENT '跨省融资租赁资产余额_期末数（万元）',
    iprv_slbk_ast_bal_abop   DECIMAL(25, 8)               DEFAULT NULL COMMENT '跨省售后回租资产余额_期初数（万元）',
    iprv_slbk_ast_bal_aotc   DECIMAL(25, 8)               DEFAULT NULL COMMENT '跨省售后回租资产余额_本期发生额（万元）',
    iprv_slbk_ast_bal_aeop   DECIMAL(25, 8)               DEFAULT NULL COMMENT '跨省售后回租资产余额_期末数（万元）',
    fnl_rels_abop            DECIMAL(25, 8)               DEFAULT NULL COMMENT '融资租赁投放额_期初数（万元）',
    fnl_rels_aotc            DECIMAL(25, 8)               DEFAULT NULL COMMENT '融资租赁投放额_本期发生额（万元）',
    fnl_rels_aeop            DECIMAL(25, 8)               DEFAULT NULL COMMENT '融资租赁投放额_期末数（万元）',
    dirt_leas_rels_abop      DECIMAL(25, 8)               DEFAULT NULL COMMENT '直接租赁投放额_期初数（万元）',
    dirt_leas_rels_aotc      DECIMAL(25, 8)               DEFAULT NULL COMMENT '直接租赁投放额_本期发生额（万元）',
    dirt_leas_rels_aeop      DECIMAL(25, 8)               DEFAULT NULL COMMENT '直接租赁投放额_期末数（万元）',
    slbk_rels_abop           DECIMAL(25, 8)               DEFAULT NULL COMMENT '售后回租投放额_期初数（万元）',
    slbk_rels_aotc           DECIMAL(25, 8)               DEFAULT NULL COMMENT '售后回租投放额_本期发生额（万元）',
    slbk_rels_aeop           DECIMAL(25, 8)               DEFAULT NULL COMMENT '售后回租投放额_期末数（万元）',
    fix_payf_scr_ivsm_abop   DECIMAL(25, 8)               DEFAULT NULL COMMENT '固定收益类证券投资余额_期初数（万元）',
    fix_payf_scr_ivsm_aotc   DECIMAL(25, 8)               DEFAULT NULL COMMENT '固定收益类证券投资余额_本期发生额（万元）',
    fix_payf_scr_ivsm_aeop   DECIMAL(25, 8)               DEFAULT NULL COMMENT '固定收益类证券投资_期末数（万元）',
    trea_abop                DECIMAL(25, 8)               DEFAULT NULL COMMENT '国债余额_期初数（万元）',
    trea_aotc                DECIMAL(25, 8)               DEFAULT NULL COMMENT '国债余额_本期发生额（万元）',
    trea_aeop                DECIMAL(25, 8)               DEFAULT NULL COMMENT '国债余额_期末数（万元）',
    ipoa_loss_abop           DECIMAL(25, 8)               DEFAULT NULL COMMENT '资产减值损失准备_期初数（万元）',
    ipoa_loss_aotc           DECIMAL(25, 8)               DEFAULT NULL COMMENT '资产减值损失准备_本期发生额（万元）',
    ipoa_loss_aeop           DECIMAL(25, 8)               DEFAULT NULL COMMENT '资产减值损失准备_期末数（万元）',
    report_instance_id       VARCHAR(64)         NOT NULL COMMENT '报表实例唯一标识 | UUID格式',
    report_instance_period   VARCHAR(24)         NOT NULL COMMENT '报表周期 | 格式：YYYYMM',
    batch_no                 VARCHAR(4)          NOT NULL COMMENT '批次号 | 从0000递增，最大9999',
    version                  VARCHAR(128)        NOT NULL COMMENT '版本号 | 格式：报表周期+版本流水号',
    op                       VARCHAR(16)         NOT NULL DEFAULT 'insert' COMMENT '操作标识 | insert/update',
    report_time              DATETIME            NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '上报时间 | 文件上传时间',
    write_time               datetime            NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '写入时间 | 数据库记录时间',
    `create_time`            datetime            NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `create_by`              bigint(20)                   DEFAULT NULL COMMENT '创建人id',
    `update_time`            datetime            NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `update_by`              bigint(20)                   DEFAULT NULL COMMENT '更新人id',
    PRIMARY KEY (id)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4 COMMENT ='业务情况表';


CREATE TABLE `association_report_sort`
(
    `id`                   bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键id',
    `create_time`          datetime     NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `create_by`            bigint(20) DEFAULT NULL COMMENT '创建人id',
    `update_time`          datetime     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `update_by`            bigint(20) DEFAULT NULL COMMENT '更新人id',
    `deleted`              tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除，0-未删除',
    `report_category_code` varchar(20)  NOT NULL DEFAULT '' COMMENT '报表分类编码',
    `report_category_name` varchar(100) NOT NULL DEFAULT '' COMMENT '报表分类名称',
    `field_name`           varchar(64)  NOT NULL COMMENT '字段名称',
    `sort`                 int(11) NOT NULL COMMENT '字段排序 越小越前',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COMMENT='金融协会报送-上报文件字段排序';

