package cn.zswltech.mithras.collection.application.facade;

import cn.zswltech.mithras.api.common.PageR;
import cn.zswltech.mithras.dto.collection.CollectionFlowCenterBusinessCollectionExportListREQ;
import cn.zswltech.mithras.dto.collection.CollectionFlowCenterBusinessCollectionExportREQ;
import cn.zswltech.mithras.dto.collection.CollectionFlowCenterBusinessCollectionListREQ;
import cn.zswltech.mithras.dto.collection.CollectionFlowCenterBusinessCollectionListRSP;
import cn.zswltech.mithras.dto.collection.CollectionFlowCenterBusinessCollectionManualRecordREQ;
import cn.zswltech.mithras.dto.collection.CollectionFlowCenterBusinessCollectionSettleDetailREQ;
import cn.zswltech.mithras.dto.collection.CollectionFlowCenterBusinessCollectionSettleDetailRSP;
import cn.zswltech.mithras.dto.collection.CollectionFlowCenterBusinessPaymentListREQ;
import cn.zswltech.mithras.dto.collection.CollectionFlowCenterBusinessPaymentListRSP;
import cn.zswltech.mithras.dto.collection.CollectionFlowCenterBusinessPaymentManualCashFlowListREQ;
import cn.zswltech.mithras.dto.collection.CollectionFlowCenterBusinessPaymentManualRecordREQ;
import cn.zswltech.mithras.dto.collection.CollectionFlowCenterBusinessPaymentManualRecordRSP;
import cn.zswltech.mithras.dto.collection.CollectionFlowCenterBusinessPaymentSettleDetailREQ;
import cn.zswltech.mithras.dto.collection.CollectionFlowCenterBusinessPaymentSettleDetailRSP;
import cn.zswltech.mithras.dto.collection.CollectionFlowCenterClientContractMarginREQ;
import cn.zswltech.mithras.dto.collection.CollectionFlowCenterClientContractMarginRSP;
import cn.zswltech.mithras.dto.collection.CollectionFlowCenterRecycleMarginPlanREQ;
import cn.zswltech.mithras.dto.collection.CollectionFlowCenterRecycleMarginPlanRSP;

import javax.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.util.List;

public interface CollectionFlowCenterApplicationService {

    PageR<CollectionFlowCenterBusinessPaymentListRSP> paymentList(CollectionFlowCenterBusinessPaymentListREQ req);

    void paymentManualRecord(CollectionFlowCenterBusinessPaymentManualRecordREQ req);

    List<CollectionFlowCenterBusinessPaymentManualRecordRSP> paymentManualCashFlowList(CollectionFlowCenterBusinessPaymentManualCashFlowListREQ req);

    List<CollectionFlowCenterBusinessPaymentSettleDetailRSP> paymentSettleDetail(CollectionFlowCenterBusinessPaymentSettleDetailREQ req);

    PageR<CollectionFlowCenterBusinessCollectionListRSP> collectionList(CollectionFlowCenterBusinessCollectionListREQ req);

    void collectionManualRecord(CollectionFlowCenterBusinessCollectionManualRecordREQ req);

    List<CollectionFlowCenterBusinessCollectionSettleDetailRSP> collectionSettleDetail(CollectionFlowCenterBusinessCollectionSettleDetailREQ req);

    void exportBusinessCollection(CollectionFlowCenterBusinessCollectionExportListREQ req, HttpServletResponse response) throws IOException;

    List<CollectionFlowCenterBusinessCollectionListRSP> businessCollectionExportList(CollectionFlowCenterBusinessCollectionExportREQ req);

    List<CollectionFlowCenterClientContractMarginRSP> clientContractMargin(CollectionFlowCenterClientContractMarginREQ req);

    CollectionFlowCenterRecycleMarginPlanRSP recycleMarginPlan(CollectionFlowCenterRecycleMarginPlanREQ req);
}
