INSERT INTO `kpi_parameter_config` (`config_code`, `config_desc`, `config_value`)
VALUES
	('TAX_RATE', '税率维护', '[{\"bizType\":\"ZL_ZZ\",\"configValueType\":\"VALUE\",\"taxRate\":\"13\",\"taxType\":\"ZZS\"},{\"bizType\":\"ZL_HZ\",\"configValueType\":\"VALUE\",\"taxRate\":\"6\",\"taxType\":\"ZZS\"},{\"bizType\":\"ZL_JYX\",\"configValueType\":\"VALUE\",\"taxRate\":\"13\",\"taxType\":\"ZZS\"},{\"bizType\":\"BL\",\"configValueType\":\"VALUE\",\"taxRate\":\"6\",\"taxType\":\"ZZS\"},{\"bizType\":\"ZR\",\"configValueType\":\"VALUE\",\"taxRate\":\"6\",\"taxType\":\"ZZS\"},{\"bizType\":\"\",\"configValueType\":\"VALUE\",\"taxRate\":\"7\",\"taxType\":\"CJS\"},{\"bizType\":\"\",\"configValueType\":\"VALUE\",\"taxRate\":\"3\",\"taxType\":\"JYFJS\"},{\"bizType\":\"\",\"configValueType\":\"VALUE\",\"taxRate\":\"2\",\"taxType\":\"DFJYFJS\"},{\"bizType\":\"RZZLHT\",\"configValueType\":\"VALUE\",\"taxRate\":\"0.005\",\"taxType\":\"YHS\"},{\"bizType\":\"ZXHT\",\"configValueType\":\"VALUE\",\"taxRate\":\"0.005\",\"taxType\":\"YHS\"},{\"bizType\":\"CGJXSHT\",\"configValueType\":\"VALUE\",\"taxRate\":\"0.03\",\"taxType\":\"YHS\"},{\"bizType\":\"JYZLHT\",\"configValueType\":\"VALUE\",\"taxRate\":\"0.1\",\"taxType\":\"YHS\"}]'),
	('PROVISION_RADIO', '拨备计提比例', '[{\"provisionRadio\":\"[1,3)\",\"projectType\":\"PUBLIC\",\"configValueType\":\"FORMULA\",\"assetClassify\":\"NORMAL\"},{\"provisionRadio\":\"3\",\"projectType\":\"PUBLIC\",\"configValueType\":\"VALUE\",\"assetClassify\":\"ATTENTION\"},{\"provisionRadio\":\"[15,25]\",\"projectType\":\"PUBLIC\",\"configValueType\":\"FORMULA\",\"assetClassify\":\"SECONDARY\"},{\"provisionRadio\":\"[30,50]\",\"projectType\":\"PUBLIC\",\"configValueType\":\"FORMULA\",\"assetClassify\":\"SUSPICIOUS\"},{\"provisionRadio\":\"100\",\"projectType\":\"PUBLIC\",\"configValueType\":\"VALUE\",\"assetClassify\":\"LOSS\"},{\"provisionRadio\":\"[1,3)\",\"projectType\":\"CONSTRUCTION_MACHINERY\",\"configValueType\":\"FORMULA\",\"assetClassify\":\"NORMAL\"},{\"provisionRadio\":\"3\",\"projectType\":\"CONSTRUCTION_MACHINERY\",\"configValueType\":\"VALUE\",\"assetClassify\":\"ATTENTION\"},{\"provisionRadio\":\"[15,25]\",\"projectType\":\"CONSTRUCTION_MACHINERY\",\"configValueType\":\"FORMULA\",\"assetClassify\":\"SECONDARY\"},{\"provisionRadio\":\"[30,50]\",\"projectType\":\"CONSTRUCTION_MACHINERY\",\"configValueType\":\"FORMULA\",\"assetClassify\":\"SUSPICIOUS\"},{\"provisionRadio\":\"100\",\"projectType\":\"CONSTRUCTION_MACHINERY\",\"configValueType\":\"VALUE\",\"assetClassify\":\"LOSS\"},{\"provisionRadio\":\"if(T<=3,\'[1,3)\',if(and(T>3,T<=5),\'[1.5,3)\',\'[2,3)\'))\",\"projectType\":\"OTHER\",\"configValueType\":\"FORMULA\",\"assetClassify\":\"NORMAL\"},{\"provisionRadio\":\"3\",\"projectType\":\"OTHER\",\"configValueType\":\"VALUE\",\"assetClassify\":\"ATTENTION\"},{\"provisionRadio\":\"[15,25]\",\"projectType\":\"OTHER\",\"configValueType\":\"FORMULA\",\"assetClassify\":\"SECONDARY\"},{\"provisionRadio\":\"[30,50]\",\"projectType\":\"OTHER\",\"configValueType\":\"FORMULA\",\"assetClassify\":\"SUSPICIOUS\"},{\"provisionRadio\":\"100\",\"projectType\":\"OTHER\",\"configValueType\":\"VALUE\",\"assetClassify\":\"LOSS\"}]'),
	('EXPENSE_RADIO', '费用计提比例', '{\"expenseRadio\":\"20\",\"configValueType\":\"VALUE\"}'),
	('PROJECT_RADIO', '项目提奖比例', '[{\"projectRadio\":\"6\",\"projectType\":\"INDUSTRY\",\"configValueType\":\"VALUE\",\"projectSource\":\"HISTORY\"},{\"projectRadio\":\"10\",\"projectType\":\"INDUSTRY\",\"configValueType\":\"VALUE\",\"projectSource\":\"NEW\"},{\"projectRadio\":\"1.5\",\"projectType\":\"PUBLIC\",\"configValueType\":\"VALUE\",\"projectSource\":\"HISTORY\"},{\"projectRadio\":\"2.5\",\"projectType\":\"PUBLIC\",\"configValueType\":\"VALUE\",\"projectSource\":\"NEW\"},{\"projectRadio\":\"7\",\"projectType\":\"FACTORY\",\"configValueType\":\"VALUE\",\"projectSource\":\"HISTORY\"},{\"projectRadio\":\"12\",\"projectType\":\"FACTORY\",\"configValueType\":\"VALUE\",\"projectSource\":\"NEW\"}]'),
	('DEPT_PROFIT_FINISH_RADIO', '部门利润完成率系数', '[{\"rangeCode\":\"RANGE1\",\"configValueType\":\"VALUE\",\"coefficient\":\"1.1\"},{\"rangeCode\":\"RANGE2\",\"configValueType\":\"VALUE\",\"coefficient\":\"1\"},{\"rangeCode\":\"RANGE3\",\"configValueType\":\"VALUE\",\"coefficient\":\"0.9\"},{\"rangeCode\":\"RANGE4\",\"configValueType\":\"VALUE\",\"coefficient\":\"0.8\"},{\"rangeCode\":\"RANGE5\",\"configValueType\":\"VALUE\",\"coefficient\":\"0.7\"}]'),
	('CAREER_LEVEL', '职等系数', '[{\"configValueType\":\"VALUE\",\"careerLevel\":\"B13\",\"coefficient\":\"1.1\"},{\"configValueType\":\"VALUE\",\"careerLevel\":\"B12\",\"coefficient\":\"1\"},{\"configValueType\":\"VALUE\",\"careerLevel\":\"B11\",\"coefficient\":\"0.9\"},{\"configValueType\":\"VALUE\",\"careerLevel\":\"B10\",\"coefficient\":\"0.8\"},{\"configValueType\":\"VALUE\",\"careerLevel\":\"B9\",\"coefficient\":\"0.75\"},{\"configValueType\":\"VALUE\",\"careerLevel\":\"B8\",\"coefficient\":\"0.75\"},{\"configValueType\":\"VALUE\",\"careerLevel\":\"M12\",\"coefficient\":\"1\"},{\"configValueType\":\"VALUE\",\"careerLevel\":\"M11\",\"coefficient\":\"0.9\"},{\"configValueType\":\"VALUE\",\"careerLevel\":\"M10\",\"coefficient\":\"0.8\"}]'),
	('BUSINESS_DEPT_ASSESS', '业务部门综合考评系数', '[{\"rangeCode\":\"RANGE1\",\"configValueType\":\"VALUE\",\"coefficient\":\"1.1\"},{\"rangeCode\":\"RANGE2\",\"configValueType\":\"VALUE\",\"coefficient\":\"1\"},{\"rangeCode\":\"RANGE3\",\"configValueType\":\"VALUE\",\"coefficient\":\"0.95\"},{\"rangeCode\":\"RANGE4\",\"configValueType\":\"FORMULA\",\"coefficient\":\"(P-60)/30*0.35+0.6\"},{\"rangeCode\":\"RANGE5\",\"configValueType\":\"VALUE\",\"coefficient\":\"0.6\"},{\"rangeCode\":\"RANGE6\",\"configValueType\":\"VALUE\",\"coefficient\":\"0\"}]'),
	('FINANCIAL_MARKET_DEPT_RADIO', '金融市场部提奖比例', '{\"financialMarketDeptRadio\":\"3\",\"configValueType\":\"\"}'),
	('PROFIT_ADJUST', '公司利润调节系数', '[{\"rangeCode\":\"RANGE1\",\"configValueType\":\"FORMULA\",\"coefficient\":\"max(1.2,(P-100)/100+1)\",\"group\":\"BEYOND\"},{\"rangeCode\":\"RANGE2\",\"configValueType\":\"VALUE\",\"coefficient\":\"1\",\"group\":\"REACH\"},{\"rangeCode\":\"RANGE3\",\"configValueType\":\"FORMULA\",\"coefficient\":\"(P-70)/100+0.8\",\"group\":\"DEDUCTION\"},{\"rangeCode\":\"RANGE4\",\"configValueType\":\"VALUE\",\"coefficient\":\"0.8\",\"group\":\"DEDUCTION\"}]'),
	('FINANCIAL_MARKET_DEPT_ASSESS', '金融市场部综合考评系数', '[{\"rangeCode\":\"RANGE1\",\"configValueType\":\"VALUE\",\"coefficient\":\"1.1\"},{\"rangeCode\":\"RANGE2\",\"configValueType\":\"VALUE\",\"coefficient\":\"1\"},{\"rangeCode\":\"RANGE3\",\"configValueType\":\"VALUE\",\"coefficient\":\"0.95\"},{\"rangeCode\":\"RANGE4\",\"configValueType\":\"FORMULA\",\"coefficient\":\"(P-60)/30*0.35+0.6\"},{\"rangeCode\":\"RANGE5\",\"configValueType\":\"VALUE\",\"coefficient\":\"0.6\"},{\"rangeCode\":\"RANGE6\",\"configValueType\":\"VALUE\",\"coefficient\":\"0\"}]'),
	('MIDDLE_BACK_DEPT_ASSESS', '中后台部门综合考评系数', '[{\"rangeCode\":\"RANGE1\",\"configValueType\":\"VALUE\",\"coefficient\":\"1.1\"},{\"rangeCode\":\"RANGE2\",\"configValueType\":\"VALUE\",\"coefficient\":\"1\"},{\"rangeCode\":\"RANGE3\",\"configValueType\":\"VALUE\",\"coefficient\":\"0.95\"},{\"rangeCode\":\"RANGE4\",\"configValueType\":\"VALUE\",\"coefficient\":\"0.9\"},{\"rangeCode\":\"RANGE5\",\"configValueType\":\"VALUE\",\"coefficient\":\"0.85\"},{\"rangeCode\":\"RANGE6\",\"configValueType\":\"VALUE\",\"coefficient\":\"0.8\"},{\"rangeCode\":\"RANGE7\",\"configValueType\":\"VALUE\",\"coefficient\":\"0.7\"},{\"rangeCode\":\"RANGE8\",\"configValueType\":\"VALUE\",\"coefficient\":\"0.6\"},{\"rangeCode\":\"RANGE9\",\"configValueType\":\"VALUE\",\"coefficient\":\"0\"}]');

-- feature/客户移交合同绩效分配-20250116

update kpi_project_distribution set approval_status = 'UN_SUBMIT' where approval_status in ('APPROVAL_REJECT', 'CANCELED');
