<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>zswl-mithras</artifactId>
        <groupId>cn.zswltech</groupId>
        <version>${revision}</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>zswl-mithras-third</artifactId>

    <properties>
        <maven.compiler.source>8</maven.compiler.source>
        <maven.compiler.target>8</maven.compiler.target>
    </properties>

    <dependencies>
        <dependency>
            <groupId>cn.zswltech</groupId>
            <artifactId>zswl-mithras-api</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>cn.zswltech</groupId>
            <artifactId>zswl-mithras-service-core</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>cn.zswltech</groupId>
            <artifactId>zswl-mithras-customer</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>cn.zswltech</groupId>
            <artifactId>zswl-mithras-fund</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>cn.zswltech</groupId>
            <artifactId>zswl-mithras-domain-basedata</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>cn.zswltech</groupId>
            <artifactId>gruul-spring-boot-starter</artifactId>
            <version>3.5.2-mithras.RELEASE</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-boot-starter</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>cn.hutool</groupId>
            <artifactId>hutool-all</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-context</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-context-support</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>javax.validation</groupId>
            <artifactId>validation-api</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>io.swagger</groupId>
            <artifactId>swagger-annotations</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-web</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.data</groupId>
            <artifactId>spring-data-redis</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-test</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.squareup.okhttp3</groupId>
            <artifactId>okhttp</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.httpcomponents</groupId>
            <artifactId>httpclient</artifactId>
            <version>${httpcomponents.version}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>cn.zswltech.cloud</groupId>
            <artifactId>spring-cloud-starter-zswl-feign</artifactId>
            <version>2.3.1</version>
        </dependency>
        <dependency>
            <groupId>com.zswltec</groupId>
            <artifactId>providence-api</artifactId>
        </dependency>
        <dependency>
            <groupId>cn.zswltech.flow</groupId>
            <artifactId>core</artifactId>
            <version>1.5.11-mithras-RELEASE</version>
            <scope>provided</scope>
            <exclusions>
                <exclusion>
                    <groupId>org.flywaydb</groupId>
                    <artifactId>flyway-core</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>net.qiyuesuo.sdk</groupId>
            <artifactId>private-java-sdk</artifactId>
            <version>4.3.4</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.pdfbox</groupId>
            <artifactId>pdfbox</artifactId>
            <version>2.0.25</version>
            <scope>provided</scope>
        </dependency>
    </dependencies>
</project>
