CREATE TABLE `asset_classify` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `year` int(11) NOT NULL COMMENT '年份',
  `quarter` tinyint(4) NOT NULL COMMENT '季度',
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间',
  `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `create_by` bigint(20) DEFAULT NULL COMMENT '创建人',
  `update_by` bigint(20) DEFAULT NULL COMMENT '更新人',
  `classify_amount` json DEFAULT NULL COMMENT '五级分类数据',
  `finish` tinyint(4) DEFAULT NULL COMMENT '是否结束，0-否，1-是',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='资产五级分类';

CREATE TABLE `asset_classify_check_content` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `asset_classify_id` bigint(20) NOT NULL COMMENT '资产五级分类id',
  `asset_classify_client_id` bigint(20) NOT NULL COMMENT '资产检查客户表主键id',
  `template_id` bigint(20) DEFAULT NULL COMMENT '检查内容模板id',
  `template_group_name` varchar(50) DEFAULT NULL COMMENT '检查内容模板分组名称',
  `template_code` varchar(50) DEFAULT NULL COMMENT '检查内容模板条目code',
  `template_title` varchar(100) NOT NULL COMMENT '检查内容模板条目',
  `template_content_input_type` varchar(20) NOT NULL COMMENT '检查内容模板输入框类型',
  `template_content_input_option` varchar(100) DEFAULT NULL COMMENT '检查内容模板输入框枚举类型（如果是下拉框等才会有值）',
  `template_order_num` int(11) NOT NULL DEFAULT '0' COMMENT '检查模板条目排序',
  `content` varchar(2000) DEFAULT NULL COMMENT '填写的检查内容',
  `create_by` bigint(20) DEFAULT NULL COMMENT '创建人、发起人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` bigint(20) DEFAULT NULL COMMENT '最后更新人id',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `after_lease_check_plan_project_id` bigint(20) DEFAULT NULL COMMENT '租后检查计划ID',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_asset_classify_id` (`asset_classify_id`),
  KEY `idx_asset_classify_client_id` (`asset_classify_client_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='五级分类检查报告检查内容表';

CREATE TABLE `asset_classify_check_content_auxiliary_lib` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `asset_classify_id` bigint(20) NOT NULL COMMENT '资产五级分类id',
  `asset_classify_client_id` bigint(20) NOT NULL COMMENT '检查计划项目表主键id',
  `template_id` bigint(20) DEFAULT NULL COMMENT '检查内容模板id',
  `template_group_name` varchar(50) DEFAULT NULL COMMENT '检查内容模板分组名称',
  `template_code` varchar(50) DEFAULT NULL COMMENT '检查内容模板条目code',
  `template_title` varchar(100) NOT NULL COMMENT '检查内容模板条目',
  `template_content_input_type` varchar(20) NOT NULL COMMENT '检查内容模板输入框类型',
  `template_content_input_option` varchar(100) DEFAULT NULL COMMENT '检查内容模板输入框枚举类型（如果是下拉框等才会有值）',
  `template_order_num` int(11) NOT NULL DEFAULT '0' COMMENT '检查模板条目排序',
  `content` varchar(2000) DEFAULT NULL COMMENT '填写的检查内容',
  `create_by` bigint(20) DEFAULT NULL COMMENT '创建人、发起人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` bigint(20) DEFAULT NULL COMMENT '最后更新人id',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `version` varchar(40) NOT NULL COMMENT '版本号',
  `origin_id` bigint(20) NOT NULL COMMENT '临时数据表id 需要用来比对数据 或者 流程拒绝时全量回写',
  `data_create_time` datetime DEFAULT NULL,
  `data_create_by` bigint(20) DEFAULT NULL,
  `data_update_time` datetime DEFAULT NULL,
  `data_update_by` bigint(20) DEFAULT NULL,
  `version_type` tinyint(4) DEFAULT '1' COMMENT '版本标志，0无效，1有效...业务自扩展',
  `after_lease_check_plan_project_id` bigint(20) DEFAULT NULL COMMENT '租后检查计划ID',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_asset_classify_id` (`asset_classify_id`),
  KEY `idx_asset_classify_client_id` (`asset_classify_client_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='五级分类检查报告检查内容表_版本表（作为大流程子表）';

CREATE TABLE `asset_classify_check_content_lib` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `asset_classify_id` bigint(20) NOT NULL COMMENT '资产五级分类id',
  `asset_classify_client_id` bigint(20) NOT NULL COMMENT '检查计划项目表主键id',
  `template_id` bigint(20) DEFAULT NULL COMMENT '检查内容模板id',
  `template_group_name` varchar(50) DEFAULT NULL COMMENT '检查内容模板分组名称',
  `template_code` varchar(50) DEFAULT NULL COMMENT '检查内容模板条目code',
  `template_title` varchar(100) NOT NULL COMMENT '检查内容模板条目',
  `template_content_input_type` varchar(20) NOT NULL COMMENT '检查内容模板输入框类型',
  `template_content_input_option` varchar(100) DEFAULT NULL COMMENT '检查内容模板输入框枚举类型（如果是下拉框等才会有值）',
  `template_order_num` int(11) NOT NULL DEFAULT '0' COMMENT '检查模板条目排序',
  `content` varchar(2000) DEFAULT NULL COMMENT '填写的检查内容',
  `create_by` bigint(20) DEFAULT NULL COMMENT '创建人、发起人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` bigint(20) DEFAULT NULL COMMENT '最后更新人id',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `version` varchar(40) NOT NULL COMMENT '版本号',
  `origin_id` bigint(20) NOT NULL COMMENT '临时数据表id 需要用来比对数据 或者 流程拒绝时全量回写',
  `data_create_time` datetime DEFAULT NULL,
  `data_create_by` bigint(20) DEFAULT NULL,
  `data_update_time` datetime DEFAULT NULL,
  `data_update_by` bigint(20) DEFAULT NULL,
  `version_type` tinyint(4) DEFAULT '1' COMMENT '版本标志，0无效，1有效...业务自扩展',
  `after_lease_check_plan_project_id` bigint(20) DEFAULT NULL COMMENT '租后检查计划ID',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_asset_classify_id` (`asset_classify_id`),
  KEY `idx_asset_classify_client_id` (`asset_classify_client_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='五级分类检查报告检查内容表_版本表';

CREATE TABLE `asset_classify_client` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `asset_classify_id` bigint(20) NOT NULL COMMENT '资产五级分类主表id',
  `client_id` bigint(20) NOT NULL COMMENT '客户id',
  `client_name` varchar(100) NOT NULL DEFAULT '' COMMENT '客户名称',
  `amount` bigint(20) NOT NULL COMMENT '投放金额',
  `remaining_term` int(11) NOT NULL COMMENT '剩余租期',
  `qualitative_adjust` tinyint(4) DEFAULT NULL COMMENT '定性调整',
  `last_classify_result` varchar(20) DEFAULT NULL COMMENT '上次分类结果',
  `init_classify_result` varchar(20) DEFAULT NULL COMMENT '初分结果',
  `classify_result` varchar(20) DEFAULT NULL COMMENT '本次分类结果',
  `review_status` varchar(20) NOT NULL COMMENT '复核状态',
  `review_pass_time` datetime DEFAULT NULL COMMENT '复核通过时间',
  `belong_dept_id` bigint(20) NOT NULL COMMENT '归属部门id',
  `belong_sponsor_id` bigint(20) NOT NULL COMMENT '归属主办id',
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间',
  `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `create_by` bigint(20) DEFAULT NULL COMMENT '创建人',
  `update_by` bigint(20) DEFAULT NULL COMMENT '更新人',
  `suggest_result` varchar(50) DEFAULT NULL COMMENT '建议分类结果',
  `remark` varchar(1000) DEFAULT NULL COMMENT '备注',
  `overdue_days` int(11) DEFAULT NULL COMMENT '逾期天数',
  `overdue_amount` bigint(20) DEFAULT NULL COMMENT '逾期金额 该季度该客户的逾期金额',
  `stock_risk_exposure` bigint(20) DEFAULT NULL COMMENT '存量风险敞口',
  `contract_expiration_date` datetime DEFAULT NULL COMMENT '合同到期日',
  `start_rent_contract_codes` json DEFAULT NULL COMMENT '在租合同编号',
  `start_rent_contractRemainingPrincipal` json DEFAULT NULL COMMENT '在租合同剩余本金',
  `board_meeting` tinyint(4) NOT NULL DEFAULT '0' COMMENT '是否进入董事会流程，0-否，1-是',
  PRIMARY KEY (`id`),
  KEY `idx_asset_classify_id` (`asset_classify_id`),
  KEY `idx_client_id` (`client_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='资产五级分类客户信息';

CREATE TABLE `asset_classify_client_auxiliary_lib` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `asset_classify_id` bigint(20) NOT NULL COMMENT '资产五级分类主表id',
  `client_id` bigint(20) NOT NULL COMMENT '客户id',
  `client_name` varchar(100) NOT NULL DEFAULT '' COMMENT '客户名称',
  `amount` bigint(20) NOT NULL COMMENT '投放金额',
  `remaining_term` int(11) NOT NULL COMMENT '剩余租期',
  `qualitative_adjust` tinyint(4) DEFAULT NULL COMMENT '定性调整',
  `last_classify_result` varchar(20) DEFAULT NULL COMMENT '上次分类结果',
  `init_classify_result` varchar(20) DEFAULT NULL COMMENT '初分结果',
  `classify_result` varchar(20) DEFAULT NULL COMMENT '本次分类结果',
  `review_status` varchar(20) NOT NULL COMMENT '复核状态',
  `review_pass_time` datetime DEFAULT NULL COMMENT '复核通过时间',
  `belong_dept_id` bigint(20) NOT NULL COMMENT '归属部门id',
  `belong_sponsor_id` bigint(20) NOT NULL COMMENT '归属主办id',
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间',
  `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `create_by` bigint(20) DEFAULT NULL COMMENT '创建人',
  `update_by` bigint(20) DEFAULT NULL COMMENT '更新人',
  `suggest_result` varchar(50) DEFAULT NULL COMMENT '建议分类结果',
  `remark` varchar(1000) DEFAULT NULL COMMENT '备注',
  `overdue_days` int(11) DEFAULT NULL COMMENT '逾期天数',
  `overdue_amount` bigint(20) DEFAULT NULL COMMENT '逾期金额 该季度该客户的逾期金额',
  `stock_risk_exposure` bigint(20) DEFAULT NULL COMMENT '存量风险敞口',
  `contract_expiration_date` datetime DEFAULT NULL COMMENT '合同到期日',
  `start_rent_contract_codes` json DEFAULT NULL COMMENT '在租合同编号',
  `start_rent_contractRemainingPrincipal` json DEFAULT NULL COMMENT '在租合同剩余本金',
  `board_meeting` tinyint(4) NOT NULL DEFAULT '0' COMMENT '是否进入董事会流程，0-否，1-是',
  `version` varchar(40) NOT NULL COMMENT '版本号',
  `origin_id` bigint(20) NOT NULL COMMENT '临时数据表id 需要用来比对数据 或者 流程拒绝时全量回写',
  `data_create_time` datetime DEFAULT NULL,
  `data_create_by` bigint(20) DEFAULT NULL,
  `data_update_time` datetime DEFAULT NULL,
  `data_update_by` bigint(20) DEFAULT NULL,
  `version_type` tinyint(4) DEFAULT '1' COMMENT '版本标志，0无效，1有效...业务自扩展',
  PRIMARY KEY (`id`),
  KEY `idx_asset_classify_id` (`asset_classify_id`),
  KEY `idx_client_id` (`client_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='资产五级分类客户信息辅助版本表(作为子表版本)';

CREATE TABLE `asset_classify_client_lib` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `asset_classify_id` bigint(20) NOT NULL COMMENT '资产五级分类主表id',
  `client_id` bigint(20) NOT NULL COMMENT '客户id',
  `client_name` varchar(100) NOT NULL DEFAULT '' COMMENT '客户名称',
  `amount` bigint(20) NOT NULL COMMENT '投放金额',
  `remaining_term` int(11) NOT NULL COMMENT '剩余租期',
  `qualitative_adjust` tinyint(4) DEFAULT NULL COMMENT '定性调整',
  `last_classify_result` varchar(20) DEFAULT NULL COMMENT '上次分类结果',
  `init_classify_result` varchar(20) DEFAULT NULL COMMENT '初分结果',
  `classify_result` varchar(20) DEFAULT NULL COMMENT '本次分类结果',
  `review_status` varchar(20) NOT NULL COMMENT '复核状态',
  `review_pass_time` datetime DEFAULT NULL COMMENT '复核通过时间',
  `belong_dept_id` bigint(20) NOT NULL COMMENT '归属部门id',
  `belong_sponsor_id` bigint(20) NOT NULL COMMENT '归属主办id',
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间',
  `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `create_by` bigint(20) DEFAULT NULL COMMENT '创建人',
  `update_by` bigint(20) DEFAULT NULL COMMENT '更新人',
  `suggest_result` varchar(50) DEFAULT NULL COMMENT '建议分类结果',
  `remark` varchar(1000) DEFAULT NULL COMMENT '备注',
  `overdue_days` int(11) DEFAULT NULL COMMENT '逾期天数',
  `overdue_amount` bigint(20) DEFAULT NULL COMMENT '逾期金额 该季度该客户的逾期金额',
  `stock_risk_exposure` bigint(20) DEFAULT NULL COMMENT '存量风险敞口',
  `contract_expiration_date` datetime DEFAULT NULL COMMENT '合同到期日',
  `start_rent_contract_codes` json DEFAULT NULL COMMENT '在租合同编号',
  `start_rent_contractRemainingPrincipal` json DEFAULT NULL COMMENT '在租合同剩余本金',
  `board_meeting` tinyint(4) NOT NULL DEFAULT '0' COMMENT '是否经过董事会流程，0-否，1-是',
  `version` varchar(40) NOT NULL COMMENT '版本号',
  `origin_id` bigint(20) NOT NULL COMMENT '临时数据表id 需要用来比对数据 或者 流程拒绝时全量回写',
  `data_create_time` datetime DEFAULT NULL,
  `data_create_by` bigint(20) DEFAULT NULL,
  `data_update_time` datetime DEFAULT NULL,
  `data_update_by` bigint(20) DEFAULT NULL,
  `version_type` tinyint(4) DEFAULT '1' COMMENT '版本标志，0无效，1有效...业务自扩展',
  PRIMARY KEY (`id`),
  KEY `idx_asset_classify_id` (`asset_classify_id`),
  KEY `idx_client_id` (`client_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='资产五级分类客户信息版本表';

CREATE TABLE `asset_classify_lib` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `year` int(11) NOT NULL COMMENT '年份',
  `quarter` tinyint(4) NOT NULL COMMENT '季度',
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间',
  `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `create_by` bigint(20) DEFAULT NULL COMMENT '创建人',
  `update_by` bigint(20) DEFAULT NULL COMMENT '更新人',
  `classify_amount` json DEFAULT NULL COMMENT '五级分类数据',
  `finish` tinyint(4) DEFAULT NULL COMMENT '是否结束，0-否，1-是',
  `version` varchar(40) NOT NULL COMMENT '版本号',
  `origin_id` bigint(20) NOT NULL COMMENT '临时数据表id 需要用来比对数据 或者 流程拒绝时全量回写',
  `data_create_time` datetime DEFAULT NULL,
  `data_create_by` bigint(20) DEFAULT NULL,
  `data_update_time` datetime DEFAULT NULL,
  `data_update_by` bigint(20) DEFAULT NULL,
  `version_type` tinyint(4) DEFAULT '1' COMMENT '版本标志，0无效，1有效...业务自扩展',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='资产五级分类版本表';

CREATE TABLE `asset_classify_node_record` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `asset_classify_id` bigint(20) NOT NULL COMMENT '资产五级分类主表id',
  `node_name` varchar(20) NOT NULL COMMENT '节点名称',
  `start_time` datetime DEFAULT NULL COMMENT '节点开始时间',
  `end_time` datetime DEFAULT NULL COMMENT '节点结束时间',
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间',
  `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `create_by` bigint(20) DEFAULT NULL COMMENT '创建人',
  `update_by` bigint(20) DEFAULT NULL COMMENT '更新人',
  `node_statue` varchar(50) DEFAULT NULL COMMENT '节点所处状态',
  PRIMARY KEY (`id`),
  KEY `idx_asset_classify_id` (`asset_classify_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='资产五级分类流程节点记录';

CREATE TABLE `asset_classify_node_record_lib` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `asset_classify_id` bigint(20) NOT NULL COMMENT '资产五级分类主表id',
  `node_name` varchar(20) NOT NULL COMMENT '节点名称',
  `start_time` datetime DEFAULT NULL COMMENT '节点开始时间',
  `end_time` datetime DEFAULT NULL COMMENT '节点结束时间',
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间',
  `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `create_by` bigint(20) DEFAULT NULL COMMENT '创建人',
  `update_by` bigint(20) DEFAULT NULL COMMENT '更新人',
  `node_statue` varchar(50) DEFAULT NULL COMMENT '节点所处状态',
  `version` varchar(40) NOT NULL COMMENT '版本号',
  `origin_id` bigint(20) NOT NULL COMMENT '临时数据表id 需要用来比对数据 或者 流程拒绝时全量回写',
  `data_create_time` datetime DEFAULT NULL,
  `data_create_by` bigint(20) DEFAULT NULL,
  `data_update_time` datetime DEFAULT NULL,
  `data_update_by` bigint(20) DEFAULT NULL,
  `version_type` tinyint(4) DEFAULT '1' COMMENT '版本标志，0无效，1有效...业务自扩展',
  PRIMARY KEY (`id`),
  KEY `idx_asset_classify_id` (`asset_classify_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='资产五级分类流程节点记录版本表';
