<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>zswl-mithras</artifactId>
        <groupId>cn.zswltech</groupId>
        <version>${revision}</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>zswl-mithras-domain-metric</artifactId>

    <properties>
        <maven.compiler.source>8</maven.compiler.source>
        <maven.compiler.target>8</maven.compiler.target>
        <juel.version>2.2.7</juel.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>cn.zswltech</groupId>
            <artifactId>zswl-mithras-api</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>cn.zswltech</groupId>
            <artifactId>zswl-mithras-service-core</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>cn.zswltech</groupId>
            <artifactId>zswl-mithras-domain-basedata</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-boot-starter</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>cn.hutool</groupId>
            <artifactId>hutool-all</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>cn.zswltech.lib</groupId>
            <artifactId>crypto-open-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>de.odysseus.juel</groupId>
            <artifactId>juel-api</artifactId>
            <version>${juel.version}</version>
        </dependency>
        <dependency>
            <groupId>de.odysseus.juel</groupId>
            <artifactId>juel-impl</artifactId>
            <version>${juel.version}</version>
        </dependency>
        <dependency>
            <groupId>de.odysseus.juel</groupId>
            <artifactId>juel-spi</artifactId>
            <version>${juel.version}</version>
        </dependency>
    </dependencies>
</project>
