// 转换资产负债表数据的函数
import financialReportApi from '@/api/financialReport/financialReportApi'

// 资产负债表数据配置
const balanceSheetColumns = [
  {
    item: '流动资产：',
    itemLevel: 0,
    item2: '流动负债：',
    itemLevel2: 0,
  },
  {
    item: '货币资金',
    order: 1,
    endValueKey: 'crcpAeop',
    startValueKey: 'crcpAboy',
    item2: '短期借款',
    order2: 38,
    endValue2Key: 'shttLoanAeop',
    startValue2Key: 'shttLoanAboy',
  },
  {
    item: '交易性金融资产',
    order: 2,
    endValueKey: 'trdFinlAstAeop',
    startValueKey: 'trdFinlAstAboy',
    item2: '交易性金融负债',
    order2: 39,
    endValue2Key: 'trdFinlLiabAeop',
    startValue2Key: 'trdFinlLiabAboy',
  },
  {
    item: '衍生金融资产',
    order: 3,
    endValueKey: 'devdFinlAstAeop',
    startValueKey: 'devdFinlAstAboy',
    item2: '衍生金融负债',
    order2: 40,
    endValue2Key: 'devdFinlLiabAeop',
    startValue2Key: 'devdFinlLiabAboy',
  },
  {
    item: '应收票据',
    order: 4,
    endValueKey: 'recvBillAeop',
    startValueKey: 'recvBillAboy',
    item2: '应付票据',
    order2: 41,
    endValue2Key: 'paybBillAeop',
    startValue2Key: 'paybBillAboy',
  },
  {
    item: '应收账款',
    order: 5,
    endValueKey: 'recvAmtAeop',
    startValueKey: 'recvAmtAboy',
    item2: '应付账款',
    order2: 42,
    endValue2Key: 'paybAmtAeop',
    startValue2Key: 'paybAmtAboy',
  },
  {
    item: '应收款项融资',
    order: 6,
    endValueKey: 'recvAmtFinAeop',
    startValueKey: 'recvAmtFinAboy',
    item2: '预收账款',
    order2: 43,
    endValue2Key: 'ciadAmtAeop',
    startValue2Key: 'ciadAmtAboy',
  },
  {
    item: '预付款项',
    order: 7,
    endValueKey: 'piaAmtAeop',
    startValueKey: 'piaAmtAboy',
    item2: '合同负债',
    order2: 44,
    endValue2Key: 'agmtLiabAeop',
    startValue2Key: 'agmtLiabAboy',
  },
  {
    item: '其他应收款',
    order: 8,
    endValueKey: 'othRecvAmtAeop',
    startValueKey: 'othRecvAmtAboy',
    item2: '应付职工薪酬',
    order2: 45,
    endValue2Key: 'paybEmpCmpsAeop',
    startValue2Key: 'paybEmpCmpsAboy',
  },
  {
    item: '其中：应收利息',
    order: 9,
    itemLevel: 2,
    endValueKey: 'recvIntrAeop',
    startValueKey: 'recvIntrAboy',
    item2: '应交税费',
    order2: 46,
    endValue2Key: 'paycTaxFeeAeop',
    startValue2Key: 'paycTaxFeeAboy',
  },
  {
    item: '应收股利',
    order: 10,
    itemLevel: 2,
    endValueKey: 'recvDivdAeop',
    startValueKey: 'recvDivdAboy',
    item2: '其他应付款',
    order2: 47,
    endValue2Key: 'othPaybAmtAeop',
    startValue2Key: 'othPaybAmtAboy',
  },
  {
    item: '其他应收款',
    order: 11,
    itemLevel: 2,
    endValueKey: 'othRecvAmtAeop',
    startValueKey: 'othRecvAmtAboy',
    item2: '其中：应付利息',
    order2: 48,
    itemLevel2: 2,
    endValue2Key: 'paybIntrAeop',
    startValue2Key: 'paybIntrAboy',
  },
  {
    item: '存货',
    order: 12,
    endValueKey: 'invAeop',
    startValueKey: 'invAboy',
    item2: '应付股利',
    order2: 49,
    endValue2Key: 'paybDivdAeop',
    startValue2Key: 'paybDivdAboy',
  },
  {
    item: '合同资产',
    order: 13,
    endValueKey: 'agmtAstAeop',
    startValueKey: 'agmtAstAboy',
    item2: '其他应付款',
    order2: 50,
    endValue2Key: 'othPaybAmtAeop',
    startValue2Key: 'othPaybAmtAboy',
  },
  {
    item: '持有待售资产',
    order: 14,
    endValueKey: 'holdSaleAstAeop',
    startValueKey: 'holdSaleAstAboy',
    item2: '持有待售负债',
    order2: 51,
    endValue2Key: 'holdSaleLiabAeop',
    startValue2Key: 'holdSaleLiabAboy',
  },
  {
    item: '一年内到期的非流动资产',
    order: 15,
    endValueKey: 'ncoyAeop',
    startValueKey: 'ncoyAboy',
    item2: '一年内到期的非流动负债',
    order2: 52,
    endValue2Key: 'oneyNocrLiabAeop',
    startValue2Key: 'oneyNocrLiabAboy',
  },
  {
    item: '其他流动资产',
    order: 16,
    endValueKey: 'othLiqdAstAeop',
    startValueKey: 'othLiqdAstAboy',
    item2: '其他流动负债',
    order2: 53,
    endValue2Key: 'othLiqdLiabAeop',
    startValue2Key: 'othLiqdLiabAboy',
  },
  {
    item: '流动资产合计',
    order: 17,
    endValueKey: 'liqdAstTotAeop',
    startValueKey: 'liqdAstTotAboy',
    item2: '流动负债合计',
    order2: 54,
    endValue2Key: 'liqdLiabTotAeop',
    startValue2Key: 'liqdLiabTotAboy',
  },
  {
    item: '非流动资产：',
    itemLevel: 0,
    item2: '非流动负债：',
    itemLevel2: 0,
  },
  {
    item: '债权投资',
    order: 18,
    endValueKey: 'clamIvsmAeop',
    startValueKey: 'clamIvsmAboy',
    item2: '长期借款',
    order2: 55,
    endValue2Key: 'longLoanAeop',
    startValue2Key: 'longLoanAboy',
  },
  {
    item: '其他债权投资',
    order: 19,
    endValueKey: 'othClamIvsmAeop',
    startValueKey: 'othClamIvsmAboy',
    item2: '应付债券',
    order2: 56,
    endValue2Key: 'paybBondAeop',
    startValue2Key: 'paybBondAboy',
  },
  {
    item: '长期应收款',
    order: 20,
    endValueKey: 'longRecvAmtAeop',
    startValueKey: 'longRecvAmtAboy',
    item2: '长期应付款',
    order2: 57,
    endValue2Key: 'longPaybAmtAeop',
    startValue2Key: 'longPaybAmtAboy',
  },
  {
    item: '长期股权投资',
    order: 21,
    endValueKey: 'lsriAeop',
    startValueKey: 'lsriAboy',
    item2: '长期应付职工薪酬',
    order2: 58,
    endValue2Key: 'longPaybEmpCmpsAeop',
    startValue2Key: 'longPaybEmpCmpsAboy',
  },
  {
    item: '其他权益工具投资',
    order: 22,
    endValueKey: 'othEquiInstIvsmAeop',
    startValueKey: 'othEquiInstIvsmAboy',
    item2: '租赁负债',
    order2: 59,
    endValue2Key: 'leasLiabAeop',
    startValue2Key: 'leasLiabAboy',
  },
  {
    item: '其他非流动金融资产',
    order: 23,
    endValueKey: 'othNocrFinlAstAeop',
    startValueKey: 'othNocrFinlAstAboy',
    item2: '预计负债',
    order2: 60,
    endValue2Key: 'expeLiabAeop',
    startValue2Key: 'expeLiabAboy',
  },
  {
    item: '投资性房地产',
    order: 24,
    endValueKey: 'ivsmEsttAeop',
    startValueKey: 'ivsmEsttAboy',
    item2: '递延收益',
    order2: 61,
    endValue2Key: 'defrPayfAeop',
    startValue2Key: 'defrPayfAboy',
  },
  {
    item: '固定资产',
    order: 25,
    endValueKey: 'fixAstAeop',
    startValueKey: 'fixAstAboy',
    item2: '递延所得税负债',
    order2: 62,
    endValue2Key: 'defrInctLiabAeop',
    startValue2Key: 'defrInctLiabAboy',
  },
  {
    item: '在建工程',
    order: 26,
    endValueKey: 'udcsProjAeop',
    startValueKey: 'udcsProjAboy',
    item2: '其他非流动负债',
    order2: 63,
    endValue2Key: 'othNocrLiabAeop',
    startValue2Key: 'othNocrLiabAboy',
  },
  {
    item: '生产性生物资产',
    order: 27,
    endValueKey: 'prodBiolMatrAeop',
    startValueKey: 'prodBiolMatrAboy',
    item2: '非流动负债合计',
    order2: 64,
    endValue2Key: 'nocrLiabTotAeop',
    startValue2Key: 'nocrLiabTotAboy',
  },
  {
    item: '油气资产',
    order: 28,
    endValueKey: 'olgsAstAeop',
    startValueKey: 'olgsAstAboy',
    item2: '负债合计',
    order2: 65,
    endValue2Key: 'liabTotAeop',
    startValue2Key: 'liabTotAboy',
  },
  {
    item: '使用权资产',
    order: 29,
    endValueKey: 'useAstAeop',
    startValueKey: 'useAstAboy',
    item2: '所有者权益：',
    itemLevel2: 0,
  },
  {
    item: '无形资产',
    order: 30,
    endValueKey: 'imtrAstAeop',
    startValueKey: 'imtrAstAboy',
    item2: '实收资本',
    order2: 66,
    endValue2Key: 'paidCptlAeop',
    startValue2Key: 'paidCptlAboy',
  },
  {
    item: '开发支出',
    order: 31,
    endValueKey: 'devPayAeop',
    startValueKey: 'devPayAboy',
    item2: '其他权益工具',
    order2: 67,
    endValue2Key: 'othEquiInstAeop',
    startValue2Key: 'othEquiInstAboy',
  },
  {
    item: '商誉',
    order: 32,
    endValueKey: 'gdwlAeop',
    startValueKey: 'gdwlAboy',
    item2: '资本公积',
    order2: 68,
    endValue2Key: 'cptlRsrvAeop',
    startValue2Key: 'cptlRsrvAboy',
  },
  {
    item: '长期待摊费用',
    order: 33,
    endValueKey: 'longTbatFeeAeop',
    startValueKey: 'longTbatFeeAboy',
    item2: '其他综合收益',
    order2: 69,
    endValue2Key: 'othCmphPayfAeop',
    startValue2Key: 'othCmphPayfAboy',
  },
  {
    item: '递延所得税资产',
    order: 34,
    endValueKey: 'defrTaxAstAeop',
    startValueKey: 'defrTaxAstAboy',
    item2: '专项储备',
    order2: 70,
    endValue2Key: 'spclRsrvAeop',
    startValue2Key: 'spclRsrvAboy',
  },
  {
    item: '其他非流动资产',
    order: 35,
    endValueKey: 'othNocrAstAeop',
    startValueKey: 'othNocrAstAboy',
    item2: '盈余公积',
    order2: 71,
    endValue2Key: 'surpRsrvAeop',
    startValue2Key: 'surpRsrvAboy',
  },
  {
    item: '非流动资产合计',
    order: 36,
    endValueKey: 'nocrAstTotAeop',
    startValueKey: 'nocrAstTotAboy',
    item2: '一般风险准备',
    order2: 72,
    endValue2Key: 'riskPrepAeop',
    startValue2Key: 'riskPrepAboy',
  },
  {
    item: '',
    item2: '未分配利润',
    order2: 73,
    endValue2Key: 'noAssnProfAeop',
    startValue2Key: 'noAssnProfAboy',
  },
  {
    item: '',
    item2: '归属母公司所有者权益合计',
    order2: 74,
    itemLevel2: 0,
    endValue2Key: 'attrPrnCponEquiAeop',
    startValue2Key: 'attrPrnCponEquiAboy',
  },
  {
    item: '',
    item2: '少数股东权益',
    order2: 75,
    endValue2Key: 'mishEquiAeop',
    startValue2Key: 'mishEquiAboy',
  },
  {
    item: '',
    item2: '所有者权益合计',
    order2: 76,
    itemLevel2: 0,
    endValue2Key: 'toeqAeop',
    startValue2Key: 'toeqAboy',
  },
  {
    item: '资产总计',
    order: 37,
    itemLevel: 0,
    endValueKey: 'astTotAeop',
    startValueKey: 'astTotAboy',
    item2: '负债及所有者权益总计',
    order2: 77,
    itemLevel2: 0,
    endValue2Key: 'liabToeqAeop',
    startValue2Key: 'liabToeqAboy',
  },
]

/**
 * 转换资产负债表数据
 * @param {Object} data - 原始数据对象
 * @returns {Array} 转换后的数据数组
 */
export const transformBalanceData = (data) => {
  if (!data) return []

  console.log('data: ', data)
  return balanceSheetColumns.map((column, index) => ({
    rowNum: index + 1,
    id: `balanceSheet_${index + 1}`,
    parentId: data.id,
    item: column.item,
    itemLevel: column.itemLevel,
    order: column.order,
    endValue: column.endValueKey ? data[column.endValueKey] : undefined,
    startValue: column.startValueKey ? data[column.startValueKey] : undefined,
    item2: column.item2,
    itemLevel2: column.itemLevel2,
    order2: column.order2,
    endValue2: column.endValue2Key ? data[column.endValue2Key] : undefined,
    startValue2: column.startValue2Key ? data[column.startValue2Key] : undefined,
  }))
}

/**
 * 资产负债表数据修改API
 * @param {Object} data - 包含id和各列数据的对象
 * @returns {Promise} API调用结果
 */
export const balanceSheetModifyApi = async ({ reportInstanceId, dataList: data }) => {
  const params = {
    reportInstanceId,
    id: data[0].parentId,
    ...balanceSheetColumns.reduce((acc, col, index) => {
      const record = data[index]
      // 处理左侧数据字段
      if (col.endValueKey) {
        acc[col.endValueKey] = record.endValue
      }
      if (col.startValueKey) {
        acc[col.startValueKey] = record.startValue
      }
      // 处理右侧数据字段
      if (col.endValue2Key) {
        acc[col.endValue2Key] = record.endValue2
      }
      if (col.startValue2Key) {
        acc[col.startValue2Key] = record.startValue2
      }
      return acc
    }, {}),
  }
  return await financialReportApi.postModifyBalanceSheetPartial(params)
}
